#!/bin/bash
set -euo pipefail

# PR Preview Comment Script
# Usage: ./scripts/preview/comment.sh <PR_NUMBER>

PR_NUMBER=${1:?PR number is required}
URL="https://pr-${PR_NUMBER}.preview.summit.ai"

echo "💬 Posting preview URL to PR #$PR_NUMBER..."

COMMENT_BODY="🚀 **Preview environment ready!**

🔗 [View Preview]($URL)

---
*Generated by Summit CI* 🤖"

# Check if gh CLI is available
if command -v gh &> /dev/null; then
    # Post the comment
    gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
    echo "✅ Comment posted to PR #$PR_NUMBER"
else
    echo "⚠️  gh CLI not found. Skipping comment."
    echo "Preview URL would be: $URL"
fi