/** @type {import('jest').Config} */
const config = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  moduleNameMapper: {
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/__mocks__/fileMock.js',
    '^dompurify$': '<rootDir>/__mocks__/dompurify.js',
    '^ansi-regex$': '<rootDir>/__mocks__/ansi-regex.js',
    '^@mui/material/Unstable_Grid2$': '<rootDir>/__mocks__/MuiGrid2.js',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^react$': '<rootDir>/../node_modules/react',
    '^react/(.*)$': '<rootDir>/../node_modules/react/$1',
    '^react/jsx-runtime$': '<rootDir>/../node_modules/react/jsx-runtime',
    '^react/jsx-dev-runtime$': '<rootDir>/../node_modules/react/jsx-dev-runtime',
    '^react-dom$': '<rootDir>/../node_modules/react-dom',
    '^react-dom/(.*)$': '<rootDir>/../node_modules/react-dom/$1',
    '^react-redux$': '<rootDir>/../node_modules/react-redux',
    '^@emotion/react$': '<rootDir>/../node_modules/@emotion/react',
    '^@emotion/styled$': '<rootDir>/../node_modules/@emotion/styled',
  },
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      useESM: true,
      tsconfig: {
        jsx: 'react-jsx',
      },
      diagnostics: false,
      stringifyContentPathRegex: '\\.(postcss|scss)$',
      babelConfig: true,
    }],
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  // Moved import.meta to setupFiles or just rely on the fact that
  // it might be handled by babel-jest/ts-jest if needed.
  // Actually, ts-jest documentation says for import.meta.env we should use:
  // but let's just keep it simple if possible.
  // The CI complained about "deprecated ts-jest globals syntax".
  testMatch: [
    '<rootDir>/src/**/*.test.{js,jsx,ts,tsx}',
    '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/main.tsx',
  ],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
  },
  coverageReporters: ['json-summary', 'text', 'lcov'],
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>/test-results',
        outputName: 'junit.xml',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
        ancestorSeparator: ' › ',
        usePathForSuiteName: true,
      },
    ],
  ],
  testPathIgnorePatterns: [
    '<rootDir>/src/tests/',
    '<rootDir>/src/__tests__/ServiceHealthCard.test.jsx',
    '<rootDir>/src/__tests__/Dashboard.test.jsx',
    '<rootDir>/src/__tests__/AlertBadge.test.js',
    '<rootDir>/src/__tests__/AlertBadge.test.jsx',
    '<rootDir>/src/__tests__/ConductorToolsEvidence.test.tsx',
    '<rootDir>/src/components/graph/__tests__/GraphContextMenu.test.jsx',
    '<rootDir>/src/components/graph/__tests__/AIInsightsPanel.test.jsx',
    '<rootDir>/src/components/visualization/__tests__/InteractiveGraphCanvas.test.tsx',
    '<rootDir>/src/components/mlops/__tests__/ModelManagementDashboard.test.tsx',
    '<rootDir>/src/components/dashboard/__tests__/StatsOverview.test.tsx',
    '<rootDir>/src/pages/DemoWalkthrough.test.jsx',
    '<rootDir>/src/pages/GraphWorkbench/__tests__/GraphCanvas.test.tsx',
    '<rootDir>/src/pages/Dashboard/__tests__/Dashboard.test.tsx',
    '<rootDir>/src/features/maestro/__tests__/MaestroApp.test.tsx',
    '<rootDir>/src/features/nlq/NlqModal.test.tsx',
    '<rootDir>/src/features/lho/LhoDashboard.test.tsx',
    '<rootDir>/src/features/conductor/__tests__/RunSearch.test.tsx',
    '<rootDir>/src/features/compliance/__tests__/DsarReviewer.test.tsx',
    '<rootDir>/src/components/explorer/__tests__/KGExplorer.test.tsx',
    '<rootDir>/src/components/ai-enhanced/hooks/useHoldToTalk.test.ts',
    '<rootDir>/src/components/ai-enhanced/__tests__/EnhancedAIAssistant.test.tsx',
    '<rootDir>/src/components/ai-enhanced/__tests__/assistant.abort.test.tsx',
    '<rootDir>/src/components/ai-enhanced/tests/assistant.chunking.fuzz.test.tsx',
    '<rootDir>/src/components/security/__tests__/VulnerabilityDashboard.test.tsx',
    '<rootDir>/src/components/hunting/__tests__/ThreatHuntingDashboard.test.tsx',
    '<rootDir>/src/components/governance/__tests__/GovernanceMetricsDashboard.test.tsx',
    '<rootDir>/src/components/intelligence/__tests__/ThreatIntelligenceHub.test.tsx',
    '<rootDir>/src/components/timeline/__tests__/TemporalAnalysis.test.tsx',
    '<rootDir>/src/components/common/__tests__/VirtualizedListTable.test.tsx',
    '<rootDir>/src/components/sigint/__tests__/useRedisStream.test.ts',
    '<rootDir>/src/components/sigint/__tests__/SIGINTDashboard.test.tsx',
    '<rootDir>/src/components/__tests__/PerformanceMonitor.test.tsx',
    '<rootDir>/src/components/admin/AdminDashboard.test.tsx',
    '<rootDir>/src/components/Switchboard/SystemStatusCard.test.tsx',
    '<rootDir>/src/switchboard/approvals/ApprovalsList.test.tsx',
    '<rootDir>/src/switchboard/approvals/__tests__/ApprovalsExperience.test.tsx',
    '<rootDir>/src/switchboard/audit/AuditTimeline.test.tsx',
    '<rootDir>/src/routes/__tests__/ActionDetailsRoute.test.tsx',
    '<rootDir>/src/auth/withAuthorization.test.tsx',
    '<rootDir>/src/services/socket.test.js',
    '<rootDir>/src/design-system/__tests__/designSystem.test.tsx',
    '<rootDir>/src/components/explorer/__tests__/useGraphData.test.ts',
    '<rootDir>/src/pages/Security/__tests__/SecurityPIIScanner.test.jsx',
    '<rootDir>/src/components/ai-enhanced/__tests__/assistant.chunking.test.tsx',
  ],
};

module.exports = config;
