/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApplicationConfiguration {
  /**
   * Configuration version for migration.
   */
  version: number;
  database: DatabaseConfiguration;
  auth: AuthenticationConfiguration;
  services?: ServicesConfiguration;
  features?: FeatureFlagsConfiguration;
  [k: string]: unknown;
}
export interface DatabaseConfiguration {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
  [k: string]: unknown;
}
export interface AuthenticationConfiguration {
  jwt: {
    secret: string;
    expiresIn: string;
    [k: string]: unknown;
  };
  apiKey?: {
    header: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ServicesConfiguration {
  redis?: {
    url: string;
    [k: string]: unknown;
  };
  neo4j?: {
    url: string;
    user: string;
    password: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface FeatureFlagsConfiguration {
  enableNewDashboard?: boolean;
  enableExperimentalFeatures?: boolean;
  [k: string]: unknown;
}
