"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TenantRepository = void 0;
const database_js_1 = require("../config/database.js");
class TenantRepository {
    pool;
    tableName;
    constructor(tableName) {
        this.pool = (0, database_js_1.getPostgresPool)();
        this.tableName = tableName;
    }
    async findById(tenantId, id) {
        const result = await this.pool.query(`SELECT * FROM ${this.tableName} WHERE id = $1 AND tenant_id = $2`, [id, tenantId]);
        return result.rows[0] || null;
    }
    async findAll(tenantId) {
        const result = await this.pool.query(`SELECT * FROM ${this.tableName} WHERE tenant_id = $1`, [tenantId]);
        return result.rows;
    }
    async create(tenantId, data) {
        const keys = Object.keys(data).filter(k => k !== 'id' && k !== 'tenant_id');
        const values = keys.map(k => data[k]);
        const placeholders = keys.map((_, i) => `$${i + 3}`); // $1 is tenant_id, $2 is generated id usually or we let DB do it.
        // We explicitly inject tenant_id.
        // Assuming ID is auto-generated by DB or we generate it.
        const query = `
        INSERT INTO ${this.tableName} (tenant_id, ${keys.join(', ')})
        VALUES ($1, ${keys.map((_, i) => `$${i + 2}`).join(', ')})
        RETURNING *
      `;
        const result = await this.pool.query(query, [tenantId, ...values]);
        return result.rows[0];
    }
    async update(tenantId, id, data) {
        const keys = Object.keys(data);
        if (keys.length === 0)
            return this.findById(tenantId, id);
        const setClause = keys.map((k, i) => `${k} = $${i + 3}`).join(', ');
        const query = `
        UPDATE ${this.tableName}
        SET ${setClause}, updated_at = NOW()
        WHERE id = $1 AND tenant_id = $2
        RETURNING *
      `;
        const result = await this.pool.query(query, [id, tenantId, ...keys.map(k => data[k])]);
        return result.rows[0] || null;
    }
    async delete(tenantId, id) {
        const result = await this.pool.query(`DELETE FROM ${this.tableName} WHERE id = $1 AND tenant_id = $2`, [id, tenantId]);
        return (result.rowCount ?? 0) > 0;
    }
}
exports.TenantRepository = TenantRepository;
