import { Pool, PoolClient, QueryResult } from 'pg';
import { getPostgresPool } from '../config/database.js';
import { TenantId } from '../types/identity.js';

export class TenantRepository<T> {
  protected pool: Pool;
  protected tableName: string;

  constructor(tableName: string) {
    this.pool = getPostgresPool();
    this.tableName = tableName;
  }

  async findById(tenantId: TenantId, id: string): Promise<T | null> {
    const result = await this.pool.query(
      `SELECT * FROM ${this.tableName} WHERE id = $1 AND tenant_id = $2`,
      [id, tenantId]
    );
    return result.rows[0] || null;
  }

  async findAll(tenantId: TenantId): Promise<T[]> {
    const result = await this.pool.query(
      `SELECT * FROM ${this.tableName} WHERE tenant_id = $1`,
      [tenantId]
    );
    return result.rows;
  }

  async create(tenantId: TenantId, data: Partial<T>): Promise<T> {
      const keys = Object.keys(data).filter(k => k !== 'id' && k !== 'tenant_id');
      const values = keys.map(k => (data as any)[k]);
      const placeholders = keys.map((_, i) => `$${i + 3}`); // $1 is tenant_id, $2 is generated id usually or we let DB do it.

      // We explicitly inject tenant_id.
      // Assuming ID is auto-generated by DB or we generate it.

      const query = `
        INSERT INTO ${this.tableName} (tenant_id, ${keys.join(', ')})
        VALUES ($1, ${keys.map((_, i) => `$${i + 2}`).join(', ')})
        RETURNING *
      `;

      const result = await this.pool.query(query, [tenantId, ...values]);
      return result.rows[0];
  }

  async update(tenantId: TenantId, id: string, data: Partial<T>): Promise<T | null> {
      const keys = Object.keys(data);
      if (keys.length === 0) return this.findById(tenantId, id);

      const setClause = keys.map((k, i) => `${k} = $${i + 3}`).join(', ');

      const query = `
        UPDATE ${this.tableName}
        SET ${setClause}, updated_at = NOW()
        WHERE id = $1 AND tenant_id = $2
        RETURNING *
      `;

      const result = await this.pool.query(query, [id, tenantId, ...keys.map(k => (data as any)[k])]);
      return result.rows[0] || null;
  }

  async delete(tenantId: TenantId, id: string): Promise<boolean> {
      const result = await this.pool.query(
          `DELETE FROM ${this.tableName} WHERE id = $1 AND tenant_id = $2`,
          [id, tenantId]
      );
      return (result.rowCount ?? 0) > 0;
  }
}
