// Implementation for types.ts
export interface Forecast {}
export interface ForecastBranch {}
export interface WorldStateSnapshot {}
export interface HistoricalAnalog {}
export interface NarrativeCluster {}
export interface InfluenceFlow {}
export interface InterventionOption {}
export interface DecisionRecord {}
export interface CognitiveInsight {}
export interface MissionCommandState {}
export interface AutonomousTask {}
export interface GovernanceGate {}
export interface OutcomeReview {}
