/**
 * Centralized metrics configuration
 * Re-exports from monitoring/metrics.js to maintain backward compatibility
 * while unifying the registry.
 */

import {
  register as registry,
  summitJobsProcessed as jobsProcessed,
  summitOutboxSyncLatency as outboxSyncLatency,
  summitActiveConnections as activeConnections,
  summitDatabaseQueryDuration as databaseQueryDuration,
  summitHttpRequestDuration as httpRequestDuration,
  summitGraphragQueryTotal as graphragQueryTotal,
  summitGraphragQueryDurationMs as graphragQueryDurationMs,
  summitQueryPreviewsTotal as queryPreviewsTotal,
  summitQueryPreviewLatencyMs as queryPreviewLatencyMs,
  summitQueryPreviewErrorsTotal as queryPreviewErrorsTotal,
  summitQueryPreviewExecutionsTotal as queryPreviewExecutionsTotal,
  summitGlassBoxRunsTotal as glassBoxRunsTotal,
  summitGlassBoxRunDurationMs as glassBoxRunDurationMs,
  summitGlassBoxCacheHits as glassBoxCacheHits,
  summitCacheHits as cacheHits,
  summitCacheMisses as cacheMisses,
  copilotApiRequestTotal,
  copilotApiRequestDurationMs,
  // Maestro Metrics
  maestroDagExecutionDurationSeconds,
  maestroJobExecutionDurationSeconds,
  // LLM Metrics
  llmTokensTotal,
  llmRequestDuration,
  // New Metrics from metrics.js
  intelgraphCacheHits,
  intelgraphCacheMisses,
  intelgraphActiveConnections,
  intelgraphDatabaseQueryDuration,
  intelgraphHttpRequestDuration,
  intelgraphGraphragQueryTotal,
  intelgraphGraphragQueryDurationMs,
  intelgraphQueryPreviewsTotal,
  intelgraphQueryPreviewLatencyMs,
  intelgraphQueryPreviewErrorsTotal,
  intelgraphQueryPreviewExecutionsTotal,
  intelgraphGlassBoxRunsTotal,
  intelgraphGlassBoxRunDurationMs,
  intelgraphGlassBoxCacheHits,
  goldenPathStepTotal,
  uiErrorBoundaryCatchTotal,
  maestroDeploymentsTotal,
  maestroPrLeadTimeHours,
  maestroChangeFailureRate,
  maestroMttrHours,
  // Standard metrics
  httpRequestsTotal as stdHttpRequestsTotal,
  httpRequestDuration as stdHttpRequestDuration,
  dbQueriesTotal,
  dbQueryDuration,
  websocketConnections,
  narrativeSimulationActiveSimulations,
  narrativeSimulationTicksTotal,
  narrativeSimulationEventsTotal,
  narrativeSimulationDurationSeconds,
  summitHealthChecksTotal,
  // CI Metrics
  ciRuntimeMinutes,
  ciTestFlakesTotal,
  mergeQueueThroughputTotal
} from '../monitoring/metrics.js';

export { registry };

export {
  jobsProcessed,
  outboxSyncLatency,
  activeConnections,
  databaseQueryDuration,
  httpRequestDuration,
  graphragQueryTotal,
  graphragQueryDurationMs,
  queryPreviewsTotal,
  queryPreviewLatencyMs,
  queryPreviewErrorsTotal,
  queryPreviewExecutionsTotal,
  glassBoxRunsTotal,
  glassBoxRunDurationMs,
  glassBoxCacheHits,
  cacheHits,
  cacheMisses,
  copilotApiRequestTotal,
  copilotApiRequestDurationMs,
  maestroDagExecutionDurationSeconds,
  maestroJobExecutionDurationSeconds,
  llmTokensTotal,
  llmRequestDuration,
  intelgraphCacheHits,
  intelgraphCacheMisses,
  intelgraphActiveConnections,
  intelgraphDatabaseQueryDuration,
  intelgraphHttpRequestDuration,
  intelgraphGraphragQueryTotal,
  intelgraphGraphragQueryDurationMs,
  intelgraphQueryPreviewsTotal,
  intelgraphQueryPreviewLatencyMs,
  intelgraphQueryPreviewErrorsTotal,
  intelgraphQueryPreviewExecutionsTotal,
  intelgraphGlassBoxRunsTotal,
  intelgraphGlassBoxRunDurationMs,
  intelgraphGlassBoxCacheHits,
  goldenPathStepTotal,
  uiErrorBoundaryCatchTotal,
  maestroDeploymentsTotal,
  maestroPrLeadTimeHours,
  maestroChangeFailureRate,
  maestroMttrHours,
  stdHttpRequestsTotal,
  stdHttpRequestDuration,
  dbQueriesTotal,
  dbQueryDuration,
  websocketConnections,
  narrativeSimulationActiveSimulations,
  narrativeSimulationTicksTotal,
  narrativeSimulationEventsTotal,
  narrativeSimulationDurationSeconds,
  summitHealthChecksTotal,
  ciRuntimeMinutes,
  ciTestFlakesTotal,
  mergeQueueThroughputTotal
};

export const metrics = {
  jobsProcessed,
  outboxSyncLatency,
  activeConnections,
  databaseQueryDuration,
  httpRequestDuration,
  graphragQueryTotal,
  graphragQueryDurationMs,
  queryPreviewsTotal,
  queryPreviewLatencyMs,
  queryPreviewErrorsTotal,
  queryPreviewExecutionsTotal,
  glassBoxRunsTotal,
  glassBoxRunDurationMs,
  glassBoxCacheHits,
  cacheHits,
  cacheMisses,
  copilotApiRequestTotal,
  copilotApiRequestDurationMs,
  maestroDagExecutionDurationSeconds,
  maestroJobExecutionDurationSeconds,
  llmTokensTotal,
  llmRequestDuration,
  intelgraphCacheHits,
  intelgraphCacheMisses,
  intelgraphActiveConnections,
  intelgraphDatabaseQueryDuration,
  intelgraphHttpRequestDuration,
  intelgraphGraphragQueryTotal,
  intelgraphGraphragQueryDurationMs,
  intelgraphQueryPreviewsTotal,
  intelgraphQueryPreviewLatencyMs,
  intelgraphQueryPreviewErrorsTotal,
  intelgraphQueryPreviewExecutionsTotal,
  intelgraphGlassBoxRunsTotal,
  intelgraphGlassBoxRunDurationMs,
  intelgraphGlassBoxCacheHits,
  goldenPathStepTotal,
  uiErrorBoundaryCatchTotal,
  maestroDeploymentsTotal,
  maestroPrLeadTimeHours,
  maestroChangeFailureRate,
  maestroMttrHours,
  stdHttpRequestsTotal,
  stdHttpRequestDuration,
  dbQueriesTotal,
  dbQueryDuration,
  websocketConnections,
  narrativeSimulationActiveSimulations,
  narrativeSimulationTicksTotal,
  narrativeSimulationEventsTotal,
  narrativeSimulationDurationSeconds,
  summitHealthChecksTotal,
  ciRuntimeMinutes,
  ciTestFlakesTotal,
  mergeQueueThroughputTotal
};
