import asyncio
import sys
from agent.prompt_loader import load_config, load_prompt_from_config
from agent.llm import LLM, LLMConfig
from agent.modules.interpreter import Interpreter
from agent.modules.executor import Executor
from agent.modules.verifier import Verifier
from agent.modules.documenter import Documenter
from agent.modules.devops import DevOps
from agent.modules.pr_manager import PRManager
from agent.orchestrator import Orchestrator

async def run(request: str):
    cfg = load_config()
    system_prompt = load_prompt_from_config(cfg)

    llm_cfg = LLMConfig(
        provider=cfg.get("llm_provider", "openai"),
        model=cfg.get("llm_model", "gpt-4"),
        temperature=0.2
    )

    try:
        llm = LLM(llm_cfg)
    except ImportError as e:
        print(f"Error initializing LLM: {e}")
        print("Please ensure openai/anthropic packages are installed.")
        return

    print("=== Ultra-Maximal Dev Agent ===")

    # Check if we should use Multi-Agent Orchestrator
    # For now, default to Universal Single-Loop for simplicity unless configured
    mode = cfg.get("mode", "universal")

    if mode == "multi-agent":
        print("[Mode] Multi-Agent Orchestration")
        orch = Orchestrator(llm)
        await orch.build_system(request, system_prompt)
    else:
        print(f"[Mode] Universal ({mode})")
        interpreter = Interpreter(llm)
        interpreted = await interpreter.interpret(request, system_prompt)
        print(f"[Interpreter] Summary: {interpreted.summary}")

        executor = Executor(llm)
        exec_result = await executor.execute(interpreted, system_prompt)

        # Verification
        verifier = Verifier()
        ver_result = verifier.verify()

        # Documentation
        doc = Documenter()
        docs = doc.document()

        # DevOps
        devops = DevOps()
        devops.setup()

        # PR
        pr_manager = PRManager()
        pr_cfg = cfg.get("pr", {})
        pr_result = pr_manager.prepare_and_optionally_merge(
            title=f"Auto-Generated: {request[:60]}",
            body="Generated by the Ultra-Maximal Autonomous Agent.\nSee /output.",
            branch=pr_cfg.get("branch", "feat/auto"),
            auto_merge=pr_cfg.get("autoMerge", False)
        )

    print("=== COMPLETE ===")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python -m agent.main \"<request>\"")
        exit(1)

    asyncio.run(run(" ".join(sys.argv[1:])))
