
import http from 'k6/http';
import { check, sleep } from 'k6';
import { config, headers } from '../config.js';
import { Rate } from 'k6/metrics';

const errorRate = new Rate('errors_cases');

export default function () {
  const listRes = http.get(`${config.baseUrl}/api/cases?limit=10`, { headers });

  check(listRes, {
    'cases list status is 200': (r) => r.status === 200,
    'cases list has data': (r) => JSON.parse(r.body).length !== undefined,
  }) || errorRate.add(1);

  // Create a case
  const createPayload = JSON.stringify({
    title: `Load Test Case ${Date.now()}`,
    description: 'Generated by k6 load test',
    status: 'active', // Lowercase as per CaseStatus type
    compartment: 'PUBLIC',
    reason: 'Load testing',
    legalBasis: 'CONSENT'
  });

  const createRes = http.post(`${config.baseUrl}/api/cases`, createPayload, { headers });

  const created = check(createRes, {
    'create case status is 201': (r) => r.status === 201,
  });

  if (!created) {
    errorRate.add(1);
  } else {
    const caseId = JSON.parse(createRes.body).id;

    // Get the created case
    const getRes = http.get(`${config.baseUrl}/api/cases/${caseId}?reason=LoadTest&legalBasis=CONSENT`, { headers });
    check(getRes, {
      'get case status is 200': (r) => r.status === 200,
      'get case matches id': (r) => JSON.parse(r.body).id === caseId,
    }) || errorRate.add(1);
  }

  sleep(1);
}
