import fs from 'fs/promises';
import path from 'path';

async function generateIndex(outputDir: string, releaseTag: string) {
  const content = `# Summit Trust Portal - Release ${releaseTag}

**Date:** ${new Date().toISOString().split('T')[0]}

## Overview
This portal contains verifiable evidence and assurance artifacts for the release \`${releaseTag}\`.

## Artifacts

### 1. Release Notes
[View Release Notes](./releases/release-notes.md)

### 2. Software Bill of Materials (SBOM)
*   [Server SBOM](./sbom/server-sbom.json)
*   [Client SBOM](./sbom/client-sbom.json)

### 3. Provenance & Attestation
*   [SLSA Attestation](./provenance/slsa-attestation.json)
*   [Build Manifest](./provenance/build-manifest.json)

### 4. Verification
See [Verification Instructions](./verification_instructions.md) to validate these artifacts using our public keys.

---
*Generated by Summit Trust Portal Generator*
`;

  await fs.writeFile(path.join(outputDir, 'index.md'), content);
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.error('Usage: tsx generate_trust_portal.ts <redacted_artifacts_dir> <output_dir> [release_tag]');
    process.exit(1);
  }

  const artifactsDir = args[0];
  const outputDir = args[1];
  const releaseTag = args[2] || 'v0.0.0-dev';

  console.log(`Generating Trust Portal for ${releaseTag}...`);

  try {
    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });

    // Copy artifacts to structure
    // We assume artifactsDir has a structure like:
    // /sbom, /provenance, /releases
    // We will copy them into outputDir/

    // Use cp -r equivalent
    await fs.cp(artifactsDir, outputDir, { recursive: true });

    // Generate Index
    await generateIndex(outputDir, releaseTag);

    console.log(`Trust Portal generated at ${outputDir}`);
  } catch (error) {
    console.error('Error generating portal:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
