import fs from "fs";
import path from "path";

// This script aggregates the results and generates a Markdown report for the team.

const reportDate = new Date().toISOString().split("T")[0];
const metricsPath = path.resolve(process.cwd(), "current_metrics.json");
const suggestionsPath = path.resolve(process.cwd(), "optimization_suggestions.json");

// --- Load Data ---

let metrics = {};
let suggestions = [];

try {
  metrics = JSON.parse(fs.readFileSync(metricsPath, "utf8"));
} catch (e) {
  console.warn("Metrics file missing.");
}

try {
  suggestions = JSON.parse(fs.readFileSync(suggestionsPath, "utf8"));
} catch (e) {
  console.warn("Suggestions file missing.");
}

// --- Generate Markdown ---

const markdown = `# 📈 Continuous Optimization Report - ${reportDate}

**Status:** ${Object.keys(metrics).length > 0 ? "✅ Metrics Available" : "⚠️ No Metrics"}
**Generated By:** Summit Continuous Optimization Loop

## 1. Current State (vs Baselines)

| Metric | Value | Status |
|--------|-------|--------|
${Object.entries(metrics)
  .map(([k, v]) => `| \`${k}\` | **${v}** | ${getStatusEmoji(k, v)} |`)
  .join("\n")}

## 2. Active Suggestions

${
  suggestions.length > 0
    ? suggestions
        .map(
          (s) => `
### 💡 ${s.area}: ${s.action}
*   **Impact:** ${s.impact}
*   **Risk:** ${s.risk}
`
        )
        .join("\n")
    : "*No active suggestions.*"
}

## 3. Backlog Actions

*   [ ] Review critical suggestions.
*   [ ] Create Jira tickets for approved optimizations.
*   [ ] Run regression suite if applying changes.

---
*Run \`npm run optimize:check\` to refresh.*
`;

function getStatusEmoji(key, val) {
  // Simple heuristic mapping
  // In a real app, this would reuse the shared config logic
  return "📊";
}

// --- Save Report ---

const reportFile = `docs/reports/optimization_report_${reportDate}.md`;
// Ensure directory exists
const reportDir = path.dirname(reportFile);
if (!fs.existsSync(reportDir)) {
  fs.mkdirSync(reportDir, { recursive: true });
}

fs.writeFileSync(reportFile, markdown);
console.log(`Optimization Report generated at ${reportFile}`);
