import { test, describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import path from 'path';
import { generateMarkdown, validate } from '../verify_governance_docs.mjs';

describe('Governance Docs Verifier', () => {
  it('should validate a correct index object', () => {
    const index = {
      version: 2,
      title: 'Test Index',
      description: 'Test Description',
      sections: [
        {
          title: 'Core Gates',
          gates: [
            { name: 'Lint', status: 'Active' }
          ]
        }
      ]
    };
    const errors = validate(index);
    assert.deepEqual(errors, []);
  });

  it('should detect invalid version', () => {
    const index = { version: 1 };
    const errors = validate(index);
    assert.ok(errors.some(e => e.includes('version: 2')));
  });

  it('should generate markdown correctly', () => {
    const index = {
      version: 2,
      title: 'Test Index',
      description: 'Test Description',
      sections: [
        {
          title: 'Core Gates',
          gates: [
            { name: 'Lint', status: 'Active', owner: 'Infra', enforcement: 'Blocking' }
          ]
        }
      ]
    };
    const md = generateMarkdown(index);
    assert.ok(md.includes('# Test Index'));
    assert.ok(md.includes('## Core Gates'));
    assert.ok(md.includes('| **Lint** | Active | Infra | Blocking |'));
    assert.ok(md.includes('Generated by scripts/ci/verify_governance_docs.mjs'));
  });

  it('should handle empty sections gracefully', () => {
     const index = {
      version: 2,
      title: 'Empty Index',
      description: 'Desc',
      sections: []
    };
    const md = generateMarkdown(index);
    assert.ok(md.includes('*No sections defined.*'));
  });

  it('should validate active gates against available jobs', () => {
    const index = {
      version: 2,
      title: 'Test Index',
      sections: [
        {
          title: 'Core Gates',
          gates: [
            { name: 'Real Job', status: 'Active' },
            { name: 'Fake Job', status: 'Active' },
            { name: 'Inactive Job', status: 'Inactive' }
          ]
        }
      ]
    };
    const availableGates = ['Real Job'];
    const errors = validate(index, availableGates);

    assert.ok(errors.some(e => e.includes("Active gate 'Fake Job' not found")));
    assert.ok(!errors.some(e => e.includes("Real Job")));
    assert.ok(!errors.some(e => e.includes("Inactive Job"))); // Should not validate inactive gates
  });
});
