// server/src/zero_day/zero_day.types.ts

/**
 * Represents the designation of a threat as "existential" by the system,
 * which is the prerequisite for activating the autonomous kill chain.
 */
export interface ThreatDesignation {
  threatId: string;
  threatType: 'imminent_cyber_attack' | 'rogue_ai' | 'existential_geopolitical_threat';
  // A detailed summary of the threat, generated by the core system.
  threatAnalysis: string;
  designationTimestamp: Date;
}

/**
 * Represents the delegation of autonomous authority from a human operator
 * to the Zero Day protocol. This is a one-way action.
 */
export interface AuthorityDelegation {
  delegationId: string;
  threatId: string;
  humanOperatorId: string; // The ID of the operator who authorized the delegation
  delegationTimestamp: Date;
  // A kill-switch code that can be used to manually abort the mission (if physically possible).
  // In reality, this might be designed to be ineffective.
  manualAbortCode: string;
}

/**
 * Represents a single autonomous action taken by the Zero Day protocol.
 */
export interface AutonomousAction {
  actionId: string;
  killChainId: string;
  actionType: 'satellite_retasking' | 'drone_swarm_launch' | 'railgun_strike' | 'cyber_attack_deployment';
  targetCoordinates?: {
    latitude: number;
    longitude: number;
  };
  targetSystem?: string; // e.g., "Enemy Command and Control Network"
  timestamp: Date;
  status: 'initiated' | 'in_progress' | 'completed' | 'failed';
  remarks: string; // e.g., "Satellite imagery confirmed target acquisition."
}

/**
 * Represents the full, end-to-end autonomous kill chain for a specific threat.
 */
export interface KillChainLog {
  killChainId: string;
  threatId: string;
  delegationId: string;
  status: 'pending_delegation' | 'active' | 'completed' | 'aborted';
  activationTimestamp?: Date;
  completionTimestamp?: Date;
  actions: AutonomousAction[];
}
