#!/bin/bash
# Batch closed PR recovery script

set -e

BATCH_START=$1
BATCH_SIZE=$2
MODE="${RECOVERY_MODE:-aggressive}"

echo "=== BATCH RECOVERY: Start=$BATCH_START, Size=$BATCH_SIZE, Mode=$MODE ==="

# Get closed unmerged PRs
gh pr list --state closed --limit 1000 --json number,title,closedAt,mergedAt,headRefName,additions,deletions,author \
  --jq '.[] | select(.mergedAt == null) | {
    number,
    title,
    branch: .headRefName,
    size: (.additions + .deletions),
    author: .author.login
  }' | \
  jq -s "sort_by(.size) | .[${BATCH_START}:${BATCH_START}+${BATCH_SIZE}]" > /tmp/recovery_batch.json

total=$(jq 'length' /tmp/recovery_batch.json)
echo "Processing $total PRs in this batch"

recovered=0
failed=0

jq -c '.[]' /tmp/recovery_batch.json | while read -r pr_data; do
  pr_num=$(echo "$pr_data" | jq -r '.number')
  branch_name=$(echo "$pr_data" | jq -r '.branch')
  pr_title=$(echo "$pr_data" | jq -r '.title')
  pr_author=$(echo "$pr_data" | jq -r '.author')

  echo "Processing PR #$pr_num ($branch_name)..."

  # Check if branch exists
  if ! git ls-remote --heads origin "$branch_name" | grep -q "$branch_name"; then
    echo "⚠️ Branch $branch_name no longer exists, skipping"
    failed=$((failed + 1))
    continue
  fi

  # Check if revival already exists
  if gh pr list --head "revival/${pr_num}" --json number --jq length | grep -q "1"; then
    echo "ℹ️ Revival already exists for #$pr_num, skipping"
    continue
  fi

  # Fetch branch
  git fetch origin "$branch_name" 2>/dev/null || {
    echo "⚠️ Failed to fetch $branch_name"
    failed=$((failed + 1))
    continue
  }

  # Create revival branch
  revival_branch="revival/${pr_num}"
  git checkout main 2>/dev/null || true
  git pull origin main 2>/dev/null || true
  git checkout -b "$revival_branch" 2>/dev/null || {
    git checkout "$revival_branch" 2>/dev/null || continue
  }

  # Try merge
  if git merge --no-commit --no-ff "origin/$branch_name" 2>&1; then
    # Merge succeeded
    git commit -m "Recovery: PR #$pr_num - $pr_title

Original PR: #$pr_num
Original author: @$pr_author
Recovery mode: $MODE

🤖 Auto-recovered by Mega Excavator" 2>/dev/null || true

    # Push and create PR
    if git push origin "$revival_branch" 2>&1; then
      gh pr create \
        --base main \
        --head "$revival_branch" \
        --title "🏗️ Recovery: $pr_title" \
        --body "## Automated PR Recovery

**Original PR:** #$pr_num
**Original Author:** @$pr_author
**Recovery Mode:** $MODE

This PR recovers work from closed PR #$pr_num.

---
🤖 Auto-generated by Mega Excavator" 2>/dev/null && {
        echo "✅ Recovered PR #$pr_num"
        recovered=$((recovered + 1))
      }
    fi
  else
    # Merge failed, try cherry-pick
    git merge --abort 2>/dev/null || true

    commits=$(git log --reverse --pretty=format:"%H" "origin/$branch_name" ^main 2>/dev/null | head -20)

    if [ -n "$commits" ]; then
      echo "$commits" | while read commit; do
        git cherry-pick "$commit" 2>/dev/null || \
          git cherry-pick --strategy=recursive -X theirs "$commit" 2>/dev/null || \
          git cherry-pick --abort 2>/dev/null
      done

      git push origin "$revival_branch" 2>/dev/null && \
        gh pr create \
          --base main \
          --head "$revival_branch" \
          --title "🏗️ Recovery (partial): $pr_title" \
          --body "Recovered from PR #$pr_num via cherry-pick" 2>/dev/null && {
          recovered=$((recovered + 1))
        }
    fi
  fi

  git checkout main 2>/dev/null || true
  sleep 2
done

echo "Batch complete: $recovered recovered, $failed failed"
