// ESLint v9 flat-config root
// Root config remains dependency-light so lint can run in constrained CI/dev shells.

const IGNORE = [
  // Flat-config replacement for legacy .eslintignore entries.
  '_worktrees/**',
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/.vite/**',
  '**/.next/**',
  '**/.cache/**',
  '**/.turbo/**',
  '**/generated/**',
  'frontend/.vite/**',
  '**/public/**',
  '**/*.min.js',
  '.github/workflows/compliance-automation.yml',
  'v4/archive/**',
  '.venv/**',
  'venv/**',
  '**/v24_modules/**',
  '.archive/**',
  '_salvage_from_refs/**',
  'templates/**',
  '.ci/**',
  '.disabled/**',
  '.github/**',
  'scripts/**',
  'tools/**',
  'benchmarks/**',
  'examples/**',
  'zero-trust/**',
  'ga-graphai/**',
  'conductor-ui/**',
  'e2e/**',
  'mobile/**',
  'activities/**',
  '__mocks__/**',
  'bindings/**',
  'operator-kit/**',
  'platform/**',
  'companyos/**',
  'cli/**',
  'gateway/**',
  'adversarial-misinfo-defense-platform/**',
  'active-measures-module/**',
  'absorption/**',
  'assistant/**',
  '.maestro/**',
  '.security/**',
  'website/**',
  'workers/**',
  'sdk/**',
  'libs/**',
  'docs/**',
  'intelgraph/**',
  'intelgraph-mcp/**',
  'agents/**',
  'graphql/**',
  'agentic/**',
  'backend/**',
  'api/**',
  'bootstrap/**',
  'adapters/**',
  'tests/**',
  'src/**',
  'ui/**',
  'web/**',
  'webapp/**',
  'k6/**',
  'deepagent-mvp/**',
  'sim-harness/**',
  'prov-ledger-service/**',
  'ops/**',
  'test/**',
  'october2025/**',
  'summit-intel-evo/**',
  'safety-harness/**',
  'infra/**',
  'connectors/**',
  'intelgraph-quickstart/**',
  'integrations/**',
  'extensions/**',
  'apps/**',
  'client/**',
  'packages/**',
  '!packages/agent-skillpacks/**',
  'services/**',
  'server/**',
  'streaming/**',
  'sprint-kits/**',
  'synthetics/**',
  'tooling/**',
  'docs-site/**',
  'intelgraph_enhancements/**',
  'Developer/**',
  'SECURITY/**',
  '__tests__/**',
  'ai/**',
  'bin/**',
  'bundle-server/**',
  'privacy/**',
  'prompts/**',
  'relevance/**',
  'reliability/**',
  'reo/**',
  'search/**',
  'frontend/**',
  'llm-serving/**',
  'mnemosyne/**',
  'monitoring/**',
  'nlp/**',
  'observability/**',
  'orchestration/**',
  'provisioning/**',
  'relay/**',
  'reporting/**',
  'replication/**',
  'scheduling/**',
  'security/**',
  'shared/**',
  'simulations/**',
  'sso/**',
  'storage/**',
  'temporal/**',
  'telemetry/**',
  'training/**',
  'translations/**',
  'trust/**',
  'types/**',
  'utils/**',
  'validation/**',
  'vectordb/**',
  'workflows/**',
  'finops/cost-events/index.js',
  'jscpd-report/html/js/prism.js',
  '*.js',
  '*.cjs',
  '*.mjs',
  '*.ts',
];

export default [
  { ignores: IGNORE },
  {
    files: ['**/*.{js,cjs,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      'no-console': 'warn',
      'no-debugger': 'warn',
      'no-alert': 'warn',
      'no-var': 'warn',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'always', { null: 'ignore' }],
      curly: ['warn', 'all'],
    },
  },
];
