import js from '@eslint/js';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import { fixupPluginRules } from '@eslint/compat';
import tseslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import-x';
import jestPlugin from 'eslint-plugin-jest';

export default tseslint.config(
  { ignores: [
    'dist', 'build', 'coverage', 'node_modules', '*.min.js',
    '.worktrees/**',
    '.archive/**', '_salvage_from_refs/**', 'templates/**', '.ci/**', '.disabled/**', '.github/**',
    'scripts/**', 'tools/**', 'benchmarks/**', 'examples/**', 'zero-trust/**',
    'ga-graphai/**', 'conductor-ui/**', 'e2e/**', 'mobile/**', 'activities/**',
    '__mocks__/**', 'bindings/**', 'operator-kit/**', 'platform/**', 'companyos/**',
    'cli/**', 'gateway/**', 'adversarial-misinfo-defense-platform/**', 'active-measures-module/**',
    'absorption/**', 'assistant/**', '.maestro/**', '.security/**',
    'website/**', 'workers/**', 'sdk/**', 'libs/**', 'docs/**', 'intelgraph/**',
    'intelgraph-mcp/**', 'agents/**', 'graphql/**', 'agentic/**', 'backend/**',
    'api/**', 'bootstrap/**', 'adapters/**', 'tests/**', 'src/**',
    'ui/**', 'web/**', 'webapp/**', 'k6/**', 'deepagent-mvp/**', 'sim-harness/**',
    'prov-ledger-service/**', 'ops/**', 'test/**', 'october2025/**', 'summit-intel-evo/**',
    'safety-harness/**', 'infra/**', 'connectors/**', 'intelgraph-quickstart/**',
    'integrations/**', 'extensions/**',
    'apps/**', 'client/**', 'packages/**', 'services/**', 'server/**',
    'streaming/**', 'sprint-kits/**', 'synthetics/**', 'tooling/**',
    // Additional directories with parsing/linting issues
    'docs-site/**', 'intelgraph_enhancements/**', 'Developer/**', 'SECURITY/**',
    '__tests__/**', 'ai/**', 'bin/**', 'bundle-server/**', 'privacy/**', 'prompts/**',
    'relevance/**', 'reliability/**', 'reo/**', 'search/**', 'frontend/**',
    'llm-serving/**', 'mnemosyne/**', 'monitoring/**', 'nlp/**', 'observability/**',
    'orchestration/**', 'provisioning/**', 'relay/**', 'reporting/**', 'replication/**',
    'scheduling/**', 'security/**', 'shared/**', 'simulations/**', 'sso/**', 'storage/**',
    'temporal/**', 'telemetry/**', 'training/**', 'translations/**', 'trust/**', 'types/**',
    'utils/**', 'validation/**', 'vectordb/**', 'workflows/**',
    // Specific compiled/autogenerated files that should be ignored
    'finops/cost-events/index.js',
    'jscpd-report/html/js/prism.js',
    // Root-level JS/TS files that are standalone scripts
    '*.js', '*.cjs', '*.mjs', '*.ts'
  ] },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
    ],
    files: ['**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
      },
    },
    plugins: {
      'react': react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'import': importPlugin,
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import/resolver': {
        typescript: { project: ['./tsconfig.json', './client/tsconfig.json'] },
      },
    },
    rules: {
      'import/order': [
        'error',
        { 'newlines-between': 'always', alphabetize: { order: 'asc' } },
      ],
      'react/prop-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn', // Changed from 'off' to 'warn'
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-expressions': ['warn', { allowShortCircuit: true, allowTernary: true }],
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-namespace': 'warn',
      '@typescript-eslint/no-this-alias': 'warn',
      '@typescript-eslint/triple-slash-reference': 'warn',
      'no-useless-escape': 'warn',
      'no-case-declarations': 'warn',
      'no-empty': 'warn',
      'no-useless-catch': 'warn',
      'no-prototype-builtins': 'warn',
      'no-fallthrough': 'warn',
      'no-control-regex': 'warn',
      'no-constant-binary-expression': 'warn',
      'no-dupe-keys': 'warn',
      'no-shadow-restricted-names': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-duplicate-case': 'warn',
      'no-async-promise-executor': 'warn',
      'no-cond-assign': 'warn',
      'no-unreachable': 'warn',
      'no-unexpected-multiline': 'warn',
      'no-sparse-arrays': 'warn',
      'no-empty-pattern': 'warn',
      'prefer-spread': 'warn',
      'no-redeclare': 'warn',
      'no-dupe-class-members': 'warn',
      'import/first': 'warn',
      'react/no-array-index-key': 'warn',
      'no-console': 'warn', // Warn about console statements
    },
  },
  {
    files: ['**/__tests__/**/*.*', '**/*.test.*', 'tests/**/*.*', 'server/src/tests/**/*.*'],
    languageOptions: { globals: { ...globals.jest } },
    plugins: { jest: jestPlugin },
    extends: [jestPlugin.configs['recommended']],
    rules: {
      'jest/no-focused-tests': 'error',
      'jest/no-disabled-tests': 'warn',
      'no-restricted-properties': [
        'error',
        {
          object: 'console',
          property: 'error',
          message:
            'Use assertions or throw errors instead of console.error in tests',
        },
      ],
    },
  },
  {
    files: ['ui/components/Switchboard.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'JSXText[value=/\\S/]',
          message: 'Use t() for user-facing text in Switchboard (i18n).',
        },
        {
          selector:
            'JSXAttribute Literal[value=/\\S/]:matches([parent.name.name="placeholder"], [parent.name.name="title"], [parent.name.name="aria-label"], [parent.name.name="ariaLabel"])',
          message: 'Use t() for user-facing attribute strings in Switchboard (i18n).',
        },
      ],
    },
  }
);
