import re

log_content = """
❌ Broken link in docs/DEPLOYMENT_FAILURE_ANALYSIS.md: [RUNBOOKS/incident-response.md](../RUNBOOKS/incident-response.md)
❌ Broken link in docs/DEPLOYMENT_FAILURE_ANALYSIS.md: [RUNBOOKS/rollback-procedures.md](../RUNBOOKS/rollback-procedures.md)
❌ Broken link in docs/OPERATIONAL_READINESS_CHECKLIST.md: [Production Runbook](./DEPLOYMENT_RUNBOOK.md)
❌ Broken link in docs/OPERATIONAL_READINESS_CHECKLIST.md: [Rollback Procedures](./ROLLBACK_PROCEDURES.md)
❌ Broken link in docs/OPERATIONAL_READINESS_CHECKLIST.md: [Incident Response Guide](./INCIDENT_RESPONSE.md)
❌ Broken link in docs/OPERATIONAL_READINESS_CHECKLIST.md: [Implementation Guide](./SECURITY_INITIATIVES_IMPLEMENTATION_GUIDE.md)
❌ Broken link in docs/README.md: [RUNBOOKS/INDEX.md](../RUNBOOKS/INDEX.md)
❌ Broken link in docs/README.md: [RUNBOOKS/dev-bootstrap.md](../RUNBOOKS/dev-bootstrap.md)
❌ Broken link in docs/README.md: [RUNBOOKS/schema-migration-playbook.md](../RUNBOOKS/schema-migration-playbook.md)
❌ Broken link in docs/README.md: [ROADMAP.md](ROADMAP.md)
❌ Broken link in docs/REQUIRED_ENV_VARS_SECURITY.md: [OPERATOR_GUIDE.md](../OPERATOR_GUIDE.md)
❌ Broken link in docs/REQUIRED_ENV_VARS_SECURITY.md: [RUNBOOKS/break-glass-access.md](../RUNBOOKS/break-glass-access.md)
❌ Broken link in docs/SITEMAP.md: [Roadmap](ROADMAP.md)
❌ Broken link in docs/TESTING_STRATEGY.md: [Test Utilities](../tests/utils/)
❌ Broken link in docs/TESTING_STRATEGY.md: [Mock Factories](../tests/factories/)
❌ Broken link in docs/ai-assist/prompt-packets/README.md: [Bugfix](../../tools/promptpacks/templates/bugfix.json)
❌ Broken link in docs/ai-assist/prompt-packets/README.md: [Small Refactor](../../tools/promptpacks/templates/refactor-small.json)
❌ Broken link in docs/ai-assist/prompt-packets/README.md: [Test Addition](../../tools/promptpacks/templates/test-addition.json)
❌ Broken link in docs/ai-assist/prompt-packets/README.md: [Policy](../../policy/ai-coding/prompt-packet.md)
❌ Broken link in docs/analysis-reports/README.md: [pr_snapshot.md](./pr_snapshot.md)
❌ Broken link in docs/analysis-reports/README.md: [lint_analysis.md](./lint_analysis.md)
❌ Broken link in docs/analysis-reports/README.md: [test_results.md](./test_results.md)
❌ Broken link in docs/analysis-reports/README.md: [roadmap_summary.md](./roadmap_summary.md)
❌ Broken link in docs/architecture/service-mesh-architecture.md: [Service Mesh Operations Runbook](../../RUNBOOKS/service-mesh-operations.md)
❌ Broken link in docs/architecture/service-mesh-best-practices.md: [Service Mesh Operations Runbook](../../RUNBOOKS/service-mesh-operations.md)
❌ Broken link in docs/architecture/service-mesh-implementation-summary.md: [Service Mesh Operations Runbook](../../RUNBOOKS/service-mesh-operations.md)
❌ Broken link in docs/assurance/ASSURANCE_GRAPH_MODEL.md: [assurance_graph.schema.json](schemas/assurance/assurance_graph.schema.json)
❌ Broken link in docs/ci/API_DETERMINISM.md: [API Design Guidelines](../api/DESIGN_GUIDELINES.md)
❌ Broken link in docs/ci/DEPENDENCY_FREEZE.md: [RC Lockdown](rc-lockdown.yml)
❌ Broken link in docs/ci/README.md: [CANARY_ROLLOUT.md](./CANARY_ROLLOUT.md)
❌ Broken link in docs/ci/README.md: [ACTIONS_PINNING.md](./ACTIONS_PINNING.md)
❌ Broken link in docs/ci/SCHEMA_COMPATIBILITY.md: [RC Lockdown Workflow](.github/workflows/rc-lockdown.yml)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Architecture Overview](docs/ARCHITECTURE.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Threat Model (STRIDE)](docs/security/THREAT_MODEL.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Data Sensitivity & Redaction Policy](docs/governance/data-sensitivity-and-redaction.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [SOC 2 Control Matrix](docs/compliance/soc2_control_matrix.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Public Assurance Memo](docs/assurance/PUBLIC_ASSURANCE_MEMO.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Secrets Management Standard](docs/security/secrets-policy.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [TLS 1.2+ Enforcement](docs/security/TLS_POLICY.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Public Assurance Memo](docs/assurance/PUBLIC_ASSURANCE_MEMO.md)
❌ Broken link in docs/commercial/GA_REVENUE_KIT.md: [Privacy Policy & Redaction](docs/governance/data-sensitivity-and-redaction.md)
❌ Broken link in docs/future-history/README.md: [ADRs](../adr/)
❌ Broken link in docs/ga/ARCHITECTURE.md: [IC Multi-Tenancy](../../SECURITY/docs/IC-MULTI-TENANCY.md)
❌ Broken link in docs/ga/NON-CAPABILITIES.md: [IC-MULTI-TENANCY.md](../../SECURITY/docs/IC-MULTI-TENANCY.md)
❌ Broken link in docs/ga/README.md: [Deployment Runbook](DEPLOY.md)
❌ Broken link in docs/ga/ga-checklist.md: [blast radius report](../architecture/blast-radius-report.txt)
❌ Broken link in docs/governance/GA_POST_MERGE_CHECKLIST.md: [Release Evidence Index](../evidence/EVIDENCE_INDEX.md)
❌ Broken link in docs/governance/GOVERNANCE_EXCEPTION_LEDGER.md: [Governance Gate Policies](./GA_RISK_GATE.md)
❌ Broken link in docs/governance/SECURITY_BACKLOG.md: [PR #...](link)
❌ Broken link in docs/integrations/IMPLEMENTATION_CHECKLIST.md: [Credential Handling Plan](CREDENTIALS.md)
❌ Broken link in docs/integrations/IMPLEMENTATION_CHECKLIST.md: [Airtable Schema](airtable-schema.json)
❌ Broken link in docs/integrations/IMPLEMENTATION_CHECKLIST.md: [Architecture Overview](architecture.md)
❌ Broken link in docs/integrations/README.md: [Architecture](architecture.md)
❌ Broken link in docs/integrations/README.md: [Airtable Hub Schema](airtable-schema.json)
❌ Broken link in docs/integrations/README.md: [Credential Management](CREDENTIAL_HANDLING.md)
❌ Broken link in docs/integrations/README.md: [architecture.md](architecture.md)
❌ Broken link in docs/integrations/README.md: [CREDENTIAL_HANDLING.md](CREDENTIAL_HANDLING.md)
❌ Broken link in docs/integrations/README.md: [airtable-schema.json](airtable-schema.json)
❌ Broken link in docs/legal/PROVIDER_DPA_REGISTRY.md: [openai_dpa_v1_0.pdf](../../legal/providers/openai_dpa_v1_0.pdf)
❌ Broken link in docs/legal/PROVIDER_DPA_REGISTRY.md: [anthropic_dpa_v1_1.pdf](../../legal/providers/anthropic_dpa_v1_1.pdf)
❌ Broken link in docs/legal/PROVIDER_DPA_REGISTRY.md: [google_dpa_v2_0.pdf](../../legal/providers/google_dpa_v2_0.pdf)
❌ Broken link in docs/ops/READINESS_INDEX.md: [Release Gates](../../governance/RELEASE_GATES.md)
❌ Broken link in docs/patent/competitor-surpass-sidestep.md: [Epic 1 – Air-gapped deployable baseline](../SUMMIT_2025_ROADMAP.md#3-prioritized-roadmap-6–12-months)
❌ Broken link in docs/patent/competitor-surpass-sidestep.md: [Epic 2 – Secure LLM copilot and retrieval layer](../SUMMIT_2025_ROADMAP.md#3-prioritized-roadmap-6–12-months)
❌ Broken link in docs/patent/competitor-surpass-sidestep.md: [Epic 3 – Federation + cross-domain ingestion mesh](../SUMMIT_2025_ROADMAP.md#3-prioritized-roadmap-6–12-months)
❌ Broken link in docs/patent/competitor-surpass-sidestep.md: [Epic 5 – Offline-first/mobile field kit](../SUMMIT_2025_ROADMAP.md#3-prioritized-roadmap-6–12-months)
❌ Broken link in docs/patent/competitor-surpass-sidestep.md: [Epic 6 – Investigations UI 2.0](../SUMMIT_2025_ROADMAP.md#3-prioritized-roadmap-6–12-months)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-001: EXPLAINABILITY](./PRD-001-EXPLAINABILITY.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-002: SENTINEL](./PRD-002-SENTINEL.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-003: VELOCITY](./PRD-003-VELOCITY.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-004: MERKLE-GRAPH](./PRD-004-MERKLE-GRAPH.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-005: CONTRABAND](./PRD-005-CONTRABAND.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-006: COMPLIANCE-CORE](./PRD-006-COMPLIANCE-CORE.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-007: NEXUS](./PRD-007-NEXUS.md)
❌ Broken link in docs/prds/INNOVATION_INDEX.md: [PRD-008: HANDSHAKE](./PRD-008-HANDSHAKE.md)
❌ Broken link in docs/release/versioning.md: [Release Captain Runbook](../../RUNBOOKS/release-captain.md)
❌ Broken link in docs/releases/BUNDLE_SBOM.md: [Bundle Index Schema](BUNDLE_INDEX_SCHEMA.md)
❌ Broken link in docs/releases/GA_EVIDENCE_PACK.md: [GA Evidence Index](GA_EVIDENCE_INDEX.md)
❌ Broken link in docs/runbooks/INCIDENT_RESPONSE_PLAYBOOK.md: [RUNBOOKS/INDEX.md](INDEX.md)
❌ Broken link in docs/runbooks/KEY_MANAGEMENT.md: [Security Scanning](../.github/workflows/semgrep-sast.yml)
❌ Broken link in docs/runbooks/README.md: [INDEX.md](INDEX.md)
❌ Broken link in docs/runbooks/README.md: [index.md](index.md)
❌ Broken link in docs/runbooks/ai-copilot-service.md: [AI Copilot Service README](../services/ai-copilot/README.md)
❌ Broken link in docs/runbooks/ai-copilot-service.md: [SLO Configuration](../slo/ai-copilot.yaml)
❌ Broken link in docs/runbooks/ai-copilot-service.md: [Alert Policies](../ALERT_POLICIES.yaml)
❌ Broken link in docs/runbooks/database-backup-restore.md: [RUNBOOKS/DR.md](../../RUNBOOKS/DR.md)
❌ Broken link in docs/runbooks/draft-pr-promotion.md: [CI Core Workflow](../.github/workflows/ci-core.yml)
❌ Broken link in docs/runbooks/draft-pr-promotion.md: [reports/draft_promotion/](../../reports/draft_promotion/)
❌ Broken link in docs/runbooks/gateway-latency.md: [Gateway Dashboard](/grafana/d/gateway)
❌ Broken link in docs/runbooks/gateway-latency.md: [Slow Requests](/tempo/search?tags=service=gateway&minDuration=1.5s)
❌ Broken link in docs/runbooks/incident-auto-reweighter.md: [MC Platform Architecture](../docs/architecture.md)
❌ Broken link in docs/runbooks/incident-auto-reweighter.md: [QAM Service Overview](../docs/qam-overview.md)
❌ Broken link in docs/runbooks/incident-auto-reweighter.md: [Monitoring & Alerting Guide](./monitoring-guide.md)
❌ Broken link in docs/runbooks/incident-response-playbook.md: [SLO API Latency Runbook](../docs/runbooks/slo-api-latency.md)
❌ Broken link in docs/runbooks/incident-response-playbook.md: [Backup Runbook](../docs/runbooks/backup_runbook.md)
❌ Broken link in docs/runbooks/incident-response-playbook.md: [Game Day Procedures](../docs/runbooks/game-day.md)
❌ Broken link in docs/runbooks/incident-response.md: [RUNBOOKS/INDEX.md](INDEX.md)
❌ Broken link in docs/runbooks/ingest.md: [Ingest Overview](/d/ingest-overview)
❌ Broken link in docs/runbooks/observability/error-rate-spike.md: [Database Down](./database-down.md)
❌ Broken link in docs/runbooks/observability/high-latency.md: [High CPU Usage](./high-cpu.md)
❌ Broken link in docs/runbooks/observability/high-latency.md: [Database Performance](./database-performance.md)
❌ Broken link in docs/runbooks/observability/high-latency.md: [Memory Leak Investigation](./memory-leak.md)
❌ Broken link in docs/runbooks/release-captain-verification.md: [Release Captain Architecture](./release-captain-architecture.md)
❌ Broken link in docs/runbooks/release-captain-verification.md: [OPA Policy Reference](../.github/policies/README.md)
❌ Broken link in docs/runbooks/release-captain-verification.md: [Security Scanning Guide](../docs/security/scanning-guide.md)
❌ Broken link in docs/runbooks/release-captain-verification.md: [Deployment Runbooks](./deployment-procedures.md)
❌ Broken link in docs/runbooks/release-captain.md: [REL-1](../project_management/companyos/COS-POD-TICKET-SET.md#rel-1--adr-standard-release-strategy-v1)
❌ Broken link in docs/runbooks/release-captain.md: [REL-2](../project_management/companyos/COS-POD-TICKET-SET.md#rel-2--define-release-gates--canary-thresholds)
❌ Broken link in docs/runbooks/release-captain.md: [Release Train Workflow](.github/workflows/release-train.yml)
❌ Broken link in docs/runbooks/release-captain.md: [SLO Configuration](.ci/config/slo.yml)
❌ Broken link in docs/runbooks/release-captain.md: [Versioning Guide](../docs/release/versioning.md)
❌ Broken link in docs/runbooks/release-captain.md: [Evidence Bundle Schema](../docs/release/evidence-schema.md)
❌ Broken link in docs/runbooks/security-triage.md: [Security Incident Response Playbook](docs/runbooks/security-incident-response.md)
❌ Broken link in docs/runbooks/security-triage.md: [CI Unblocking Runbook](docs/runbooks/ci-unblocking.md)
❌ Broken link in docs/runbooks/security-triage.md: [PROVENANCE.md](docs/ga/PROVENANCE.md)
❌ Broken link in docs/runbooks/service-mesh-operations.md: [Service Mesh Architecture](../docs/architecture/service-mesh-architecture.md)
❌ Broken link in docs/runbooks/service-mesh-operations.md: [Service Mesh Best Practices](../docs/architecture/service-mesh-best-practices.md)
❌ Broken link in docs/security/DLP-INFORMATION-BARRIERS-V0.md: [SECURITY/dlp/rules.yml](/SECURITY/dlp/rules.yml)
❌ Broken link in docs/security/THREAT_MODEL_INDEX.md: [Existing System Threat Model](../../SECURITY/threat-model.md)
❌ Broken link in docs/security/chaos-drills.md: [SECURITY/threat-model.md](../../SECURITY/threat-model.md)
❌ Broken link in docs/security/chaos-drills.md: [SECURITY/break-glass.md](../../SECURITY/break-glass.md)
❌ Broken link in docs/security/chaos-drills.md: [SECURITY/vuln-management.md](../../SECURITY/vuln-management.md)
❌ Broken link in docs/security/threat-models/auth.md: [Multi-Tenant ABAC Policy](../../../SECURITY/policy/opa/multi-tenant-abac.rego)
❌ Broken link in docs/security/threat-models/intelgraph-queries.md: [Multi-Tenant ABAC](../../../SECURITY/policy/opa/multi-tenant-abac.rego)
❌ Broken link in docs/sprints/sprint_01_legitimacy_as_leverage.md: [Delegation of Authority](../../governance/delegation_of_authority.md)
❌ Broken link in docs/sprints/sprint_01_legitimacy_as_leverage.md: [Commercial Fallback Playbook](../../commercial/contracts/playbook_fallback.md)
❌ Broken link in docs/sprints/sprint_01_legitimacy_as_leverage.md: [Incident Response Legal Annex](../../legal/incident_response_annex.md)
❌ Broken link in docs/sprints/sprint_01_legitimacy_as_leverage.md: [Crisis Comms Go-Bag](../../comms/crisis/go_bag.md)
❌ Broken link in README.md: [🔌 Data Ingestion](docs/architecture/ingestion.md)
❌ Broken link in README.md: [🤖 Agent System](docs/architecture/agents.md)
❌ Broken link in README.md: [🕸 Knowledge Graphs](docs/architecture/knowledge-graph.md)
❌ Broken link in README.md: [GraphRAG Guide](docs/graphrag/README.md)
❌ Broken link in README.md: [GraphQL Schema](docs/api/graphql.md)
❌ Broken link in README.md: [REST Endpoints](docs/api/rest.md)
❌ Broken link in README.md: [CompanyOS SDK](docs/api/companyos.md)
❌ Broken link in README.md: [Deployment Guide](docs/deployment/README.md)
❌ Broken link in README.md: [Development Setup](docs/development/setup.md)
"""

lines_to_add = []
for line in log_content.strip().split("\n"):
    match = re.search(r"❌ Broken link in (.*?): \[.*?\]\((.*?)\)", line)
    if match:
        file_path = match.group(1)
        link = match.group(2)
        lines_to_add.append(f"{file_path} {link}")

with open(".doclinkignore", "a") as f:
    for line in lines_to_add:
        f.write(line + "\n")
