module.exports = {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts', '.tsx', '.mts'],
  transform: {
    '^.+\\.[cm]?[tj]sx?$': [
      require.resolve('ts-jest'),
      {
        useESM: true,
        tsconfig: 'tsconfig.test.json',
      },
    ],
  },
  roots: ['server', 'client', 'packages', 'services', 'tests', 'scripts', 'libs'],
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/archive/',
    '<rootDir>/salvage/',
    '<rootDir>/pull/',
    '<rootDir>/packages/cli/',
    '<rootDir>/packages/work-graph/packages/work-graph/',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/archive/',
    '/salvage/',
    '/pull/',
    '/tests/e2e/',
    '/client/tests/',
    '/services/sandbox-gateway/tests/',
  ],
  watchPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/archive/',
    '/salvage/',
    '/pull/',
  ],
  collectCoverageFrom: [
    '**/*.{ts,tsx,js,jsx}',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/*.config.{js,ts}',
    '!**/coverage/**',
    '!**/archive/**',
    '!**/salvage/**',
    '!**/pull/**',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './server/src/middleware/**/*.ts': {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
    './server/src/services/**/*.ts': {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
  },
  testMatch: [
    '**/__tests__/**/*.{ts,tsx,js,jsx}',
    '**/?(*.)+(spec|test).{ts,tsx,js,jsx}',
  ],
  moduleNameMapper: {
    '^node-fetch$': '<rootDir>/__mocks__/node-fetch.cjs',
    '^pg$': '<rootDir>/__mocks__/pg.js',
    '^ioredis$': '<rootDir>/__mocks__/ioredis.js',
    '^@opentelemetry/sdk-node$': '<rootDir>/__mocks__/otel-sdk-node.cjs',
    '^@opentelemetry/exporter-trace-otlp-http$': '<rootDir>/__mocks__/otel-exporter-trace-otlp-http.cjs',
    '^puppeteer$': '<rootDir>/__mocks__/puppeteer.cjs',
    '^@server/(.*)$': '<rootDir>/server/src/$1',
    '^@tests/(.*)$': '<rootDir>/tests/$1',
    '^@intelgraph/provenance$': '<rootDir>/packages/provenance/src/index.ts',
    '^@intelgraph/(.*)$': '<rootDir>/packages/$1/src/index.ts',
  },
  resolver: '<rootDir>/jest.resolver.cjs',
  transformIgnorePatterns: [
    'node_modules/(?!(uuid|node-fetch|data-uri-to-buffer|fetch-blob|formdata-polyfill|jose|.*\\.mjs$))',
    '<rootDir>/.disabled/',
    '<rootDir>/apps/.mobile-native-disabled/',
    '<rootDir>/apps/.desktop-electron-disabled/',
  ],
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons', 'default'],
  },
  setupFilesAfterEnv: ['<rootDir>/tests/utils/jest-setup.cjs'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
};
