/**
 * FactAPI Pro
 * White-label verification API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VerifyResponse model module.
 * @module model/VerifyResponse
 * @version 1.0.0
 */
class VerifyResponse {
    /**
     * Constructs a new <code>VerifyResponse</code>.
     * @alias module:model/VerifyResponse
     * @param verified {Boolean}
     * @param score {Number}
     * @param reasoning {String}
     */
    constructor(verified, score, reasoning) {

        VerifyResponse.initialize(this, verified, score, reasoning);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verified, score, reasoning) {
        obj['verified'] = verified;
        obj['score'] = score;
        obj['reasoning'] = reasoning;
    }

    /**
     * Constructs a <code>VerifyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerifyResponse} obj Optional instance to populate.
     * @return {module:model/VerifyResponse} The populated <code>VerifyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerifyResponse();

            if (data.hasOwnProperty('verified')) {
                obj['verified'] = ApiClient.convertToType(data['verified'], 'Boolean');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('reasoning')) {
                obj['reasoning'] = ApiClient.convertToType(data['reasoning'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VerifyResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VerifyResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VerifyResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['reasoning'] && !(typeof data['reasoning'] === 'string' || data['reasoning'] instanceof String)) {
            throw new Error("Expected the field `reasoning` to be a primitive type in the JSON string but got " + data['reasoning']);
        }
        // ensure the json data is a string
        if (data['timestamp'] && !(typeof data['timestamp'] === 'string' || data['timestamp'] instanceof String)) {
            throw new Error("Expected the field `timestamp` to be a primitive type in the JSON string but got " + data['timestamp']);
        }

        return true;
    }


}

VerifyResponse.RequiredProperties = ["verified", "score", "reasoning"];

/**
 * @member {Boolean} verified
 */
VerifyResponse.prototype['verified'] = undefined;

/**
 * @member {Number} score
 */
VerifyResponse.prototype['score'] = undefined;

/**
 * @member {String} reasoning
 */
VerifyResponse.prototype['reasoning'] = undefined;

/**
 * @member {String} timestamp
 */
VerifyResponse.prototype['timestamp'] = undefined;






export default VerifyResponse;
