#!/usr/bin/env bash
# build-promotion-bundle.sh v1.0.0
# Generates a Promotion Bundle for RC → GA promotion
#
# Usage: ./build-promotion-bundle.sh --tag v4.1.2-rc.1 --commit <sha>
# Output: artifacts/promotion-bundles/<tag>/

set -euo pipefail

# --- Configuration ---
SCRIPT_VERSION="1.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"

# --- Color output ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*" >&2; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

print_usage() {
    cat <<EOF
Usage: $0 --tag <tag> --commit <sha> [OPTIONS]

Generates a Promotion Bundle for RC → GA promotion.

OPTIONS:
    --tag TAG          RC tag name (e.g., v4.1.2-rc.1)
    --commit SHA       Commit SHA the tag points to
    --output DIR       Output directory (default: artifacts/promotion-bundles/<tag>)
    --help             Show this help message

OUTPUT:
    The bundle contains:
    - github_release.md      Release notes for GitHub Release
    - promote_to_ga.sh       Operator commands to promote RC to GA
    - REQUIRED_CHECKS.txt    Truth table snapshot from verify-green-for-tag
    - PROMOTION_CHECKLIST.md Step-by-step promotion guide

EXAMPLES:
    $0 --tag v4.1.2-rc.1 --commit a8b1963
    $0 --tag v4.1.2-rc.1 --commit a8b1963 --output ./my-bundle
EOF
}

# --- Validation ---
validate_rc_tag() {
    local tag="$1"
    if ! [[ "${tag}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
        log_error "Invalid RC tag format: ${tag}"
        log_error "Expected format: vX.Y.Z-rc.N (e.g., v4.1.2-rc.1)"
        exit 2
    fi
}

extract_version_from_rc() {
    local rc_tag="$1"
    echo "${rc_tag}" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+)-rc\.[0-9]+$/\1/'
}

extract_ga_tag_from_rc() {
    local rc_tag="$1"
    echo "${rc_tag}" | sed -E 's/^(v[0-9]+\.[0-9]+\.[0-9]+)-rc\.[0-9]+$/\1/'
}

# --- Bundle Generation ---
generate_github_release_md() {
    local tag="$1"
    local commit_sha="$2"
    local output_file="$3"
    local version
    version=$(extract_version_from_rc "${tag}")
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat > "${output_file}" <<EOF
# ${tag} - MVP-4 Stabilization Release Candidate

**Release Type**: Stabilization RC
**Version**: ${version}
**RC Tag**: \`${tag}\`
**Commit**: \`${commit_sha}\`
**Created**: ${timestamp}

---

## What's in this RC

This release candidate contains fixes and improvements for MVP-4 stabilization:

- See [CHANGELOG.md](CHANGELOG.md) for detailed changes
- See [MVP-4 Stabilization Release Notes](docs/releases/MVP-4_STABILIZATION_RELEASE_NOTES.md) for highlights

## Verification Status

This RC has been verified by the automated Promotion Guard:

- ✅ Release Readiness Gate
- ✅ GA Gate
- ✅ Unit Tests & Coverage
- ✅ CI Core (Primary Gate)
- ✅ All conditionally-required checks (for changed paths)

## Promotion to GA

To promote this RC to GA:

\`\`\`bash
# 1. Verify the RC is still green
./scripts/release/verify-green-for-tag.sh --tag ${tag} --commit ${commit_sha}

# 2. Create and push GA tag
git tag -a v${version} ${commit_sha} -m "MVP-4 Stabilization Release v${version}"
git push origin v${version}
\`\`\`

## Rollback

If issues are discovered:

\`\`\`bash
# Delete the RC tag
git tag -d ${tag}
git push origin :refs/tags/${tag}
\`\`\`

---

**Promotion Bundle**: This release notes file was auto-generated by the RC Pipeline.
**Commit**: ${commit_sha}
**Timestamp**: ${timestamp}
EOF
}

generate_promote_to_ga_script() {
    local rc_tag="$1"
    local commit_sha="$2"
    local output_file="$3"
    local ga_tag
    ga_tag=$(extract_ga_tag_from_rc "${rc_tag}")
    local version
    version=$(extract_version_from_rc "${rc_tag}")

    cat > "${output_file}" <<'SCRIPT_HEADER'
#!/usr/bin/env bash
# promote_to_ga.sh - Generated promotion script for RC → GA
# This script was auto-generated by build-promotion-bundle.sh
#
# Usage: ./promote_to_ga.sh [--dry-run]
#
# This script will:
# 1. Re-verify the RC commit is green
# 2. Create the GA tag
# 3. Push the GA tag
# 4. Print the gh release command

set -euo pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

SCRIPT_HEADER

    cat >> "${output_file}" <<EOF

# --- Configuration (auto-generated) ---
RC_TAG="${rc_tag}"
GA_TAG="${ga_tag}"
COMMIT_SHA="${commit_sha}"
VERSION="${version}"

EOF

    cat >> "${output_file}" <<'SCRIPT_BODY'
# --- Color output ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

echo "═══════════════════════════════════════════════════════════════"
echo "  RC → GA Promotion Script"
echo "═══════════════════════════════════════════════════════════════"
echo ""
log_info "RC Tag:     ${RC_TAG}"
log_info "GA Tag:     ${GA_TAG}"
log_info "Commit:     ${COMMIT_SHA}"
log_info "Version:    ${VERSION}"
log_info "Dry Run:    ${DRY_RUN}"
echo ""

# Step 1: Re-verify
log_info "Step 1: Re-verifying RC commit is green..."
if [[ "${DRY_RUN}" == "true" ]]; then
    log_warn "[DRY-RUN] Would run: ./scripts/release/verify-green-for-tag.sh --tag ${RC_TAG} --commit ${COMMIT_SHA}"
else
    if ! ./scripts/release/verify-green-for-tag.sh --tag "${RC_TAG}" --commit "${COMMIT_SHA}"; then
        log_error "Verification failed! Cannot promote to GA."
        exit 1
    fi
fi
log_success "Step 1: Complete"
echo ""

# Step 2: Create GA tag
log_info "Step 2: Creating GA tag..."
TAG_MESSAGE="MVP-4 Stabilization Release ${GA_TAG}

Promoted from: ${RC_TAG}
Commit: ${COMMIT_SHA}
Promoted at: $(date -u +%Y-%m-%dT%H:%M:%SZ)

This release has passed all required gates:
- Release Readiness Gate
- GA Gate
- Unit Tests & Coverage
- CI Core (Primary Gate)

Evidence: See promotion bundle artifact from RC pipeline.
"

if [[ "${DRY_RUN}" == "true" ]]; then
    log_warn "[DRY-RUN] Would create tag: git tag -a ${GA_TAG} ${COMMIT_SHA}"
    echo "${TAG_MESSAGE}"
else
    git tag -a "${GA_TAG}" "${COMMIT_SHA}" -m "${TAG_MESSAGE}"
    log_success "Created tag: ${GA_TAG}"
fi
log_success "Step 2: Complete"
echo ""

# Step 3: Push GA tag
log_info "Step 3: Pushing GA tag..."
if [[ "${DRY_RUN}" == "true" ]]; then
    log_warn "[DRY-RUN] Would push: git push origin ${GA_TAG}"
else
    git push origin "${GA_TAG}"
    log_success "Pushed tag: ${GA_TAG}"
fi
log_success "Step 3: Complete"
echo ""

# Step 4: Print release command
log_info "Step 4: GitHub Release command..."
RELEASE_CMD="gh release create ${GA_TAG} \\
  --title \"v${VERSION} - MVP-4 Stabilization\" \\
  --notes-file docs/releases/MVP-4_STABILIZATION_RELEASE_NOTES.md"

echo ""
echo "To create the GitHub Release, run:"
echo ""
echo "${RELEASE_CMD}"
echo ""

if [[ "${DRY_RUN}" == "true" ]]; then
    log_warn "[DRY-RUN] No changes made."
else
    log_success "═══════════════════════════════════════════════════════════════"
    log_success "  GA TAG CREATED: ${GA_TAG}"
    log_success "═══════════════════════════════════════════════════════════════"
    log_info "Next: Run the gh release create command above to publish."
fi
SCRIPT_BODY

    chmod +x "${output_file}"
}

generate_promotion_checklist() {
    local rc_tag="$1"
    local commit_sha="$2"
    local output_file="$3"
    local ga_tag
    ga_tag=$(extract_ga_tag_from_rc "${rc_tag}")
    local version
    version=$(extract_version_from_rc "${rc_tag}")
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat > "${output_file}" <<EOF
# RC → GA Promotion Checklist

**RC Tag**: \`${rc_tag}\`
**Target GA Tag**: \`${ga_tag}\`
**Commit**: \`${commit_sha}\`
**Bundle Generated**: ${timestamp}

---

## Pre-Promotion Verification

- [ ] All required CI checks passed (see REQUIRED_CHECKS.txt)
- [ ] RC has been stable in staging for 24-48 hours
- [ ] No critical bugs reported during stabilization
- [ ] Promotion bundle artifact downloaded

## Promotion Steps

### Option A: Use the generated script (recommended)

\`\`\`bash
# Dry run first
./promote_to_ga.sh --dry-run

# Execute promotion
./promote_to_ga.sh
\`\`\`

### Option B: Manual steps

1. **Re-verify the RC is green**:
   \`\`\`bash
   ./scripts/release/verify-green-for-tag.sh --tag ${rc_tag} --commit ${commit_sha}
   \`\`\`

2. **Create GA tag**:
   \`\`\`bash
   git tag -a ${ga_tag} ${commit_sha} -m "MVP-4 Stabilization Release ${ga_tag}"
   \`\`\`

3. **Push GA tag**:
   \`\`\`bash
   git push origin ${ga_tag}
   \`\`\`

4. **Create GitHub Release**:
   \`\`\`bash
   gh release create ${ga_tag} \\
     --title "v${version} - MVP-4 Stabilization" \\
     --notes-file docs/releases/MVP-4_STABILIZATION_RELEASE_NOTES.md
   \`\`\`

## Post-Promotion

- [ ] Verify GitHub Release is published
- [ ] Update CHANGELOG.md if needed
- [ ] Announce release in team channels
- [ ] Monitor production metrics for 24-48 hours
- [ ] Archive this promotion bundle

## Rollback (if needed)

\`\`\`bash
# Delete GA tag locally and remotely
git tag -d ${ga_tag}
git push origin :refs/tags/${ga_tag}

# Delete GitHub Release if created
gh release delete ${ga_tag} --yes

# Revert to previous stable version if necessary
\`\`\`

---

**Bundle ID**: ${rc_tag}
**Generated by**: build-promotion-bundle.sh v1.0.0
EOF
}

capture_truth_table() {
    local rc_tag="$1"
    local commit_sha="$2"
    local output_file="$3"

    log_info "Capturing verification truth table..."

    # Run verify-green-for-tag and capture output
    # Note: This may fail if checks aren't green, but we still capture output
    {
        echo "# Required Checks Snapshot"
        echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# Tag: ${rc_tag}"
        echo "# Commit: ${commit_sha}"
        echo ""
        "${REPO_ROOT}/scripts/release/verify-green-for-tag.sh" \
            --tag "${rc_tag}" \
            --commit "${commit_sha}" 2>&1 || true
    } > "${output_file}"
}

# --- Main ---
main() {
    local tag=""
    local commit_sha=""
    local output_dir=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --tag)
                tag="$2"
                shift 2
                ;;
            --commit)
                commit_sha="$2"
                shift 2
                ;;
            --output)
                output_dir="$2"
                shift 2
                ;;
            --help)
                print_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                print_usage
                exit 2
                ;;
        esac
    done

    # Validate required arguments
    if [[ -z "${tag}" ]]; then
        log_error "Missing required argument: --tag"
        print_usage
        exit 2
    fi
    if [[ -z "${commit_sha}" ]]; then
        log_error "Missing required argument: --commit"
        print_usage
        exit 2
    fi

    # Validate tag format
    validate_rc_tag "${tag}"

    # Set default output directory
    if [[ -z "${output_dir}" ]]; then
        output_dir="${REPO_ROOT}/artifacts/promotion-bundles/${tag}"
    fi

    log_info "═══════════════════════════════════════════════════════════════"
    log_info "  Building Promotion Bundle"
    log_info "═══════════════════════════════════════════════════════════════"
    log_info "Script version: ${SCRIPT_VERSION}"
    log_info "RC Tag: ${tag}"
    log_info "Commit: ${commit_sha}"
    log_info "Output: ${output_dir}"
    echo ""

    # Create output directory
    mkdir -p "${output_dir}"

    # Generate bundle files
    log_info "Generating github_release.md..."
    generate_github_release_md "${tag}" "${commit_sha}" "${output_dir}/github_release.md"

    log_info "Generating promote_to_ga.sh..."
    generate_promote_to_ga_script "${tag}" "${commit_sha}" "${output_dir}/promote_to_ga.sh"

    log_info "Generating PROMOTION_CHECKLIST.md..."
    generate_promotion_checklist "${tag}" "${commit_sha}" "${output_dir}/PROMOTION_CHECKLIST.md"

    log_info "Capturing REQUIRED_CHECKS.txt..."
    capture_truth_table "${tag}" "${commit_sha}" "${output_dir}/REQUIRED_CHECKS.txt"

    # List bundle contents
    echo ""
    log_success "═══════════════════════════════════════════════════════════════"
    log_success "  Promotion Bundle Created"
    log_success "═══════════════════════════════════════════════════════════════"
    echo ""
    log_info "Bundle location: ${output_dir}"
    log_info "Contents:"
    ls -la "${output_dir}" | while read -r line; do
        echo "  ${line}"
    done
    echo ""
    log_info "To promote to GA, run:"
    log_info "  cd ${output_dir} && ./promote_to_ga.sh"
    echo ""

    # Output the bundle path for CI to use
    echo "BUNDLE_PATH=${output_dir}"
}

main "$@"
