#!/usr/bin/env npx tsx
/**
 * Go-Live Release Notes Generator
 *
 * Generates release notes from an evidence bundle for go-live releases.
 * Creates both markdown and JSON formats suitable for GitHub releases.
 *
 * Usage:
 *   npx tsx scripts/release/generate-go-live-release-notes.ts [evidence-dir]
 *   pnpm release:go-live:notes
 *
 * Environment variables:
 *   EVIDENCE_DIR     Path to evidence directory
 *   VERSION          Release version (default: from package.json)
 */

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

interface GoLiveEvidence {
  version: string;
  generatedAt: string;
  git: {
    sha: string;
    shortSha: string;
    branch: string;
    dirty: boolean;
    author?: string;
    message?: string;
  };
  toolchain: {
    node: string;
    pnpm: string;
    platform: string;
    arch: string;
  };
  checks: Record<
    string,
    {
      status: 'passed' | 'failed' | 'skipped';
      durationMs: number;
      summary?: string;
    }
  >;
  summary: {
    passed: boolean;
    totalChecks: number;
    passedChecks: number;
    failedChecks: number;
    durationMs: number;
  };
  metadata?: {
    ci: boolean;
    ciProvider?: string;
    runId?: string;
    runUrl?: string;
  };
}

interface ReleaseNotes {
  version: string;
  tagName: string;
  sha: string;
  title: string;
  body: string;
  prerelease: boolean;
  evidence: {
    bundlePath: string;
    checksumsSha256: Record<string, string>;
  };
}

function getDefaultEvidenceDir(): string {
  const result = spawnSync('git', ['rev-parse', 'HEAD'], {
    encoding: 'utf8',
    stdio: 'pipe',
  });
  const sha = result.stdout?.trim() || 'unknown';
  return path.join('artifacts', 'evidence', 'go-live', sha);
}

function getPackageVersion(): string {
  try {
    const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    return pkg.version || '0.0.0';
  } catch {
    return '0.0.0';
  }
}

function loadChecksums(evidenceDir: string): Record<string, string> {
  const checksumPath = path.join(evidenceDir, 'checksums.txt');
  const result: Record<string, string> = {};

  if (!fs.existsSync(checksumPath)) {
    return result;
  }

  const content = fs.readFileSync(checksumPath, 'utf8');
  for (const line of content.trim().split('\n')) {
    const match = line.match(/^([a-f0-9]{64})\s{2}(.+)$/);
    if (match) {
      result[match[2]] = match[1];
    }
  }

  return result;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

function generateMarkdownBody(evidence: GoLiveEvidence, version: string): string {
  const statusIcon = evidence.summary.passed ? '✅' : '❌';
  const statusText = evidence.summary.passed ? 'All checks passed' : 'Some checks failed';

  const checkRows = Object.entries(evidence.checks)
    .map(([name, check]) => {
      const icon =
        check.status === 'passed' ? '✅' : check.status === 'skipped' ? '⏭️' : '❌';
      return `| ${name} | ${icon} ${check.status} | ${formatDuration(check.durationMs)} |`;
    })
    .join('\n');

  return `## Go-Live Release ${version}

${statusIcon} **Status:** ${statusText}

### Verification Summary

| Metric | Value |
|--------|-------|
| Commit | \`${evidence.git.sha}\` |
| Branch | ${evidence.git.branch} |
| Total Checks | ${evidence.summary.totalChecks} |
| Passed | ${evidence.summary.passedChecks} |
| Failed | ${evidence.summary.failedChecks} |
| Duration | ${formatDuration(evidence.summary.durationMs)} |

### Check Results

| Check | Status | Duration |
|-------|--------|----------|
${checkRows}

### Toolchain

- **Node.js:** ${evidence.toolchain.node}
- **pnpm:** ${evidence.toolchain.pnpm}
- **Platform:** ${evidence.toolchain.platform}/${evidence.toolchain.arch}

### Evidence Bundle

This release includes a verified evidence bundle proving go-live readiness.

- **Evidence Schema Version:** ${evidence.version}
- **Generated At:** ${evidence.generatedAt}
${
  evidence.metadata?.runUrl
    ? `- **CI Run:** [View Workflow](${evidence.metadata.runUrl})`
    : ''
}

### Artifacts

The following artifacts are attached to this release:

- \`evidence.json\` - Machine-readable evidence bundle
- \`evidence.md\` - Human-readable summary
- \`checksums.txt\` - SHA-256 checksums

### Verification

To verify the release artifacts:

\`\`\`bash
# Download and verify checksums
sha256sum -c checksums.txt
\`\`\`

---
*Generated by generate-go-live-release-notes.ts*
`;
}

function main(): void {
  console.log('========================================');
  console.log('  Go-Live Release Notes Generator');
  console.log('========================================\n');

  // Get evidence directory
  const evidenceDir = process.argv[2] || process.env.EVIDENCE_DIR || getDefaultEvidenceDir();
  console.log(`[release-notes] Evidence directory: ${evidenceDir}`);

  // Load evidence
  const evidencePath = path.join(evidenceDir, 'evidence.json');
  if (!fs.existsSync(evidencePath)) {
    console.error(`\n❌ Evidence not found: ${evidencePath}`);
    console.error('   Run "pnpm evidence:go-live:gen" first.');
    process.exit(1);
  }

  const evidence: GoLiveEvidence = JSON.parse(fs.readFileSync(evidencePath, 'utf8'));
  console.log(`[release-notes] Loaded evidence for commit ${evidence.git.sha}`);

  // Get version
  const version = process.env.VERSION || getPackageVersion();
  const tagName = `v${version}-go-live`;
  console.log(`[release-notes] Version: ${version}, Tag: ${tagName}`);

  // Generate release notes
  const body = generateMarkdownBody(evidence, version);
  const checksums = loadChecksums(evidenceDir);

  const releaseNotes: ReleaseNotes = {
    version,
    tagName,
    sha: evidence.git.sha,
    title: `Go-Live Release ${version}`,
    body,
    prerelease: !evidence.summary.passed,
    evidence: {
      bundlePath: evidenceDir,
      checksumsSha256: checksums,
    },
  };

  // Write outputs
  const outDir = evidenceDir;
  const mdPath = path.join(outDir, 'RELEASE_NOTES.md');
  const jsonPath = path.join(outDir, 'release-notes.json');

  fs.writeFileSync(mdPath, body);
  console.log(`[release-notes] Wrote ${mdPath}`);

  fs.writeFileSync(jsonPath, JSON.stringify(releaseNotes, null, 2));
  console.log(`[release-notes] Wrote ${jsonPath}`);

  // Summary
  console.log('\n========================================');
  if (evidence.summary.passed) {
    console.log(`  ✅ Release notes generated for ${tagName}`);
  } else {
    console.log(`  ⚠️  Release notes generated (checks failed)`);
  }
  console.log('========================================\n');

  // Exit with appropriate code
  process.exit(evidence.summary.passed ? 0 : 1);
}

main();
