#!/usr/bin/env bash
# verify_dependency_freeze.sh
#
# Verifies that dependencies have not changed during RC stabilization.
# Compares current lockfile against a baseline to detect any modifications.
#
# Usage:
#   ./scripts/release/verify_dependency_freeze.sh [OPTIONS]
#
# Options:
#   --baseline <ref>     Git ref for baseline (default: latest rc-* tag)
#   --lockfile <path>    Path to lockfile (default: pnpm-lock.yaml)
#   --allow-patch        Allow patch version updates
#   --report             Generate detailed report
#   --strict             Fail on any change
#   --help               Show this help message
#
# Exit codes:
#   0 - No dependency changes (or only allowed changes)
#   1 - Dependencies changed (freeze violation)
#   2 - Invalid arguments or configuration error

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
STATE_DIR="${REPO_ROOT}/docs/releases/_state"
STATE_FILE="${STATE_DIR}/dependency_freeze_state.json"

# Defaults
BASELINE=""
LOCKFILE="pnpm-lock.yaml"
ALLOW_PATCH=false
GENERATE_REPORT=false
STRICT_MODE=false

# Timestamp
CHECK_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --baseline)
      BASELINE="$2"
      shift 2
      ;;
    --lockfile)
      LOCKFILE="$2"
      shift 2
      ;;
    --allow-patch)
      ALLOW_PATCH=true
      shift
      ;;
    --report)
      GENERATE_REPORT=true
      shift
      ;;
    --strict)
      STRICT_MODE=true
      shift
      ;;
    --help)
      head -25 "$0" | tail -21
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

# Find latest RC tag if no baseline specified
find_latest_rc_tag() {
  git tag -l 'v*.*.*-rc.*' --sort=-v:refname | head -1
}

# Get lockfile content at a specific ref
get_lockfile_at_ref() {
  local ref="$1"
  local file="$2"

  git show "${ref}:${file}" 2>/dev/null || echo ""
}

# Extract package versions from pnpm lockfile
extract_versions() {
  local lockfile_content="$1"

  # Extract packages section and version info
  echo "$lockfile_content" | grep -E "^  ['\"]?[a-zA-Z@]" | head -100 || true
}

# Compare two lockfiles and find differences
compare_lockfiles() {
  local baseline_content="$1"
  local current_content="$2"

  local baseline_file=$(mktemp)
  local current_file=$(mktemp)

  echo "$baseline_content" > "$baseline_file"
  echo "$current_content" > "$current_file"

  # Find differences
  diff -u "$baseline_file" "$current_file" 2>/dev/null || true

  rm -f "$baseline_file" "$current_file"
}

# Check if difference is only patch version
is_patch_only() {
  local diff_output="$1"

  # Check for major/minor version changes
  if echo "$diff_output" | grep -E "^[\+\-].*[0-9]+\.[0-9]+\.[0-9]+" | grep -vE "^[\+\-].*[0-9]+\.[0-9]+\.[0-9]+->" >/dev/null 2>&1; then
    return 1
  fi
  return 0
}

# Generate report
generate_report() {
  local baseline="$1"
  local diff_output="$2"
  local status="$3"

  local report_dir="${REPO_ROOT}/artifacts/reports"
  mkdir -p "$report_dir"

  local report_file="${report_dir}/dependency-freeze-$(date +%Y%m%d-%H%M%S).md"

  cat > "$report_file" <<EOF
# Dependency Freeze Verification Report

**Generated:** ${CHECK_TIMESTAMP}
**Baseline:** ${baseline}
**Current:** HEAD
**Status:** ${status}

---

## Summary

| Check | Result |
|-------|--------|
| Lockfile Changed | $([ -n "$diff_output" ] && echo "Yes" || echo "No") |
| Strict Mode | ${STRICT_MODE} |
| Patch Updates Allowed | ${ALLOW_PATCH} |
| Overall Status | ${status} |

---

## Changes Detected

\`\`\`diff
${diff_output:-No changes detected}
\`\`\`

---

## Recommendations

$(generate_recommendations "$status" "$diff_output")

---

**Report generated by:** verify_dependency_freeze.sh
EOF

  echo "$report_file"
}

generate_recommendations() {
  local status="$1"
  local diff_output="$2"

  if [[ "$status" == "PASS" ]]; then
    echo "Dependencies are frozen and stable. No action required."
  elif [[ "$status" == "WARN" ]]; then
    echo "- Review the patch version changes"
    echo "- Ensure changes are intentional security updates"
    echo "- Consider regenerating RC if changes are substantial"
  else
    echo "- **FREEZE VIOLATION:** Dependencies have changed since RC baseline"
    echo "- Investigate the source of dependency changes"
    echo "- Either revert changes or cut a new RC"
    echo "- Do not proceed with GA promotion until resolved"
  fi
}

# Update state file
update_state() {
  local baseline="$1"
  local status="$2"
  local has_changes="$3"

  mkdir -p "$(dirname "$STATE_FILE")"

  local state
  state=$(cat "$STATE_FILE" 2>/dev/null || echo '{"version":"1.0.0","checks":[]}')

  state=$(echo "$state" | jq \
    --arg time "$CHECK_TIMESTAMP" \
    --arg baseline "$baseline" \
    --arg status "$status" \
    --argjson has_changes "$has_changes" \
    --arg strict "$STRICT_MODE" \
    --arg allow_patch "$ALLOW_PATCH" \
    '.last_check = $time |
     .last_result = {
       baseline: $baseline,
       status: $status,
       has_changes: $has_changes,
       strict_mode: ($strict == "true"),
       allow_patch: ($allow_patch == "true")
     } |
     .checks = ([{
       timestamp: $time,
       baseline: $baseline,
       status: $status,
       has_changes: $has_changes
     }] + .checks[:49])')

  echo "$state" > "$STATE_FILE"
}

# Main function
main() {
  echo "========================================" >&2
  echo "DEPENDENCY FREEZE VERIFICATION" >&2
  echo "========================================" >&2
  echo "" >&2

  # Find baseline if not specified
  if [[ -z "$BASELINE" ]]; then
    BASELINE=$(find_latest_rc_tag)
    if [[ -z "$BASELINE" ]]; then
      echo "Error: No RC tag found and no baseline specified" >&2
      exit 2
    fi
    echo "Using latest RC tag as baseline: $BASELINE" >&2
  fi

  echo "  Baseline: $BASELINE" >&2
  echo "  Lockfile: $LOCKFILE" >&2
  echo "  Strict Mode: $STRICT_MODE" >&2
  echo "  Allow Patch: $ALLOW_PATCH" >&2
  echo "" >&2

  # Verify baseline exists
  if ! git rev-parse "$BASELINE" >/dev/null 2>&1; then
    echo "Error: Baseline ref '$BASELINE' not found" >&2
    exit 2
  fi

  # Get lockfile contents
  echo "Fetching baseline lockfile..." >&2
  local baseline_content
  baseline_content=$(get_lockfile_at_ref "$BASELINE" "$LOCKFILE")

  if [[ -z "$baseline_content" ]]; then
    echo "Error: Could not read lockfile at baseline" >&2
    exit 2
  fi

  echo "Reading current lockfile..." >&2
  local current_content
  if [[ -f "$LOCKFILE" ]]; then
    current_content=$(cat "$LOCKFILE")
  else
    echo "Error: Current lockfile not found: $LOCKFILE" >&2
    exit 2
  fi

  # Compare lockfiles
  echo "Comparing lockfiles..." >&2
  local diff_output
  diff_output=$(compare_lockfiles "$baseline_content" "$current_content")

  local status="PASS"
  local has_changes=false
  local exit_code=0

  if [[ -n "$diff_output" ]]; then
    has_changes=true
    echo "" >&2
    echo "Changes detected in lockfile:" >&2
    printf '%s\n' "$diff_output" | sed -n '1,50p' >&2

    if [[ "$ALLOW_PATCH" == "true" ]] && is_patch_only "$diff_output"; then
      status="WARN"
      echo "" >&2
      echo "Only patch version changes detected (allowed with --allow-patch)" >&2
    else
      status="FAIL"
      exit_code=1
    fi
  else
    echo "" >&2
    echo "No changes detected in lockfile" >&2
  fi

  # Apply strict mode
  if [[ "$STRICT_MODE" == "true" && "$has_changes" == "true" ]]; then
    status="FAIL"
    exit_code=1
  fi

  # Generate report if requested
  if [[ "$GENERATE_REPORT" == "true" ]]; then
    local report_file
    report_file=$(generate_report "$BASELINE" "$diff_output" "$status")
    echo "" >&2
    echo "Report generated: $report_file" >&2
  fi

  # Update state
  update_state "$BASELINE" "$status" "$has_changes"

  # Print summary
  echo "" >&2
  echo "========================================" >&2
  if [[ "$status" == "PASS" ]]; then
    echo "✅ DEPENDENCY FREEZE: VERIFIED" >&2
  elif [[ "$status" == "WARN" ]]; then
    echo "⚠️  DEPENDENCY FREEZE: WARNING" >&2
  else
    echo "❌ DEPENDENCY FREEZE: VIOLATION" >&2
  fi
  echo "========================================" >&2
  echo "  Baseline: $BASELINE" >&2
  echo "  Changes:  $has_changes" >&2
  echo "  Status:   $status" >&2
  echo "========================================" >&2

  # Output JSON for CI integration
  cat <<EOF
{
  "timestamp": "${CHECK_TIMESTAMP}",
  "baseline": "${BASELINE}",
  "lockfile": "${LOCKFILE}",
  "status": "${status}",
  "has_changes": ${has_changes},
  "strict_mode": ${STRICT_MODE},
  "allow_patch": ${ALLOW_PATCH}
}
EOF

  exit $exit_code
}

main "$@"
