import { convertLineageToProv } from '../provExporter.js';
import { LineageGraph } from '../lineage.js';

describe('PROV Exporter', () => {
  it('should convert a simple lineage graph to PROV-JSON', () => {
    const graph: LineageGraph = {
      tenantId: 'tenant-1',
      generatedAt: new Date(),
      nodes: [
        {
          id: 'entity-1',
          type: 'DataArtifact',
          label: 'Artifact 1',
          createdAt: new Date('2023-01-01T10:00:00Z'),
          updatedAt: new Date('2023-01-01T10:00:00Z'),
          metadata: { version: '1.0' },
        },
        {
          id: 'action-1',
          type: 'Action',
          label: 'Build Job',
          createdAt: new Date('2023-01-01T10:05:00Z'),
          updatedAt: new Date('2023-01-01T10:10:00Z'),
          metadata: { status: 'SUCCESS' },
        },
        {
          id: 'user-1',
          type: 'User',
          label: 'Alice',
          createdAt: new Date('2023-01-01T09:00:00Z'),
          updatedAt: new Date('2023-01-01T09:00:00Z'),
          metadata: { email: 'alice@example.com' },
        }
      ],
      edges: [
        {
          sourceId: 'action-1', // Activity
          targetId: 'entity-1', // Entity
          relation: 'generatedBy', // Entity generated by Activity
          timestamp: new Date(),
          metadata: {},
        },
        {
           sourceId: 'user-1', // Agent
           targetId: 'action-1', // Activity
           relation: 'associatedWith', // Agent associated with Activity
           timestamp: new Date(),
           metadata: {},
        }
      ]
    };

    const prov = convertLineageToProv(graph);

    expect(prov).toBeDefined();
    expect(prov.prefix.summit).toBe('https://summit.dev/provenance/');

    // Check Entity
    expect(prov.entity['summit:entity-1']).toBeDefined();
    expect(prov.entity['summit:entity-1']['prov:type']).toBe('DataArtifact');

    // Check Activity
    expect(prov.activity['summit:action-1']).toBeDefined();
    expect(prov.activity['summit:action-1']['prov:type']).toBe('Action');
    expect(prov.activity['summit:action-1']['prov:startTime']).toBe('2023-01-01T10:05:00.000Z');

    // Check Agent
    expect(prov.agent['summit:user-1']).toBeDefined();

    // Check Relations
    const generatedByKeys = Object.keys(prov.wasGeneratedBy || {});
    expect(generatedByKeys.length).toBeGreaterThan(0);
    const genRel = prov.wasGeneratedBy![generatedByKeys[0]];
    expect(genRel['prov:entity']).toBe('summit:entity-1');
    expect(genRel['prov:activity']).toBe('summit:action-1');

    const assocKeys = Object.keys(prov.wasAssociatedWith || {});
    expect(assocKeys.length).toBeGreaterThan(0);
    const assocRel = prov.wasAssociatedWith![assocKeys[0]];
    expect(assocRel['prov:activity']).toBe('summit:action-1');
    expect(assocRel['prov:agent']).toBe('summit:user-1');
  });
});
