/**
 * FactAPI Pro
 * White-label verification API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import VerifyRequest from '../model/VerifyRequest';
import VerifyResponse from '../model/VerifyResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi.
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the verifyClaim operation.
     * @callback module:api/DefaultApi~verifyClaimCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VerifyResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Verify a claim
     * @param {module:model/VerifyRequest} verifyRequest
     * @param {module:api/DefaultApi~verifyClaimCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VerifyResponse}
     */
    verifyClaim(verifyRequest, callback) {
      let postBody = verifyRequest;
      // verify the required parameter 'verifyRequest' is set
      if (verifyRequest === undefined || verifyRequest === null) {
        throw new Error("Missing the required parameter 'verifyRequest' when calling verifyClaim");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = VerifyResponse;
      return this.apiClient.callApi(
        '/verify', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
