import { IndicatorDefinition, ThreatContext } from './types';

const contexts: ThreatContext[] = [
  'domestic',
  'public_figure',
  'workplace',
  'school',
  'general',
];

const families = [
  {
    key: 'COMM',
    family: 'threat_communications',
    weight: 1.2,
    labels: [
      'Direct threat stated',
      'Conditional threat',
      'Veiled threat',
      'Repeated hostile messages',
      'Escalating language severity',
      'Deadline or ultimatum',
      'Leakage to third parties',
      'Threat rehearsal in writing',
      'Obsessive frequency of contact',
      'Communication despite no-contact directive',
      'Multi-channel contact persistence',
      'Demand for acknowledgment or response',
    ],
  },
  {
    key: 'FIXATION',
    family: 'fixation',
    weight: 1.15,
    labels: [
      'Persistent preoccupation with target',
      'Identity fusion with grievance',
      'Collection of target imagery or info',
      'Rumination on humiliation',
      'Grandiose destiny framing',
      'Nothing-to-lose statements',
      'Romanticized entitlement',
      'Delusional personal significance claims',
      'Persistent narrative rewriting',
      'Sleep or work disruption due to fixation',
      'Target-centered online posting pattern',
      'Refusal to disengage after intervention',
    ],
  },
  {
    key: 'APPROACH',
    family: 'approach',
    weight: 1.3,
    labels: [
      'Physical approach attempt',
      'Repeated proximity seeking',
      'Travel toward target site',
      'Loitering or surveillance near target',
      'Boundary testing at access points',
      'Following or shadowing behavior',
      'Unwanted gifts or packages',
      'Proxy contact through associates',
      'Event attendance to access target',
      'Attempts to enter restricted spaces',
      'Use of disguise to approach',
      'Location triangulation efforts',
    ],
  },
  {
    key: 'ESC',
    family: 'escalation',
    weight: 1.35,
    labels: [
      'Increase in frequency over time',
      'Increase in severity',
      'Shift from words to acts',
      'Shortening interval between incidents',
      'New channels after block',
      'Escalation after setback',
      'Escalation after humiliation',
      'Escalation after relationship rupture',
      'Escalation after legal notice',
      'New target adjacency after access loss',
      'Broader collateral references',
      'Failure of prior de-escalation attempts',
    ],
  },
  {
    key: 'PLAN',
    family: 'planning',
    weight: 1.4,
    labels: [
      'Research of routines or locations',
      'Research of security patterns',
      'Acquisition of transport or logistics',
      'Dry runs',
      'Timing references',
      'Lists maps or schedules',
      'Acquisition of restraints or tools',
      'Procurement linked to attack fantasy',
      'Concealment of movements',
      'Farewell or legacy behaviors',
      'Asset liquidation',
      'Finalizing target opportunity window',
    ],
  },
  {
    key: 'ACCESS',
    family: 'capability_access',
    weight: 1.35,
    labels: [
      'Weapon access claim',
      'Corroborated weapon access',
      'Access to vehicle for approach',
      'Physical ability to execute plan',
      'Knowledge of target environment',
      'Insider access knowledge',
      'Access to sensitive target info',
      'Network of helpers',
      'Technical ability to evade controls',
      'Prior successful boundary breaches',
      'Access to target schedule',
      'Means to maintain prolonged pursuit',
    ],
  },
  {
    key: 'HISTORY',
    family: 'history',
    weight: 1.25,
    labels: [
      'Prior threats to same target',
      'Prior threats to others',
      'Prior assaultive conduct',
      'Prior stalking or harassment',
      'Prior domestic-violence incidents',
      'Prior weapons misuse',
      'Prior protection-order violations',
      'Prior school or workplace discipline linked to threats',
      'Prior arrests related to intimidation',
      'Documented coercive control history',
      'Prior fixation on substitute targets',
      'Recidivism after sanction',
    ],
  },
  {
    key: 'TRIGGER',
    family: 'triggering_stressors',
    weight: 1.1,
    labels: [
      'Recent breakup or rejection',
      'Job loss or discipline',
      'Eviction or financial collapse',
      'Public shaming',
      'Custody or divorce dispute',
      'Legal setback',
      'Perceived betrayal by institution',
      'Bereavement with destabilization',
      'Housing instability',
      'Substance-related destabilization',
      'Sudden social isolation',
      'Acute grievance activation event',
    ],
  },
  {
    key: 'PROTECT',
    family: 'protective',
    weight: 1.0,
    direction: 'risk_down' as const,
    labels: [
      'Credible third-party supervision',
      'Voluntary treatment engagement',
      'Stable prosocial ties',
      'Clear disengagement signs',
      'Time since last incident increasing',
      'Compliance with protective orders',
      'Cooperative contact with investigators',
      'No means access despite threats',
      'Contradictory evidence lowering credibility',
      'Strong geographic separation',
      'Stable employment restored',
      'Demonstrated response to intervention',
    ],
  },
  {
    key: 'CTX',
    family: 'context_amplifiers',
    weight: 1.3,
    labels: [
      'Domestic coercive control pattern',
      'Child-access conflict',
      'Public-figure parasocial delusion',
      'School grievance with leakage',
      'Workplace insider retaliation motive',
      'Final justice or martyrdom framing',
      'Symbolic date selection',
      'Interest in prior attack scripts',
      'Collateral target mention',
      'Concerned third-party warnings',
      'Security probing behavior',
      'Sudden silence after escalation or planning',
    ],
  },
];

export const INDICATOR_REGISTRY: IndicatorDefinition[] = families.flatMap((f) =>
  f.labels.map((label, index) => ({
    indicator_id: `TA_${f.key}_${String(index + 1).padStart(3, '0')}`,
    family: f.family,
    label,
    description: label,
    allowed_values: [0, 0.5, 1, 2],
    contexts,
    direction: f.direction ?? 'risk_up',
    default_weight: f.weight,
    requires_evidence: true,
    evidence_min: 1,
    notes: 'Summit original, clean-room',
    high_importance: f.key === 'PLAN' || f.key === 'ACCESS',
  })),
);

export const INDICATOR_BY_ID = new Map(
  INDICATOR_REGISTRY.map((indicator) => [indicator.indicator_id, indicator]),
);
