// Nodes
CREATE CONSTRAINT IF NOT EXISTS ON (c:Case) ASSERT c.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS ON (a:Answer) ASSERT a.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS ON (x:Export) ASSERT x.id IS UNIQUE;