#!/usr/bin/env bash
set -euo pipefail

DATE_INPUT="${1:-}"
if [[ -n "$DATE_INPUT" ]]; then
  RUN_DATE="$DATE_INPUT"
else
  RUN_DATE="$(date -u +%F)"
fi

EVIDENCE_ROOT="docs/ops/evidence/daily-sprint-${RUN_DATE}"
REPORT_PATH="docs/ops/DAILY_SPRINT_${RUN_DATE}.md"
mkdir -p "$EVIDENCE_ROOT"

PR_TXT="$EVIDENCE_ROOT/pr_list.txt"
PR_ERR="$EVIDENCE_ROOT/pr_list.err"
ISSUE_TXT="$EVIDENCE_ROOT/issue_list.txt"
ISSUE_ERR="$EVIDENCE_ROOT/issue_list.err"

: > "$PR_TXT"
: > "$PR_ERR"
: > "$ISSUE_TXT"
: > "$ISSUE_ERR"

if command -v gh >/dev/null 2>&1; then
  gh pr list --repo BrianCLong/summit --limit 20 >"$PR_TXT" 2>"$PR_ERR" || true
  gh issue list --repo BrianCLong/summit --limit 20 \
    --label security --label ga --label governance --label osint --label bolt \
    >"$ISSUE_TXT" 2>"$ISSUE_ERR" || true
else
  echo "gh CLI unavailable in runtime" >"$PR_ERR"
  echo "gh CLI unavailable in runtime" >"$ISSUE_ERR"
fi

python3 - <<PY
import hashlib
import json
from pathlib import Path

run_date = "$RUN_DATE"
base = Path("$EVIDENCE_ROOT")

pr_err = (base / "pr_list.err").read_text().strip()
issue_err = (base / "issue_list.err").read_text().strip()
pr_lines = [line for line in (base / "pr_list.txt").read_text().splitlines() if line.strip()]
issue_lines = [line for line in (base / "issue_list.txt").read_text().splitlines() if line.strip()]

report = {
    "scope": "daily-sprint",
    "date": run_date,
    "evidence": {
        "pr_list": {"count": len(pr_lines), "error": pr_err or None},
        "issue_list": {"count": len(issue_lines), "error": issue_err or None},
    },
    "notes": [
        "Daily sprint evidence generated by scripts/ops/daily-sprint-loop.sh.",
        "If GitHub triage is unavailable, see pr_list.err and issue_list.err.",
    ],
}

metrics = {
    "pr_count": report["evidence"]["pr_list"]["count"],
    "issue_count": report["evidence"]["issue_list"]["count"],
    "pr_error": bool(report["evidence"]["pr_list"]["error"]),
    "issue_error": bool(report["evidence"]["issue_list"]["error"]),
}

(base / "report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
(base / "metrics.json").write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n")

h = hashlib.sha256()
for name in ["report.json", "metrics.json", "pr_list.txt", "pr_list.err", "issue_list.txt", "issue_list.err"]:
    h.update((base / name).read_bytes())
(base / "stamp.json").write_text(
    json.dumps({"hash": h.hexdigest(), "provenance": "daily-sprint"}, indent=2, sort_keys=True) + "\n"
)
PY

cat > "$REPORT_PATH" <<MD
# Daily Sprint — ${RUN_DATE}

Mode: Sensing

## Evidence Bundle

- Evidence root: \`${EVIDENCE_ROOT}\`
- report.json, metrics.json, stamp.json
- Raw logs: pr_list.err, issue_list.err

## Sprint Plan (3–6 tasks)

1. Restore GitHub API connectivity and re-run PR/issue triage.
   - Goal: capture top PRs and labeled issues for a current sprint plan.
   - Scope: GitHub API access (gh CLI), docs/ops evidence outputs.
   - Validation: gh pr list, gh issue list, updated evidence bundle.
2. Register daily sprint prompt in prompts/registry.yaml (governance alignment).
   - Goal: unblock prompt-integrity gate for daily sprint artifacts.
   - Scope: prompts/registry.yaml, governance checks.
   - Validation: node scripts/ci/verify-prompt-integrity.ts.
3. Once GH API is restored, select and execute 1-2 highest-risk PRs (security/GA/CI).
   - Goal: merge-ready fixes with evidence + validation.
   - Scope: determined after triage; limited to single primary zone.
   - Validation: scoped tests plus node scripts/check-boundaries.cjs when code changes.

## Execution Log

- Evidence generated by scripts/ops/daily-sprint-loop.sh for ${RUN_DATE}.
- PR triage count is recorded in report.json.
- Issue triage count is recorded in report.json.

## Blockers

- See report.json and *.err files for current execution constraints.

## MAESTRO Alignment

- MAESTRO Layers: Agents, Tools, Observability, Security.
- Threats Considered: tool abuse, prompt injection, evidence tampering.
- Mitigations: deterministic hash stamp; explicit failure capture; evidence-first outputs.

## End-of-Day Report

- Completed: deterministic evidence bundle generated.
- In progress: triage execution pending runtime connectivity and tooling availability.
- Blocked: deferred pending explicit errors captured in evidence logs.
MD

echo "Daily sprint bundle written: $EVIDENCE_ROOT"
echo "Daily sprint report written: $REPORT_PATH"
