/**
 * Smart Contracting Service
 *
 * AI-driven procurement contract automation:
 * - Auto-generate contracts from demand forecasts
 * - Pre-fill procurement documents with FAR/DFARS clauses
 * - Vendor selection and scoring
 * - Contract lifecycle management
 * - Compliance validation
 */

import express from 'express';
import pino from 'pino';
import pinoHttp from 'pino-http';
import { v4 as uuidv4 } from 'uuid';
import {
  ProcurementContractSchema,
  ContractGenerationRequestSchema,
  ContractLineItemSchema,
  type ProcurementContract,
  type ContractGenerationRequest,
  type ContractLineItem,
} from '@intelgraph/logistics-automation-types';

const logger = pino({ level: process.env.LOG_LEVEL || 'info' });
const app = express();
const PORT = process.env.PORT || 4031;

app.use(express.json());
app.use(pinoHttp({ logger }));

// In-memory store (replace with database in production)
const contracts = new Map<string, ProcurementContract>();

// Standard FAR/DFARS clauses by contract type
const standardClauses = {
  far: [
    'FAR 52.212-4 Contract Terms and Conditions',
    'FAR 52.212-5 Contract Terms and Conditions Required to Implement Statutes',
    'FAR 52.219-8 Utilization of Small Business Concerns',
    'FAR 52.222-21 Prohibition of Segregated Facilities',
    'FAR 52.222-26 Equal Opportunity',
    'FAR 52.232-33 Payment by Electronic Funds Transfer',
  ],
  dfars: [
    'DFARS 252.204-7012 Safeguarding Covered Defense Information',
    'DFARS 252.204-7018 Prohibition on Acquisition of Certain Items',
    'DFARS 252.225-7001 Buy American and Balance of Payments Program',
    'DFARS 252.225-7012 Preference for Certain Domestic Commodities',
    'DFARS 252.232-7003 Electronic Submission of Payment Requests',
  ],
};

// =============================================================================
// HEALTH ENDPOINTS
// =============================================================================

app.get('/health', (_req, res) => {
  res.json({ status: 'healthy', service: 'smart-contracting-service' });
});

// =============================================================================
// CONTRACT GENERATION ENDPOINTS
// =============================================================================

/**
 * AI-powered contract generation from demand forecasts
 */
app.post('/api/contracts/generate', async (req, res) => {
  try {
    const request = ContractGenerationRequestSchema.parse(req.body);

    // Simulate fetching forecasts (would call logistics-automation-service)
    const lineItems: ContractLineItem[] = request.forecastIds.map((forecastId, index) => ({
      lineNumber: index + 1,
      itemId: `ITEM-${String(index + 1).padStart(3, '0')}`,
      nsn: `5905-00-${String(Math.floor(Math.random() * 1000000)).padStart(7, '0')}`,
      description: `Supply item from forecast ${forecastId}`,
      quantity: Math.floor(Math.random() * 500) + 50,
      unitOfMeasure: 'EA',
      unitPrice: Math.floor(Math.random() * 1000) + 100,
      totalPrice: 0, // Will be calculated
      deliveryDate:
        request.requiredDeliveryDate || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      deliveryLocation: 'DLA Distribution Center',
    }));

    // Calculate totals
    lineItems.forEach((item) => {
      item.totalPrice = item.quantity * item.unitPrice;
    });

    const totalValue = lineItems.reduce((sum, item) => sum + item.totalPrice, 0);

    const contract: ProcurementContract = {
      id: uuidv4(),
      contractNumber: `W91CRB-${new Date().getFullYear()}-C-${String(Math.floor(Math.random() * 10000)).padStart(4, '0')}`,
      title: `Auto-Generated Procurement Contract - ${new Date().toISOString().split('T')[0]}`,
      status: 'draft',
      priority: request.priority,
      vendorId: request.preferredVendorIds?.[0] || 'VENDOR-001',
      vendorName: 'Approved Defense Supplier Inc.',
      vendorCage: '1ABC2',
      contractType: 'firm_fixed_price',
      totalValue,
      currency: 'USD',
      lineItems,
      terms: {
        paymentTerms: 'Net 30',
        warrantyPeriodMonths: 12,
        penaltyClause: 'Late delivery penalty of 1% per day, max 10%',
        qualityRequirements: [
          'MIL-STD-1916 Sampling Procedures',
          'ISO 9001:2015 Quality Management',
        ],
        complianceRequirements: [
          'CMMC Level 2 Certification',
          'ITAR Compliance',
          'Buy American Act',
        ],
        securityClassification: 'unclassified',
        exportControlled: false,
        farClauses: standardClauses.far,
        dfarsClauses: standardClauses.dfars,
      },
      effectiveDate: new Date().toISOString(),
      expirationDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      autoGenerated: true,
      sourceForecastIds: request.forecastIds,
      approvals: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    contracts.set(contract.id, contract);
    logger.info(
      { contractId: contract.id, contractNumber: contract.contractNumber },
      'Contract auto-generated',
    );

    res.status(201).json({ data: contract });
  } catch (error) {
    logger.error({ error }, 'Failed to generate contract');
    res.status(400).json({ error: 'Invalid contract generation request', details: error });
  }
});

// =============================================================================
// CONTRACT CRUD ENDPOINTS
// =============================================================================

app.get('/api/contracts', (_req, res) => {
  res.json({ data: Array.from(contracts.values()) });
});

app.get('/api/contracts/:id', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }
  res.json({ data: contract });
});

app.patch('/api/contracts/:id', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }

  const updatedContract = {
    ...contract,
    ...req.body,
    id: contract.id, // Prevent ID modification
    updatedAt: new Date().toISOString(),
  };

  contracts.set(contract.id, updatedContract);
  logger.info({ contractId: contract.id }, 'Contract updated');
  res.json({ data: updatedContract });
});

// =============================================================================
// CONTRACT WORKFLOW ENDPOINTS
// =============================================================================

/**
 * Submit contract for approval
 */
app.post('/api/contracts/:id/submit', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }

  if (contract.status !== 'draft') {
    return res.status(400).json({ error: 'Contract must be in draft status to submit' });
  }

  const updatedContract = {
    ...contract,
    status: 'pending_approval' as const,
    updatedAt: new Date().toISOString(),
  };

  contracts.set(contract.id, updatedContract);
  logger.info({ contractId: contract.id }, 'Contract submitted for approval');
  res.json({ data: updatedContract });
});

/**
 * Approve contract
 */
app.post('/api/contracts/:id/approve', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }

  const { approverId, approverName, level } = req.body;

  const updatedContract = {
    ...contract,
    status: 'approved' as const,
    approvals: [
      ...contract.approvals,
      {
        approverId,
        approverName,
        approvedAt: new Date().toISOString(),
        level: level || contract.approvals.length + 1,
      },
    ],
    updatedAt: new Date().toISOString(),
  };

  contracts.set(contract.id, updatedContract);
  logger.info({ contractId: contract.id, approverId }, 'Contract approved');
  res.json({ data: updatedContract });
});

/**
 * Activate contract (after approval)
 */
app.post('/api/contracts/:id/activate', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }

  if (contract.status !== 'approved') {
    return res.status(400).json({ error: 'Contract must be approved before activation' });
  }

  const updatedContract = {
    ...contract,
    status: 'active' as const,
    updatedAt: new Date().toISOString(),
  };

  contracts.set(contract.id, updatedContract);
  logger.info({ contractId: contract.id }, 'Contract activated');
  res.json({ data: updatedContract });
});

// =============================================================================
// VENDOR ENDPOINTS
// =============================================================================

app.get('/api/vendors/recommended', (req, res) => {
  const { itemCategory, minRating } = req.query;

  // Simulated vendor recommendations
  const vendors = [
    {
      id: 'VENDOR-001',
      name: 'Approved Defense Supplier Inc.',
      cage: '1ABC2',
      rating: 4.8,
      onTimeDeliveryRate: 0.95,
      qualityScore: 0.92,
      cmmcLevel: 2,
      capabilities: ['electronics', 'mechanical', 'consumables'],
    },
    {
      id: 'VENDOR-002',
      name: 'Military Logistics Partners LLC',
      cage: '2DEF3',
      rating: 4.5,
      onTimeDeliveryRate: 0.88,
      qualityScore: 0.89,
      cmmcLevel: 2,
      capabilities: ['consumables', 'packaging', 'transportation'],
    },
    {
      id: 'VENDOR-003',
      name: 'Allied Defense Systems Corp',
      cage: '3GHI4',
      rating: 4.9,
      onTimeDeliveryRate: 0.97,
      qualityScore: 0.95,
      cmmcLevel: 3,
      capabilities: ['electronics', 'software', 'integration'],
    },
  ];

  res.json({ data: vendors });
});

// =============================================================================
// COMPLIANCE VALIDATION
// =============================================================================

app.post('/api/contracts/:id/validate-compliance', (req, res) => {
  const contract = contracts.get(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: 'Contract not found' });
  }

  // Simulate compliance validation
  const validationResults = {
    contractId: contract.id,
    validatedAt: new Date().toISOString(),
    overallStatus: 'compliant',
    checks: [
      { rule: 'FAR Clause Coverage', status: 'pass', message: 'All required FAR clauses included' },
      {
        rule: 'DFARS Clause Coverage',
        status: 'pass',
        message: 'All required DFARS clauses included',
      },
      { rule: 'Buy American Act', status: 'pass', message: 'Domestic sourcing requirements met' },
      { rule: 'CMMC Requirements', status: 'pass', message: 'Vendor CMMC certification verified' },
      { rule: 'Export Control', status: 'pass', message: 'No export-controlled items detected' },
    ],
    recommendations: [],
  };

  logger.info({ contractId: contract.id }, 'Compliance validation completed');
  res.json({ data: validationResults });
});

// =============================================================================
// START SERVER
// =============================================================================

app.listen(PORT, () => {
  logger.info({ port: PORT }, 'Smart Contracting Service started');
});

export default app;
