CREATE CONSTRAINT IF NOT EXISTS FOR (n:Reservation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Tenant) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Pool) REQUIRE n.id IS UNIQUE;
