export const rbacSchema = {
  users: [
    { id: 'alice', roles: ['ANALYST'] },
    { id: 'bob', roles: ['SUPERVISOR'] },
    { id: 'carol', roles: ['SYSTEM_ADMIN'] },
  ],
  roles: [
    {
      id: 'ANALYST',
      permissions: [
        'INVESTIGATION_CREATE',
        'INVESTIGATION_READ',
        'INVESTIGATION_UPDATE',
        'INVESTIGATION_SHARE',
        'ENTITY_CREATE',
        'ENTITY_READ',
        'ENTITY_UPDATE',
        'ENTITY_LINK',
        'ANALYTICS_RUN',
        'ANALYTICS_VIEW_RESULTS',
        'SIMULATION_RUN',
        'FEDERATED_SEARCH',
        'AI_EXTRACTION',
        'DATA_EXPORT',
      ],
      entities: ['INVESTIGATION', 'ENTITY', 'ANALYTICS'],
    },
    {
      id: 'SUPERVISOR',
      permissions: [
        'INVESTIGATION_CREATE',
        'INVESTIGATION_READ',
        'INVESTIGATION_UPDATE',
        'INVESTIGATION_DELETE',
        'INVESTIGATION_SHARE',
        'INVESTIGATION_EXPORT',
        'ENTITY_CREATE',
        'ENTITY_READ',
        'ENTITY_UPDATE',
        'ENTITY_DELETE',
        'ENTITY_LINK',
        'ANALYTICS_RUN',
        'ANALYTICS_VIEW_RESULTS',
        'ML_MODEL_ACCESS',
        'SIMULATION_RUN',
        'FEDERATED_SEARCH',
        'AI_EXTRACTION',
        'COPILOT_ACCESS',
        'API_ACCESS',
        'DATA_EXPORT',
        'DATA_IMPORT',
        'SENSITIVE_DATA_ACCESS',
        'PII_ACCESS',
        'AUDIT_LOG_ACCESS',
      ],
      entities: ['INVESTIGATION', 'ENTITY', 'ANALYTICS', 'DATA', 'ADMIN'],
    },
    {
      id: 'SYSTEM_ADMIN',
      permissions: [
        'USER_MANAGEMENT',
        'ROLE_MANAGEMENT',
        'SYSTEM_CONFIG',
        'AUDIT_LOG_ACCESS',
        'SECURITY_SETTINGS',
        'INVESTIGATION_CREATE',
        'INVESTIGATION_READ',
        'INVESTIGATION_UPDATE',
        'INVESTIGATION_DELETE',
        'INVESTIGATION_SHARE',
        'INVESTIGATION_EXPORT',
        'ENTITY_CREATE',
        'ENTITY_READ',
        'ENTITY_UPDATE',
        'ENTITY_DELETE',
        'ENTITY_LINK',
        'ANALYTICS_RUN',
        'ANALYTICS_VIEW_RESULTS',
        'ML_MODEL_ACCESS',
        'SIMULATION_RUN',
        'FEDERATED_SEARCH',
        'AI_EXTRACTION',
        'COPILOT_ACCESS',
        'API_ACCESS',
        'DATA_EXPORT',
        'DATA_IMPORT',
        'SENSITIVE_DATA_ACCESS',
        'PII_ACCESS',
      ],
      entities: ['INVESTIGATION', 'ENTITY', 'ANALYTICS', 'DATA', 'ADMIN'],
    },
  ],
  entities: [
    { id: 'INVESTIGATION' },
    { id: 'ENTITY' },
    { id: 'ANALYTICS' },
    { id: 'DATA' },
    { id: 'ADMIN' },
  ],
};
