import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default {
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setup/vitest.setup.ts'],
    alias: {
      '@': resolve(__dirname, './src'),
      '@tests': resolve(__dirname, './tests'),
      // Mock ESM-only modules or problematic native modules
      'node-fetch': resolve(__dirname, '../__mocks__/node-fetch.js'),
      'pkcs11js': resolve(__dirname, './tests/__mocks__/pkcs11js.js'),
      '@packages/cache': resolve(__dirname, './tests/__mocks__/packages-cache.js'),
      '@server/pits': resolve(__dirname, './tests/__mocks__/server-pits.js'),
    },
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/e2e/**',
      '**/playwright-tests/**',
      // Legacy excludes from Jest config to prevent immediate CI explosion
      '**/src/connectors/__tests__/gcs-ingest.test.ts',
      '**/tests/governance-acceptance.test.ts',
      '**/tests/integration/',
      '**/tests/e2e/',
      '**/tests/api-docs.test.ts',
      '**/*.flaky.test.ts',
      '**/*.int.test.ts',
      '**/*.integration.test.ts',
      '**/*.e2e.test.ts',
      '**/tests/realtime/',
      '**/tests/federal-integration',
      '**/tests/security/',
      '**/tests/lib/deployment/',
      '**/tests/pre-commit',
      '**/tests/osint/',
      '**/tests/stix',
      '**/tests/orchestrator/',
      '**/tests/document.test.ts',
      '**/tests/bulk-create.test.ts',
      '**/src/maestro/pipelines/__tests__/',
      '**/src/maestro/executors/__tests__/',
      '**/src/middleware/__tests__/reason-for-access.test.ts',
      '**/src/__tests__/ai-copilot.e2e.test.ts',
      '**/src/extensions/__tests__/',
      '**/src/routes/__tests__/compliance.test.ts',
      '**/src/graphql/__tests__/permissions.test.ts',
      '**/src/publishing/__tests__/',
      '**/src/summitsight/',
      '**/src/hunting/__tests__/',
      '**/src/notifications-hub/__tests__/',
      '**/src/repos/__tests__/',
      '**/src/db/__tests__/',
      '**/src/entity-resolution/__tests__/',
      '**/src/billing/entitlements/__tests__/',
      '**/src/conductor/runbooks/',
      '**/src/webhooks/__tests__/',
      '**/src/routes/__tests__/',
      '**/src/pii/__tests__/',
      '**/src/observability/__tests__/',
      '**/src/search/__tests__/',
      '**/tests/bench/',
      '**/tests/tenant-isolation',
      '**/tests/services/security/',
      '**/tests/metrics',
      '**/tests/conductor/',
      '**/tests/internal_command',
      '**/tests/assistant',
      '**/tests/influence_operations',
      '**/tests/plugins/',
      '**/tests/db/',
      '**/src/tests/narrative/',
      '**/src/services/__tests__/',
      '**/src/middleware/__tests__/',
      '**/src/maestro/mcp/__tests__/',
      '**/src/queue/__tests__/',
      '**/src/provenance/__tests__/',
      '**/src/ai/copilot/__tests__/',
      '**/src/compliance/__tests__/',
      '**/src/config/__tests__/',
      '**/src/audit/__tests__/',
      '**/src/aurelius/__tests__/',
      '**/src/conductor/__tests__/',
      '**/src/conductor/scheduling/__tests__/',
      '**/src/conductor/api/__tests__/',
      '**/src/graph/__tests__/',
      '**/src/graphql/__tests__/',
      '**/src/graphql/dataloaders/__tests__/',
      '**/tests/graphAnalytics',
      '**/tests/adversarial/',
      '**/tests/pii/',
      '**/tests/socket-auth',
      '**/tests/recipes',
      '**/tests/tenancy/',
      '**/tests/middleware/',
      '**/tests/hybrid-er',
      '**/tests/canonical/',
      '**/tests/apollo',
      '**/src/tests/llm-governance',
      '**/src/tests/featurePlaceholders',
      '**/src/tests/tenantIsolation',
      '**/src/tests/graphragService',
      '**/src/tests/case-overview-cache',
      '**/src/tests/AuditAccessLogRepo',
      '**/src/__tests__/',
      '**/src/governance/__tests__/',
      '**/src/graph/optimizer/__tests__/',
      '**/src/services/semantic-rag/__tests__/',
      '**/src/services/er/__tests__/',
      '**/src/services/xai-overlay/__tests__/',
      '**/src/conductor/mcp/__tests__/',
      '**/src/conductor/premium-routing/__tests__/',
      '**/src/logging/__tests__/',
      '**/src/cross-border/__tests__/',
      '**/src/time-series/__tests__/',
      '**/src/ingestion/__tests__/',
      '**/src/auth/sso/__tests__/',
      '**/src/resolvers/__tests__/',
      '**/src/http/__tests__/',
      '**/tests/queue',
      '**/tests/graphqlPersisted',
      '**/tests/presence',
      '**/tests/services/RateLimiter',
      '**/tests/maestro/',
      '**/tests/nl-graph-query',
      '**/tests/autonomous/',
      '**/tests/case-spaces',
      '**/tests/secret-manager',
      '**/tests/network-security',
      '**/tests/governance/',
      '**/tests/similarity',
      '**/tests/websocket/',
      '**/tests/metering/',
      '**/tests/narrative',
      '**/tests/forensics-custody',
      '**/tests/alerting/',
      '**/tests/env-config',
      '**/tests/audit-first',
      '**/tests/collab',
      '**/tests/redis',
      '**/tests/services/RedTeamSimulator',
      '**/src/governance/litigation/__tests__/',
      '**/src/governance/retention/__tests__/',
      '**/src/tests/behavioralFingerprintWorker',
      '**/src/tests/audit/',
      '**/src/tests/services/',
      '**/src/tests/time-series-intelligence',
      '**/src/cache/__tests__/',
      '**/src/ingestion/migration/__tests__/',
      '**/src/trust-center/__tests__/',
      '**/src/metering/__tests__/',
      '**/src/dr/__tests__/',
      '**/src/services/reporting/__tests__/',
      '**/src/influence/__tests__/',
      '**/src/feature-flags/__tests__/',
      '**/src/services/billing/__tests__/',
      '**/src/dr/backup-inventory/__tests__/',
      '**/src/lib/__tests__/',
      '**/src/lib/resources/__tests__/',
      '**/src/tests/payments_webhook',
      '**/src/maestro/runs/__tests__/',
      '**/src/workers/__tests__/',
      '**/src/services/entity-resolution/__tests__/',
      '**/src/services/strategic-framework/__tests__/',
      '**/src/conductor/edge/__tests__/',
      '**/tests/ticket-links',
      '**/tests/copilotQuery',
      '**/tests/engagementCascade',
      '**/tests/lib/',
      '**/tests/report-templates',
      '**/tests/utils/',
      '**/tests/pits',
      '**/tests/observability/',
      '**/tests/activity',
      '**/tests/tenants/',
      '**/tests/services/DefensivePsyOpsService',
      '**/tests/services/ComplianceService',
      '**/tests/siem/',
      '**/tests/graphql/',
      '**/tests/realtime-collab',
      '**/src/security/tenant-simulation/__tests__/',
      '**/src/conductor/auth/__tests__/',
      '**/src/websocket/__tests__/',
      '**/src/tests/er/',
      '**/src/graphql/resolvers/__tests__/',
      '**/src/maestro/__tests__/',
      '**/src/kpro/__tests__/',
      '**/src/federation/__tests__/',
      '**/src/tests/semanticSearch',
      '**/src/reporting/__tests__/',
      '**/src/tests/case-dashboard',
      '**/src/tests/audit_migrations',
      '**/src/tests/ai.webhook',
      '**/src/tests/llmAnalystService',
      '**/src/jobs/__tests__/',
      '**/tests/security_scan',
      '**/tests/threat-intelligence',
      '**/tests/resources',
      '**/tests/investigative-thread',
      '**/tests/n8n',
      '**/tests/graphql.test.ts',
      '**/tests/guardrails',
      '**/tests/suggestions',
      '**/tests/exportRoute',
      '**/tests/graphData',
      '**/tests/cyber-deception',
      '**/tests/edge_ops',
      '**/tests/entities',
    ],
    // Prevent tests from hanging
    testTimeout: 20000,
    hookTimeout: 20000,
    poolOptions: {
      threads: {
        singleThread: true,
      },
    },
  },
};
