"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.listCacheKey = exports.withCache = void 0;
const CacheService_js_1 = require("../services/CacheService.js");
/**
 * Wraps a GraphQL resolver function with automatic caching capabilities.
 *
 * This high-order function intercepts the resolver call, checks the cache for an existing result
 * using the key generated by `keyGenerator`, and returns the cached value if found.
 * If not found, it executes the resolver, caches the result, and then returns it.
 *
 * @typeParam TArgs - The type of the arguments passed to the resolver.
 * @typeParam TResult - The return type of the resolver.
 * @param keyGenerator - A function that generates a unique cache key based on the resolver's arguments (parent, args, context, info).
 * @param resolver - The original resolver function to be wrapped.
 * @param ttl - Optional time-to-live for the cached entry in seconds. If not provided, the default TTL from CacheService is used.
 * @returns A new resolver function that implements the caching logic.
 */
const withCache = (keyGenerator, resolver, ttl) => {
    return async (parent, args, context, info) => {
        const key = keyGenerator(parent, args, context, info);
        return CacheService_js_1.cacheService.getOrSet(key, () => resolver(parent, args, context, info), ttl);
    };
};
exports.withCache = withCache;
/**
 * Generates a consistent cache key for lists with filtering, sorting, and pagination.
 *
 * @param prefix - Prefix for the cache key (e.g., 'entities')
 * @param params - Object containing filter, sort, and pagination parameters
 * @returns A string cache key
 */
const listCacheKey = (prefix, params) => {
    const sortedParams = Object.keys(params)
        .sort()
        .reduce((acc, key) => {
        // Filter out undefined/null/empty values to keep keys canonical? 
        // Or keep them valid? Keeping them ensures strict match.
        // But let's just JSON.stringify the sorted object.
        acc[key] = params[key];
        return acc;
    }, {});
    return `${prefix}:${JSON.stringify(sortedParams)}`;
};
exports.listCacheKey = listCacheKey;
