from typing import Protocol, Iterable, Optional
from graphrag.topology.router import RegionRoute

class GraphStoreRegioned(Protocol):
  def route(self, data_class: str, preferred_region: str) -> RegionRoute: ...
  def upsert_triplets(self, route: RegionRoute, triplets: Iterable[object]) -> None: ...
  def query_subgraph(self, route: RegionRoute, query: str) -> object: ...
