import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

// Configuration
const REQUIRED_ARTIFACTS = [
    'artifacts/trust/trust_state.json',
    'artifacts/attestations/verification_result.json',
]; // Paths relative to repo root
const OUTPUT_FILE = 'artifacts/risk/risk_metrics.json';
const MAX_LIABILITY_PER_VIOLATION = 10000; // USD

function computeRiskMetrics() {
    let integrityScore = 100;
    let integrityViolations = 0;

    // 1. Integrity Exposure (Based on Trust State)
    let trustState = 'UNKNOWN';
    try {
        if (fs.existsSync('artifacts/trust/trust_state.json')) {
            const trustData = JSON.parse(fs.readFileSync('artifacts/trust/trust_state.json', 'utf-8'));
            trustState = trustData.status; // GREEN, AMBER, RED

            if (trustState === 'RED') {
                integrityScore = 0;
                integrityViolations += 1; // Major violation
            } else if (trustState === 'AMBER') {
                integrityScore = 50;
                // Warning, not necessarily a violation of integrity but degradation
            }
        } else {
            integrityScore = 0;
            integrityViolations += 1; // Missing proof of trust
            trustState = 'MISSING';
        }
    } catch (e) {
        integrityScore = 0;
        integrityViolations += 1;
        trustState = 'ERROR';
    }

    // 2. Auditability Exposure (Based on Artifact Presence)
    let missingArtifacts = 0;
    let totalArtifacts = REQUIRED_ARTIFACTS.length;
    for (const artifact of REQUIRED_ARTIFACTS) {
        if (!fs.existsSync(artifact)) {
            missingArtifacts++;
        }
    }
    const evidenceCompleteness = totalArtifacts > 0
        ? ((totalArtifacts - missingArtifacts) / totalArtifacts) * 100
        : 100;


    // 3. Availability Exposure (Placeholder / Mock for this proof as we don't have live ops data in CI build)
    // In a real system, this would consume active incident reports from Ops artifacts.
    // We assume 100 if no 'artifacts/ops/incidents.json' exists for now.
    const availabilityCompliance = 100;
    const activeIncidents = 0;


    const metrics = {
        schema_version: "1.0.0",
        timestamp: new Date().toISOString(),
        context: {
            commit_sha: process.env.GITHUB_SHA || 'dev',
            trust_state: trustState,
            run_id: process.env.GITHUB_RUN_ID || 'local'
        },
        metrics: {
            integrity_exposure: {
                score: integrityScore,
                violations: integrityViolations,
                max_exposure_usd: integrityViolations * MAX_LIABILITY_PER_VIOLATION
            },
            availability_exposure: {
                uptime_sla_compliance: availabilityCompliance,
                active_incidents: activeIncidents
            },
            auditability_exposure: {
                evidence_completeness: evidenceCompleteness,
                missing_artifacts: missingArtifacts
            }
        },
        // Signature placeholder (would be signed by CI key)
        signature: {
            value: "ci-autogenerated-signature-placeholder",
            key_id: "ci-runner-key-1"
        }
    };

    return metrics;
}

const metrics = computeRiskMetrics();
const outDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

// Deterministic Output: Sort keys if necessary, but JSON.stringify order is consistent for same object logic usually.
// For strict safety we could sort.
fs.writeFileSync(OUTPUT_FILE, JSON.stringify(metrics, null, 2));

console.log("Risk Metrics Computed:");
console.log(JSON.stringify(metrics.metrics, null, 2));

// If integrity is 0 (RED), we still produce metrics, but CI might choose to fail elsewhere. 
// This script acts as a reporter.
process.exit(0);
