#!/usr/bin/env bash
# Required Checks Discovery Automation
#
# This script discovers and documents the required status checks configured
# on branch protection rules via the GitHub API.
#
# Part of the subsumption-bundle-framework initiative.
#
# Usage:
#   ./scripts/ci/discover-required-checks.sh
#   ./scripts/ci/discover-required-checks.sh --branch main
#   ./scripts/ci/discover-required-checks.sh --output ci/required_checks.todo.md
#   ./scripts/ci/discover-required-checks.sh --ci  # Non-interactive mode

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration
BRANCH="${BRANCH:-main}"
OUTPUT_FILE="${OUTPUT_FILE:-$PROJECT_ROOT/ci/required_checks.todo.md}"
CI_MODE=false
VERBOSE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --branch) BRANCH="$2"; shift 2 ;;
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --ci) CI_MODE=true; shift ;;
        --verbose|-v) VERBOSE=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

log() {
    if [[ "$VERBOSE" == "true" ]]; then
        echo "$1"
    fi
}

# Check gh CLI is available
if ! command -v gh &> /dev/null; then
    echo "ERROR: GitHub CLI (gh) is not installed"
    echo "Install from: https://cli.github.com/"
    exit 1
fi

# Check authentication
if ! gh auth status &> /dev/null; then
    echo "ERROR: Not authenticated with GitHub CLI"
    echo "Run: gh auth login"
    exit 1
fi

log "Discovering required checks for branch: $BRANCH"

# Get repo info
REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || echo "")
if [[ -z "$REPO" ]]; then
    echo "ERROR: Could not determine repository"
    exit 1
fi

log "Repository: $REPO"

# Fetch branch protection settings
PROTECTION_DATA=$(gh api "repos/$REPO/branches/$BRANCH/protection/required_status_checks" 2>/dev/null || echo '{"error": true}')

if echo "$PROTECTION_DATA" | jq -e '.error' &>/dev/null; then
    echo "WARNING: Could not fetch branch protection (may require admin access)"
    echo "Using cached data if available..."

    if [[ -f "$OUTPUT_FILE" ]]; then
        echo "Existing file found: $OUTPUT_FILE"
        exit 0
    else
        echo "No existing file found"
        exit 1
    fi
fi

# Extract required checks
STRICT=$(echo "$PROTECTION_DATA" | jq -r '.strict // false')
CHECKS=$(echo "$PROTECTION_DATA" | jq -r '.checks // []')
CONTEXTS=$(echo "$PROTECTION_DATA" | jq -r '.contexts // []')

# Generate markdown report
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

cat > "$OUTPUT_FILE" << EOF
# Required Checks Discovery

**Status:** ✅ COMPLETED ($TIMESTAMP)
**Last Updated:** $TIMESTAMP
**Automation:** scripts/ci/discover-required-checks.sh

## Current Branch Protection Configuration

The following required status checks are configured on the \`$BRANCH\` branch:

| Check Name | App ID | Status |
|------------|--------|--------|
EOF

# Parse checks (new format)
if [[ $(echo "$CHECKS" | jq 'length') -gt 0 ]]; then
    echo "$CHECKS" | jq -r '.[] | "| \(.context) | \(.app_id // "N/A") | ✅ Active |"' >> "$OUTPUT_FILE"
fi

# Parse contexts (legacy format)
if [[ $(echo "$CONTEXTS" | jq 'length') -gt 0 ]]; then
    echo "$CONTEXTS" | jq -r '.[] | "| \(.) | N/A | ✅ Active |"' >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

## Discovery Method

Retrieved via GitHub API:
\`\`\`bash
gh api repos/$REPO/branches/$BRANCH/protection/required_status_checks
\`\`\`

## Configuration Details

- **Strict mode:** $STRICT (requires branches to be up to date before merging)
- **Total checks:** $(echo "$CHECKS" | jq 'length') + $(echo "$CONTEXTS" | jq 'length') contexts

## Related Workflows

EOF

# Find related workflow files
for workflow in "$PROJECT_ROOT"/.github/workflows/*.yml; do
    if [[ -f "$workflow" ]]; then
        workflow_name=$(basename "$workflow")
        echo "- \`.github/workflows/$workflow_name\`" >> "$OUTPUT_FILE"
    fi
done | head -10 >> "$OUTPUT_FILE" 2>/dev/null || true

cat >> "$OUTPUT_FILE" << EOF

## Verification

To verify these checks match your workflows:

\`\`\`bash
# List all workflow job names
grep -h "^  [a-z].*:" .github/workflows/*.yml | sed 's/://g' | sort -u

# Compare with required checks
gh api repos/$REPO/branches/$BRANCH/protection/required_status_checks | jq '.checks[].context'
\`\`\`

## Future Considerations

If additional checks need to be added:
1. Create the workflow job in the appropriate workflow file
2. Ensure the job name matches exactly what will be required
3. Update branch protection via GitHub UI or API
4. Re-run this script to update documentation

---

*Generated by discover-required-checks.sh*
EOF

echo ""
echo "=== Required Checks Discovery ==="
echo "Branch: $BRANCH"
echo "Repository: $REPO"
echo "Output: $OUTPUT_FILE"
echo ""
echo "Checks found:"
echo "$CHECKS" | jq -r '.[] | "  - \(.context)"' 2>/dev/null || true
echo "$CONTEXTS" | jq -r '.[] | "  - \(.)"' 2>/dev/null || true
echo ""
echo "[SUCCESS] Required checks documentation updated"
