import fs from 'fs';
import path from 'path';
import { ConstraintSystem } from '../../server/src/autonomous/constraint-system.js';
import { InfraResilienceSimulator } from '../../server/src/autonomous/infra-resilience.js';
import { CapitalAllocationEngine } from '../../server/src/autonomous/capital-efficiency.js';
import { DecisionRightsEngine } from '../../server/src/autonomous/decision-rights.js';

const EVIDENCE_DIR = path.resolve('evidence');
const METRICS_DIR = path.resolve('metrics');
const INFRA_DIR = path.resolve('infra/worst_case_models');
const ORG_DIR = path.resolve('org');

[EVIDENCE_DIR, METRICS_DIR, INFRA_DIR, ORG_DIR].forEach(d => {
    if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
});

async function main() {
  const constraints = new ConstraintSystem(console);

  // 1. Resilience Evidence
  const infraSim = new InfraResilienceSimulator(constraints, console);
  const infraProposal = {
    resourceType: 'Redis Cache',
    action: 'scale_down' as const,
    costImpactUsd: -200,
    reliabilityImpact: -0.1
  };
  const infraResult = infraSim.evaluateProposal(infraProposal);

  fs.writeFileSync(
    path.join(EVIDENCE_DIR, 'resilience_decisions.json'),
    JSON.stringify([infraResult], null, 2)
  );

  // 2. Capital ROI Metrics
  const capEngine = new CapitalAllocationEngine(constraints, console);
  const investment = {
    name: 'Autonomous Testing Cluster',
    costUsd: 1000,
    velocityValue: 5000 // High value from speed
  };
  const capResult = capEngine.evaluateInvestment(investment);

  fs.writeFileSync(
    path.join(METRICS_DIR, 'capital_roi.json'),
    JSON.stringify([capResult], null, 2)
  );

  // 3. Worst Case Models
  fs.writeFileSync(
    path.join(INFRA_DIR, 'README.md'),
    `# Worst-Case Infrastructure Models\n\nGenerated by InfraResilienceSimulator.\nLast Run: ${new Date().toISOString()}`
  );

  // 4. Decision Rights
  const decisionEngine = new DecisionRightsEngine(console);
  decisionEngine.evaluateRights({
      agentId: 'Jules-Release-Bot',
      successfulDeploys: 55,
      incidentsCaused: 0,
      lastIncident: null
  });

  fs.writeFileSync(
      path.join(ORG_DIR, 'decision_rights_state.json'),
      JSON.stringify(decisionEngine.exportState(), null, 2)
  );
  fs.writeFileSync(
      path.join(ORG_DIR, 'DYNAMIC_GOVERNANCE.md'),
      `# Dynamic Governance State\n\nGenerated by DecisionRightsEngine.\nLast Run: ${new Date().toISOString()}`
  );

  console.log('Generated autonomous evidence.');
}

main().catch(console.error);
