"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
const constraint_system_js_1 = require("../../server/src/autonomous/constraint-system.js");
const infra_resilience_js_1 = require("../../server/src/autonomous/infra-resilience.js");
const capital_efficiency_js_1 = require("../../server/src/autonomous/capital-efficiency.js");
const decision_rights_js_1 = require("../../server/src/autonomous/decision-rights.js");
const EVIDENCE_DIR = path_1.default.resolve('evidence');
const METRICS_DIR = path_1.default.resolve('metrics');
const INFRA_DIR = path_1.default.resolve('infra/worst_case_models');
const ORG_DIR = path_1.default.resolve('org');
[EVIDENCE_DIR, METRICS_DIR, INFRA_DIR, ORG_DIR].forEach(d => {
    if (!fs_1.default.existsSync(d))
        fs_1.default.mkdirSync(d, { recursive: true });
});
async function main() {
    const constraints = new constraint_system_js_1.ConstraintSystem(console);
    // 1. Resilience Evidence
    const infraSim = new infra_resilience_js_1.InfraResilienceSimulator(constraints, console);
    const infraProposal = {
        resourceType: 'Redis Cache',
        action: 'scale_down',
        costImpactUsd: -200,
        reliabilityImpact: -0.1
    };
    const infraResult = infraSim.evaluateProposal(infraProposal);
    fs_1.default.writeFileSync(path_1.default.join(EVIDENCE_DIR, 'resilience_decisions.json'), JSON.stringify([infraResult], null, 2));
    // 2. Capital ROI Metrics
    const capEngine = new capital_efficiency_js_1.CapitalAllocationEngine(constraints, console);
    const investment = {
        name: 'Autonomous Testing Cluster',
        costUsd: 1000,
        velocityValue: 5000 // High value from speed
    };
    const capResult = capEngine.evaluateInvestment(investment);
    fs_1.default.writeFileSync(path_1.default.join(METRICS_DIR, 'capital_roi.json'), JSON.stringify([capResult], null, 2));
    // 3. Worst Case Models
    fs_1.default.writeFileSync(path_1.default.join(INFRA_DIR, 'README.md'), `# Worst-Case Infrastructure Models\n\nGenerated by InfraResilienceSimulator.\nLast Run: ${new Date().toISOString()}`);
    // 4. Decision Rights
    const decisionEngine = new decision_rights_js_1.DecisionRightsEngine(console);
    decisionEngine.evaluateRights({
        agentId: 'Jules-Release-Bot',
        successfulDeploys: 55,
        incidentsCaused: 0,
        lastIncident: null
    });
    fs_1.default.writeFileSync(path_1.default.join(ORG_DIR, 'decision_rights_state.json'), JSON.stringify(decisionEngine.exportState(), null, 2));
    fs_1.default.writeFileSync(path_1.default.join(ORG_DIR, 'DYNAMIC_GOVERNANCE.md'), `# Dynamic Governance State\n\nGenerated by DecisionRightsEngine.\nLast Run: ${new Date().toISOString()}`);
    console.log('Generated autonomous evidence.');
}
main().catch(console.error);
