#!/bin/bash
# Runner Saturation Policy - Auto-Recovery Automation
#
# Monitors CI queue depth and automatically takes action when gridlock is detected:
# 1. Detects saturation thresholds (>100 queued = elevated, >200 = critical)
# 2. Auto-enables MERGE_SURGE mode (if not already enabled)
# 3. Auto-cancels archived workflow runs (preserves new 8-workflow system)
# 4. Posts status update to docs/ci/recovery-status-update.md
#
# Usage: bash scripts/ci/runner-saturation-policy.sh
# Cron: */5 * * * * (every 5 minutes)

set -euo pipefail

# Thresholds
ELEVATED_THRESHOLD=100
CRITICAL_THRESHOLD=200
GRIDLOCK_THRESHOLD=300

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Status file
STATUS_FILE="docs/ci/recovery-status-update.md"

log() {
  echo -e "${2:-$NC}$1${NC}"
}

update_status_file() {
  local status="$1"
  local queue_depth="$2"
  local in_progress="$3"
  local actions_taken="$4"

  cat > "$STATUS_FILE" <<EOF
# CI Recovery Status

**Last Updated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Current Status: $status

- **Queued workflows**: $queue_depth
- **In-progress workflows**: $in_progress
- **MERGE_SURGE mode**: $(gh variable get MERGE_SURGE --repo BrianCLong/summit 2>/dev/null || echo "unknown")

## Actions Taken

$actions_taken

## Monitoring

\`\`\`bash
# Check current status
bash scripts/ci/monitor-runner-capacity.sh

# Manual intervention (if needed)
bash scripts/ci/cancel-archived-workflow-runs.sh
\`\`\`

---
*Auto-generated by runner-saturation-policy.sh*
EOF
}

main() {
  log "\n=== Runner Saturation Policy ===" "$BLUE"
  log "Timestamp: $(date)" "$BLUE"

  # Get queue metrics
  QUEUED=$(gh run list --status queued --limit 500 --json databaseId --jq 'length')
  IN_PROGRESS=$(gh run list --status in_progress --limit 100 --json databaseId --jq 'length')

  log "\nQueue depth: $QUEUED" "$BLUE"
  log "In progress: $IN_PROGRESS" "$BLUE"

  # Determine status
  STATUS="HEALTHY"
  ACTIONS=""

  if [ "$QUEUED" -lt "$ELEVATED_THRESHOLD" ]; then
    STATUS="HEALTHY"
    log "\n✅ Status: HEALTHY" "$GREEN"
    ACTIONS="- No intervention required"
  elif [ "$QUEUED" -lt "$CRITICAL_THRESHOLD" ]; then
    STATUS="ELEVATED"
    log "\n⚠️  Status: ELEVATED" "$YELLOW"
    ACTIONS="- Monitoring elevated queue depth\n- No automatic intervention yet"
  elif [ "$QUEUED" -lt "$GRIDLOCK_THRESHOLD" ]; then
    STATUS="CRITICAL"
    log "\n🚨 Status: CRITICAL" "$RED"

    ACTIONS="### Critical Actions Taken:\n\n"

    # Action 1: Enable MERGE_SURGE mode
    log "\n🔧 Enabling MERGE_SURGE mode..." "$YELLOW"
    if gh variable set MERGE_SURGE --body "true" --repo BrianCLong/summit 2>/dev/null; then
      log "✅ MERGE_SURGE mode enabled" "$GREEN"
      ACTIONS+="1. ✅ Enabled MERGE_SURGE mode (skips 60-75% of heavy jobs)\n"
    else
      log "⚠️  Failed to enable MERGE_SURGE mode (may already be enabled)" "$YELLOW"
      ACTIONS+="1. ℹ️  MERGE_SURGE mode already enabled\n"
    fi

    # Action 2: Cancel archived workflow runs
    log "\n🚫 Canceling archived workflow runs..." "$YELLOW"
    CANCEL_OUTPUT=$(bash scripts/ci/cancel-archived-workflow-runs.sh 2>&1 | tail -10)
    CANCELLED_COUNT=$(echo "$CANCEL_OUTPUT" | grep -o "Canceled [0-9]* archived" | grep -o "[0-9]*" || echo "0")

    if [ "$CANCELLED_COUNT" -gt 0 ]; then
      log "✅ Cancelled $CANCELLED_COUNT archived workflow runs" "$GREEN"
      ACTIONS+="2. ✅ Cancelled $CANCELLED_COUNT archived workflow runs\n"
    else
      log "ℹ️  No archived workflow runs to cancel" "$BLUE"
      ACTIONS+="2. ℹ️  No archived workflow runs to cancel\n"
    fi

    ACTIONS+="3. 📊 Monitoring for recovery\n"

  else
    STATUS="GRIDLOCK"
    log "\n❌ Status: GRIDLOCK" "$RED"

    ACTIONS="### GRIDLOCK Actions Taken:\n\n"

    # Action 1: Enable MERGE_SURGE mode
    log "\n🔧 Enabling MERGE_SURGE mode..." "$YELLOW"
    if gh variable set MERGE_SURGE --body "true" --repo BrianCLong/summit 2>/dev/null; then
      log "✅ MERGE_SURGE mode enabled" "$GREEN"
      ACTIONS+="1. ✅ Enabled MERGE_SURGE mode\n"
    else
      log "⚠️  MERGE_SURGE mode already enabled" "$YELLOW"
      ACTIONS+="1. ℹ️  MERGE_SURGE mode already enabled\n"
    fi

    # Action 2: Cancel ALL queued runs (emergency)
    log "\n🚫 EMERGENCY: Canceling ALL queued runs..." "$RED"
    CANCEL_OUTPUT=$(bash scripts/ci/cancel-queued-runs.sh 2>&1 | tail -10)
    CANCELLED_COUNT=$(echo "$CANCEL_OUTPUT" | grep -o "Canceled [0-9]*" | grep -o "[0-9]*" || echo "0")

    log "✅ Cancelled $CANCELLED_COUNT queued runs" "$GREEN"
    ACTIONS+="2. ✅ EMERGENCY: Cancelled ALL $CANCELLED_COUNT queued runs\n"
    ACTIONS+="3. 🚨 MANUAL INTERVENTION RECOMMENDED\n"
    ACTIONS+="4. 📋 See docs/ci/EMERGENCY-RECOVERY-INSTRUCTIONS.md\n"
  fi

  # Update status file
  log "\n📝 Updating status file: $STATUS_FILE" "$BLUE"
  update_status_file "$STATUS" "$QUEUED" "$IN_PROGRESS" "$ACTIONS"

  log "\n=== Policy Execution Complete ===" "$BLUE"
  log "Status: $STATUS" "$BLUE"
  log "Next check: Run this script again in 5 minutes\n" "$BLUE"
}

main "$@"
