import type { Config } from 'jest';

const gaVerifyMode = process.env.GA_VERIFY_MODE === 'true';

const coverageThreshold = {
  global: {
    branches: 80,
    functions: 80,
    lines: 80,
    statements: 80,
  },
};

// In GA verify mode, use minimal ignore patterns since testMatch is explicit
// In normal mode, use comprehensive patterns to exclude ESM-incompatible tests
const testPathIgnorePatterns = gaVerifyMode
  ? ['/node_modules/', '/dist/']
  : [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/playwright-tests/',
    // Skip integration and e2e tests that require real backends
    '.*\\.int\\.test\\.ts$',
    '.*\\.integration\\.test\\.ts$',
    '.*\\.e2e\\.test\\.ts$',
    '.*/integration/.*\\.test\\.ts$',
  ];

const config: Config = {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  setupFiles: ['<rootDir>/tests/setup/env.ts'],
  setupFilesAfterEnv: [
    '<rootDir>/tests/setup/jest.setup.cjs',
    // 'jest-extended/all',
  ],
  testMatch: gaVerifyMode
    ? [
      '<rootDir>/src/services/__tests__/GraphRAGService.test.ts',
      '<rootDir>/src/provenance-integrity-gateway/__tests__/ProvenanceIntegrityGateway.test.ts',
      '<rootDir>/src/db/__tests__/tickets.test.ts',
    ]
    : [
      '<rootDir>/tests/**/*.test.ts',
      '<rootDir>/src/tests/**/*.test.ts',
      '<rootDir>/src/**/__tests__/**/*.test.ts',
    ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/playwright-tests/',
    // Skip integration and e2e tests that require real backends
    '.*\\.int\\.test\\.ts$',
    '.*\\.integration\\.test\\.ts$',
    '.*\\.e2e\\.test\\.ts$',
    '.*/integration/.*\\.test\\.ts$',
    // Skip tests with CommonJS require() that don't work in ESM
    'src/graphql/plugins/__tests__/',
    'src/conductor/api/__tests__/',
    'src/conductor/config/__tests__/',
    'src/conductor/premium-routing/__tests__/',
    'src/conductor/scheduling/__tests__/',
    'src/conductor/__tests__/',
    'src/analytics/',
    'src/billing/',
    'src/auth-sso/',
    'src/auth/sso/__tests__/',
    'src/aurelius/',
    'src/chatops/',
    'src/compliance/__tests__/',
    'src/connectors/__tests__/',
    // 'src/data-residency/__tests__/',
    // 'src/db/__tests__/',
    'src/entities/comments/__tests__/',
    'src/evidence/__tests__/',
    'src/extensions/__tests__/',
    'src/feature-flags/__tests__/',
    'src/federation/__tests__/',
    'src/graph/__tests__/',
    'src/graphql/services/__tests__/',
    'src/ingest/__tests__/',
    'src/intel/cti/__tests__/',
    'src/lib/resources/__tests__/',
    // 'src/maestro/__tests__/',
    'src/audit/__tests__/',
    'src/__tests__/fuzz',
    'src/__tests__/risk/',
    'src/backpressure/__tests__/',
    'src/maestro/coordination/__tests__/',
    'src/maestro/executors/__tests__/',
    'src/maestro/mcp/__tests__/',
    'src/maestro/pipelines/__tests__/',
    'src/maestro/runs/__tests__/',
    'src/memory/__tests__/',
    'src/metering/__tests__/',
    'src/nlp/__tests__/',
    'src/observability/__tests__/',
    'src/pii/__tests__/',
    'src/provenance/__tests__/',
    'src/queue/__tests__/',
    'src/replay/__tests__/',
    'src/repos/__tests__/',
    'src/retrieval/__tests__/',
    'src/routes/__tests__/',
    'src/securiteyes/',
    'src/security/tenant-simulation/__tests__/',
    'src/summitsight/__tests__/',
    'src/tests/', // TODO: Enable after fixing ESM issues in legacy tests
    'src/trust-center/__tests__/',
    // 'src/utils/__tests__/',
    'src/webhooks/__tests__/',
    'src/reporting/__tests__/',
    'src/services/reporting/__tests__/',
    'src/logging/__tests__/',
    'src/jobs/__tests__/',
    'tests/', // TODO: Enable after fixing ESM issues in legacy tests
  ],
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
  moduleNameMapper: {
    '.*governance-service.*$': '<rootDir>/tests/mocks/agent-governance-service.ts',
    '.*provenance/ledger.*$': '<rootDir>/tests/mocks/provenance-ledger.ts',
    '^jsdom$': '<rootDir>/tests/mocks/jsdom.ts',
    '.*lib/telemetry/diagnostic-snapshotter(\\.js)?$': '<rootDir>/tests/mocks/diagnostic-snapshotter.ts',
    '.*DeterministicExportService(\\.js)?$': '<rootDir>/tests/mocks/deterministic-export-service.ts',
    '.*PolicyEngine(\\.js)?$': '<rootDir>/tests/mocks/policy-engine.ts',
    '.*prompts/registry(\\.js)?$': '<rootDir>/tests/mocks/prompts-registry.ts',
    '.*insights/engagementCascade(\\.js)?$': '<rootDir>/tests/mocks/engagement-cascade.ts',
    '.*packages/shared/provenance(\\.js)?$': '<rootDir>/tests/mocks/provenance.ts',
    '.*telemetry/comprehensive-telemetry(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*lib/telemetry/anomaly-detector(\\.js)?$': '<rootDir>/tests/mocks/anomaly-detector.ts',
    '.*config/logger(\\.[a-zA-Z]+)?$': '<rootDir>/tests/mocks/config-logger.ts',
    '.*utils/logger(\\.js)?$': '<rootDir>/tests/mocks/utils-logger.ts',
    '.*metrics/dbMetrics(\\.js)?$': '<rootDir>/tests/mocks/db-metrics.ts',
    '.*workers/eventBus(\\.js)?$': '<rootDir>/tests/mocks/eventBus.ts',
    '.*health/aggregator(\\.js)?$': '<rootDir>/tests/mocks/health-aggregator.ts',
    '^node-fetch$': '<rootDir>/tests/mocks/node-fetch.ts',
    '^ioredis$': '<rootDir>/tests/mocks/ioredis.ts',
    '^pg-boss$': '<rootDir>/tests/mocks/pg-boss.ts',
    '^neo4j-driver$': '<rootDir>/tests/mocks/neo4j-driver.ts',
    '.*db/neo4j(\\.js)?$': '<rootDir>/tests/mocks/db-neo4j.ts',
    '^pino$': '<rootDir>/tests/mocks/pino.ts',
    '^pino-http$': '<rootDir>/tests/mocks/pino-http.cjs',
    '^pg$': '<rootDir>/tests/mocks/pg.ts',
    '^uWebSockets\\.js$': '<rootDir>/tests/mocks/uWebSockets.js',
    '^bullmq$': '<rootDir>/tests/mocks/bullmq.ts',
    '^kafkajs$': '<rootDir>/tests/mocks/kafkajs.ts',
    '.*middleware/TieredRateLimitMiddleware(\\.js)?$': '<rootDir>/tests/mocks/tiered-rate-limiter.ts',
    '.*backpressure/BackpressureController(\\.js)?$': '<rootDir>/tests/mocks/backpressure-controller.ts',
    '^jsonwebtoken$': '<rootDir>/tests/mocks/jsonwebtoken.ts',
    '^isomorphic-dompurify$': '<rootDir>/tests/mocks/isomorphic-dompurify.ts',
    '.*services/rag(\\.js)?$': '<rootDir>/tests/mocks/rag.ts',
    '.*middleware/rateLimit(\\.js)?$': '<rootDir>/tests/mocks/rateLimit.ts',
    '.*middleware/audit-logger(\\.js)?$': '<rootDir>/tests/mocks/audit-logger.cjs',
    '.*security/zero-trust/siem/audit-logger(\\.js)?$': '<rootDir>/tests/mocks/siem-audit-logger.ts',
    '.*utils/audit(\\.js)?$': '<rootDir>/tests/mocks/audit.ts',
    '.*graphql/schema\\.collab(\\.js)?$': '<rootDir>/tests/mocks/schema-collab.ts',
    '.*graphql/resolvers\\.collab(\\.js)?$': '<rootDir>/tests/mocks/resolvers-collab.ts',
    '.*workers/trustScoreWorker(\\.js)?$': '<rootDir>/tests/mocks/trust-score-worker.ts',
    '.*workers/retentionWorker(\\.js)?$': '<rootDir>/tests/mocks/retention-worker.ts',
    '.*ingest/stream(\\.js)?$': '<rootDir>/tests/mocks/stream-ingest.ts',
    '.*webhooks/webhook.worker(\\.js)?$': '<rootDir>/tests/mocks/webhook-worker.ts',
    '.*graphql/plugins/rateLimitAndCache(\\.js)?$': '<rootDir>/tests/mocks/rate-limit-cache.ts',
    '.*analytics/telemetry/TelemetryService(\\.js)?$': '<rootDir>/tests/mocks/telemetry-service.ts',
    '.*scripts/maintenance(\\.js)?$': '<rootDir>/tests/mocks/maintenance.ts',
    '^argon2$': '<rootDir>/tests/mocks/argon2.ts',
    '^pkcs11js$': '<rootDir>/tests/mocks/pkcs11js.js',
    '^graphql-iso-date$': '<rootDir>/tests/mocks/graphql-iso-date.cjs',
    '^pptxgenjs$': '<rootDir>/tests/mocks/pptxgenjs.ts',
    // '.*config/database(\\.js)?$': '<rootDir>/tests/mocks/db-config.ts',
    '^html-to-text$': '<rootDir>/tests/mocks/html-to-text.ts',
    '^mjml$': '<rootDir>/tests/mocks/mjml.ts',
    '.*TemplateRenderer.*': '<rootDir>/tests/mocks/template-renderer.ts',
    '.*monitoring/metrics(\\.js)?$': '<rootDir>/tests/mocks/metrics.ts',

    '@intelgraph/feature-flags': '<rootDir>/tests/mocks/feature-flags.ts',
    '@intelgraph/attack-surface': '<rootDir>/tests/mocks/attack-surface.ts',
    '@packages/cache': '<rootDir>/tests/mocks/cache.ts',
    '.*security/secret-audit-logger(\\.js)?$': '<rootDir>/tests/mocks/secret-audit-logger.ts',
    '^python-shell$': '<rootDir>/tests/mocks/python-shell.ts',
    '^axios$': '<rootDir>/tests/mocks/axios.ts',
    '^openai$': '<rootDir>/tests/mocks/openai.ts',
    '.*observability/tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*observability/tracer(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*observability/telemetry(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*middleware/observability/otel-tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*/otel-tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*/otel(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*services/IntelGraphService(\\.js)?$': '<rootDir>/tests/mocks/intelgraph-service.ts',
    '.*services/CIBDetectionService(\\.js)?$': '<rootDir>/tests/mocks/cib-detection-service.ts',
    '.*db/redis(\\.js)?$': '<rootDir>/tests/mocks/db-redis.ts',
    '.*graph/neo4j(\\.js)?$': '<rootDir>/tests/mocks/graph-neo4j.ts',
    '.*auth/multi-tenant-rbac(\\.js)?$': '<rootDir>/tests/mocks/multi-tenant-rbac.ts',
    '.*services/DoclingService(\\.js)?$': '<rootDir>/tests/mocks/docling-service.ts',
    '.*db/repositories/doclingRepository(\\.js)?$': '<rootDir>/tests/mocks/docling-repository.ts',
    '.*provenance/ledger(\\.js)?$': '<rootDir>/tests/mocks/provenance-ledger.ts',
    '.*packages/osint-collector/src/collectors/SimpleFeedCollector(\\.js)?$': '<rootDir>/tests/mocks/osint-collector.ts',
    '.*packages/osint-collector/src/types/index(\\.js)?$': '<rootDir>/tests/mocks/osint-collector-types.ts',
    '^graphql-query-complexity$': '<rootDir>/tests/mocks/graphql-query-complexity.ts',
    '^mysql2/promise$': '<rootDir>/tests/mocks/mysql2.ts',
    '@intelgraph/post-quantum-crypto': '<rootDir>/tests/mocks/post-quantum-crypto.ts',
    '@intelgraph/connector-sdk': '<rootDir>/tests/mocks/connector-sdk.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@tests/(.*)$': '<rootDir>/tests/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/__tests__/**',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
    '!src/tests/**',
    '!src/**/index.ts',
    '!src/config/**',
    '!src/database/**',
    '!src/generated/**',
    '!src/**/__mocks__/**',
    '!src/**/*.d.ts',
  ],
  coverageProvider: 'v8',
  // coverageThreshold,
  coverageReporters: ['text', 'lcov', 'cobertura', 'json-summary'],
  coverageDirectory: '<rootDir>/coverage',
  testTimeout: 30000,
  globalSetup: '<rootDir>/tests/setup/globalSetup.cjs',
  globalTeardown: '<rootDir>/tests/setup/globalTeardown.cjs',
  testResultsProcessor: 'jest-junit',
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>/test-results',
        outputName: 'junit.xml',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
        ancestorSeparator: ' › ',
        usePathForSuiteName: true,
      },
    ],
  ],
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  bail: false,
  errorOnDeprecated: true,
  transform: {
    '^.+\\.m?tsx?$': ['ts-jest', { useESM: true, tsconfig: 'tsconfig.test.json' }],
    '^.+\\.m?js$': ['ts-jest', { useESM: true, tsconfig: 'tsconfig.test.json' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@intelgraph|p-limit|yocto-queue|node-fetch|data-uri-to-buffer|fetch-blob|formdata-polyfill|pptxgenjs|jszip|@exodus/bytes|jsdom|html-encoding-sniffer|pg-boss|gaxios|gcp-metadata|@opentelemetry|pg)/)',
  ],
  maxWorkers: process.env.CI ? 2 : '50%',
  // Limit worker memory to prevent OOM in CI
  workerIdleMemoryLimit: process.env.CI ? '512MB' : undefined,
  // Open handle detection - helps identify hanging tests
  detectOpenHandles: process.env.JEST_DETECT_HANDLES === 'true',
  // Force exit after tests complete (CI safety net for orphan handles)
  forceExit: process.env.CI === 'true',
};

export default config;
