import type { Config } from 'jest';

const gaVerifyMode = process.env.GA_VERIFY_MODE === 'true';

const config: Config = {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  setupFiles: ['<rootDir>/tests/setup/env.ts'],
  setupFilesAfterEnv: [
    '<rootDir>/tests/setup/jest.setup.cjs',
    'jest-extended/all',
  ],
  testMatch: gaVerifyMode
    ? [
      '<rootDir>/src/services/__tests__/GraphRAGService.test.ts',
      '<rootDir>/src/provenance-integrity-gateway/__tests__/ProvenanceIntegrityGateway.test.ts',
    ]
    : [
      '<rootDir>/tests/**/*.test.ts',
      '<rootDir>/src/tests/**/*.test.ts',
      '<rootDir>/src/**/__tests__/**/*.test.ts',
    ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/playwright-tests/',
  ],
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
  moduleNameMapper: {
    '^jsdom$': '<rootDir>/tests/mocks/jsdom.ts',
    '.*diagnostic-snapshotter(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*DeterministicExportService(\\.js)?$': '<rootDir>/tests/mocks/deterministic-export-service.ts',
    '.*PolicyEngine(\\.js)?$': '<rootDir>/tests/mocks/policy-engine.ts',
    '.*prompts/registry(\\.js)?$': '<rootDir>/tests/mocks/prompts-registry.ts',
    '.*insights/engagementCascade(\\.js)?$': '<rootDir>/tests/mocks/engagement-cascade.ts',
    '.*packages/shared/provenance(\\.js)?$': '<rootDir>/tests/mocks/provenance.ts',
    '.*telemetry/comprehensive-telemetry(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*lib/telemetry/anomaly-detector(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*config/logger(\\.js)?$': '<rootDir>/tests/mocks/logger.cjs',
    '.*utils/logger(\\.js)?$': '<rootDir>/tests/mocks/logger.cjs',
    '.*metrics/dbMetrics(\\.js)?$': '<rootDir>/tests/mocks/db-metrics.ts',
    '.*workers/eventBus(\\.js)?$': '<rootDir>/tests/mocks/eventBus.ts',
    '.*health/aggregator(\\.js)?$': '<rootDir>/tests/mocks/health-aggregator.ts',
    '^node-fetch$': '<rootDir>/tests/mocks/node-fetch.ts',
    '^ioredis$': '<rootDir>/tests/mocks/ioredis.ts',
    '^pg-boss$': '<rootDir>/tests/mocks/pg-boss.ts',
    '^neo4j-driver$': '<rootDir>/tests/mocks/neo4j-driver.ts',
    '.*db/neo4j(\\.js)?$': '<rootDir>/tests/mocks/db-neo4j.ts',
    '^pino$': '<rootDir>/tests/mocks/logger.cjs',
    '^pg$': '<rootDir>/tests/mocks/pg.ts',
    '^jsonwebtoken$': '<rootDir>/tests/mocks/jsonwebtoken.ts',
    '^isomorphic-dompurify$': '<rootDir>/tests/mocks/isomorphic-dompurify.ts',
    '.*services/rag(\\.js)?$': '<rootDir>/tests/mocks/rag.ts',
    '.*middleware/rateLimit(\\.js)?$': '<rootDir>/tests/mocks/rateLimit.ts',
    '.*middleware/audit-logger(\\.js)?$': '<rootDir>/tests/mocks/audit-logger.cjs',
    '.*security/zero-trust/siem/audit-logger(\\.js)?$': '<rootDir>/tests/mocks/siem-audit-logger.ts',
    '.*utils/audit(\\.js)?$': '<rootDir>/tests/mocks/audit.ts',
    '.*graphql/schema\\.collab(\\.js)?$': '<rootDir>/tests/mocks/schema-collab.ts',
    '.*graphql/resolvers\\.collab(\\.js)?$': '<rootDir>/tests/mocks/resolvers-collab.ts',
    '.*workers/trustScoreWorker(\\.js)?$': '<rootDir>/tests/mocks/trust-score-worker.ts',
    '.*workers/retentionWorker(\\.js)?$': '<rootDir>/tests/mocks/retention-worker.ts',
    '.*ingest/stream(\\.js)?$': '<rootDir>/tests/mocks/stream-ingest.ts',
    '.*webhooks/webhook.worker(\\.js)?$': '<rootDir>/tests/mocks/webhook-worker.ts',
    '.*graphql/plugins/rateLimitAndCache(\\.js)?$': '<rootDir>/tests/mocks/rate-limit-cache.ts',
    '.*analytics/telemetry/TelemetryService(\\.js)?$': '<rootDir>/tests/mocks/telemetry-service.ts',
    '.*scripts/maintenance(\\.js)?$': '<rootDir>/tests/mocks/maintenance.ts',
    '^argon2$': '<rootDir>/tests/mocks/argon2.ts',
    '^graphql-iso-date$': '<rootDir>/tests/mocks/graphql-iso-date.cjs',
    '^pptxgenjs$': '<rootDir>/tests/mocks/pptxgenjs.ts',
    '.*config/database(\\.js)?$': '<rootDir>/tests/mocks/db-config.ts',

    '@intelgraph/feature-flags': '<rootDir>/tests/mocks/feature-flags.ts',
    '@intelgraph/attack-surface': '<rootDir>/tests/mocks/attack-surface.ts',
    '@packages/cache': '<rootDir>/tests/mocks/cache.ts',
    '.*security/secret-audit-logger(\\.js)?$': '<rootDir>/tests/mocks/secret-audit-logger.ts',
    '^axios$': '<rootDir>/tests/mocks/axios.ts',
    '^openai$': '<rootDir>/tests/mocks/openai.ts',
    '.*observability/tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*observability/tracer(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*observability/telemetry(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*middleware/observability/otel-tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*/otel-tracing(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*/otel(\\.js)?$': '<rootDir>/tests/mocks/otel-service.ts',
    '.*services/IntelGraphService(\\.js)?$': '<rootDir>/tests/mocks/intelgraph-service.ts',
    '.*services/CIBDetectionService(\\.js)?$': '<rootDir>/tests/mocks/cib-detection-service.ts',
    '.*db/redis(\\.js)?$': '<rootDir>/tests/mocks/db-redis.ts',
    '.*graph/neo4j(\\.js)?$': '<rootDir>/tests/mocks/graph-neo4j.ts',
    '.*auth/multi-tenant-rbac(\\.js)?$': '<rootDir>/tests/mocks/multi-tenant-rbac.ts',
    '^kafkajs$': '<rootDir>/tests/mocks/kafkajs.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@tests/(.*)$': '<rootDir>/tests/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/__tests__/**',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
    '!src/tests/**',
    '!src/**/index.ts',
    '!src/config/**',
    '!src/database/**',
    '!src/generated/**',
    '!src/**/__mocks__/**',
    '!src/**/*.d.ts',
  ],
  coverageProvider: 'v8',
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
  },
  coverageReporters: ['text', 'lcov', 'cobertura'],
  coverageDirectory: '<rootDir>/coverage',
  testTimeout: 30000,
  globalSetup: '<rootDir>/tests/setup/globalSetup.cjs',
  globalTeardown: '<rootDir>/tests/setup/globalTeardown.cjs',
  testResultsProcessor: 'jest-junit',
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>/test-results',
        outputName: 'junit.xml',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
        ancestorSeparator: ' › ',
        usePathForSuiteName: true,
      },
    ],
  ],
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  bail: false,
  errorOnDeprecated: true,
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { useESM: true, tsconfig: 'tsconfig.test.json' }],
    '^.+\\.js$': ['ts-jest', { useESM: true, tsconfig: 'tsconfig.test.json' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(\\.pnpm|p-limit|yocto-queue|node-fetch|data-uri-to-buffer|fetch-blob|formdata-polyfill|pptxgenjs|jszip|@exodus/bytes|jsdom|html-encoding-sniffer|pg-boss|gaxios|gcp-metadata|@opentelemetry|pg)/)',
  ],
  maxWorkers: process.env.CI ? 2 : '50%',
  // Limit worker memory to prevent OOM in CI
  workerIdleMemoryLimit: process.env.CI ? '512MB' : undefined,
  // Open handle detection - helps identify hanging tests
  detectOpenHandles: process.env.JEST_DETECT_HANDLES === 'true',
  // Force exit after tests complete (CI safety net for orphan handles)
  forceExit: process.env.CI === 'true',
};

export default config;
