#!/bin/bash
if [[ "$*" == *"histogram_quantile"* ]] && [ "$SCENARIO" == "failure" ]; then
   echo '{"data":{"result":[{"value":[1234567890,"500"]}]}}'
elif [[ "$*" == *"status=~\"5..\""* ]] && [ "$SCENARIO" == "failure" ]; then
   echo '{"data":{"result":[{"value":[1234567890,"0.05"]}]}}'
elif [[ "$*" == *"pod_status_ready"* ]]; then
   echo '{"data":{"result":[{"value":[1234567890,"1"]}]}}'
else
   if [[ "$*" == *"histogram_quantile"* ]]; then
      echo '{"data":{"result":[{"value":[1234567890,"0.1"]}]}}'
   else
      echo '{"data":{"result":[{"value":[1234567890,"0"]}]}}'
   fi
fi
