import type { InsightRecord } from './InsightFeed';

interface InsightExplanationProps {
  insight: InsightRecord;
}

export function InsightExplanation({ insight }: InsightExplanationProps) {
  return (
    <section aria-label="insight-explanation">
      <h3>Why this insight matters</h3>
      <p>{insight.summary}</p>
      <p>Generated by: {insight.sourceEngine}</p>
    </section>
  );
}
