/**
 * This file was auto-generated by openapi-typescript.
 * Do not modify it by hand. Instead, modify the source OpenAPI specification.
 */

export interface paths {
  "/monitoring/metrics": {
    get: {
      responses: {
        /** Prometheus metrics text */
        200: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
  "/health": {
    get: {
      responses: {
        /** Healthy */
        200: {
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
        /** Unhealthy */
        503: {
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
      };
    };
  };
  "/api/maestro/route/preview": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            task?: string;
            context?: { [key: string]: any };
          };
        };
      };
      responses: {
        /** List of candidates */
        200: {
          content: {
            "application/json": components["schemas"]["RoutePreviewResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/route/execute": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            task?: string;
            selection?: string[];
          };
        };
      };
      responses: {
        /** Execution results */
        200: {
          content: {
            "application/json": components["schemas"]["RouteExecuteResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/web/interfaces": {
    get: {
      responses: {
        /** List of web interfaces */
        200: {
          content: {
            "application/json": components["schemas"]["WebInterfacesResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/web/run": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            task?: string;
            interfaces?: string[];
          };
        };
      };
      responses: {
        /** Orchestration results */
        200: {
          content: {
            "application/json": components["schemas"]["OrchestrateWebResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/budgets": {
    get: {
      responses: {
        /** Budget info */
        200: {
          content: {
            "application/json": components["schemas"]["BudgetsResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/policy/check": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            action?: string;
            payload?: { [key: string]: any };
          };
        };
      };
      responses: {
        /** Policy check result */
        200: {
          content: {
            "application/json": components["schemas"]["PolicyCheckResponse"];
          };
        };
      };
    };
  };
  "/api/maestro/runs": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            userId?: string;
            requestText?: string;
          };
        };
      };
      responses: {
        /** Run created */
        200: {
          content: {
            "application/json": { [key: string]: any };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    HealthStatus: {
      status?: "healthy" | "unhealthy";
      timestamp?: string;
      error?: string;
    };
    Candidate: {
      id?: string;
      type?: "model" | "web";
      name?: string;
      score?: number;
      cost_est?: number;
      latency_est_ms?: number;
      rationale?: string;
    };
    RoutePreviewResponse: {
      candidates?: components["schemas"]["Candidate"][];
    };
    RouteExecuteStep: {
      id?: string;
      source?: string;
      status?: "ok" | "fail";
      tokens?: number;
      cost?: number;
      citations?: {
        title?: string;
        url?: string;
      }[];
      elapsed_ms?: number;
    };
    RouteExecuteResponse: {
      runId?: string;
      steps?: components["schemas"]["RouteExecuteStep"][];
    };
    WebInterface: {
      id?: string;
      name?: string;
      category?: string;
      reliability?: number;
      cost_hint?: number;
    };
    WebInterfacesResponse: {
      items?: components["schemas"]["WebInterface"][];
    };
    OrchestrateWebResponse: {
      responses?: {
        id?: string;
        interface?: string;
        text?: string;
        citations?: {
          title?: string;
          url?: string;
        }[];
      }[];
      synthesized?: {
        text?: string;
        citations?: {
          title?: string;
          url?: string;
        }[];
      };
    };
    BudgetsResponse: {
      tier?: "bronze" | "silver" | "gold";
      remaining?: {
        tokens?: number;
        usd?: number;
      };
      burndown?: {
        t?: string;
        usd?: number;
        tokens?: number;
      }[];
    };
    PolicyCheckResponse: {
      allowed?: boolean;
      reason?: string;
      elevation?: {
        contact?: string;
        sla_hours?: number;
      };
    };
  };
}
