"use strict";
/**
 * This file was auto-generated by openapi-typescript.
 * Do not modify it by hand. Instead, modify the source OpenAPI specification.
 */
Object.defineProperty(exports, "__esModule", { value: true });
