name: CompanyOS API

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  companyos-api:
    uses: ./.github/workflows/companyos-service-template.yml
    with:
      service: companyos-api
      working-directory: companyos
    secrets: inherit
