name: Summit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: 9.12.0

      - name: Install dependencies (Global)
        run: |
          npm install -g typescript ts-node

      - name: Install Server Dependencies (Manual Workaround)
        working-directory: ./server
        run: |
          npm install --legacy-peer-deps --ignore-scripts --no-optional
          npm install --save-dev ts-jest --legacy-peer-deps --ignore-scripts --no-optional

      - name: Run Server Tests
        working-directory: ./server
        run: npm run test
        env:
          CI: true

  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20'
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Deps
        run: npm install --legacy-peer-deps --ignore-scripts --no-optional

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
