"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.validate = exports.parseConfigFile = exports.loadConfig = exports.Validate = exports.Load = void 0;
var parse_1 = require("./parse");
Object.defineProperty(exports, "Load", { enumerable: true, get: function () { return parse_1.loadConfig; } });
var validate_1 = require("./validate");
Object.defineProperty(exports, "Validate", { enumerable: true, get: function () { return validate_1.validate; } });
var parse_2 = require("./parse");
Object.defineProperty(exports, "loadConfig", { enumerable: true, get: function () { return parse_2.loadConfig; } });
Object.defineProperty(exports, "parseConfigFile", { enumerable: true, get: function () { return parse_2.parseConfigFile; } });
var validate_2 = require("./validate");
Object.defineProperty(exports, "validate", { enumerable: true, get: function () { return validate_2.validate; } });
