import { ManifestDocument } from './types.js';

export function createSummaryMarkdown(manifest: ManifestDocument): string {
  const lines: string[] = [];

  lines.push(`# Incident ${manifest.incident.id}`);
  lines.push('');
  lines.push(`- **Occurred At:** ${manifest.incident.occurredAt}`);
  lines.push(`- **Reported At:** ${manifest.incident.reportedAt}`);
  lines.push(`- **Severity:** ${manifest.incident.severity}`);
  lines.push('');
  lines.push('## Description');
  lines.push('');
  lines.push(manifest.incident.description);
  lines.push('');
  lines.push('## Artifacts');
  lines.push('');
  lines.push('| ID | Type | Checksum (SHA-256) | Validator | Redactions |');
  lines.push('| --- | --- | --- | --- | --- |');

  for (const artifact of manifest.artifacts) {
    const redactions = artifact.redactions.length
      ? artifact.redactions
          .map((record) => `${record.target}×${record.occurrences}`)
          .join('<br>')
      : 'None';
    lines.push(
      `| ${artifact.id} | ${artifact.type} | \`${artifact.checksum}\` | ${artifact.validation.validator} | ${redactions} |`
    );
  }

  lines.push('');
  lines.push('## Validation Notes');
  lines.push('');
  for (const artifact of manifest.artifacts) {
    lines.push(`### ${artifact.id}`);
    lines.push('');
    lines.push(`- **Status:** ${artifact.validation.status}`);
    for (const detail of artifact.validation.details) {
      lines.push(`  - ${detail}`);
    }
    if (artifact.description) {
      lines.push(`- **Description:** ${artifact.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by ${manifest.tool.name} v${manifest.tool.version} on ${manifest.createdAt}.`);

  return lines.join('\n');
}
