/**
 * Endpoint Detection Rules
 */

import type { DetectionRule } from '../engine.js';
import type { ProcessEvent, FileEvent, EdrAlert } from '../../schemas/endpoint.js';

/** Suspicious process execution */
const suspiciousProcessRule: DetectionRule = {
  id: 'endpoint-001',
  name: 'Suspicious Process Execution',
  description: 'Execution of commonly abused system utility',
  severity: 'medium',
  enabled: true,
  eventTypes: ['endpoint.process'],
  mitreTactics: ['execution'],
  mitreTechniques: ['T1059'],
  tags: ['endpoint', 'process', 'lolbas'],
  evaluate: (event: unknown) => {
    const procEvent = event as ProcessEvent;
    const suspiciousProcesses = [
      'powershell.exe',
      'cmd.exe',
      'wscript.exe',
      'cscript.exe',
      'mshta.exe',
      'rundll32.exe',
      'regsvr32.exe',
      'certutil.exe',
      'bitsadmin.exe',
    ];
    const processName = procEvent.processName?.toLowerCase();
    if (processName && suspiciousProcesses.includes(processName)) {
      // Higher confidence if elevated
      return procEvent.isElevated ? 0.8 : 0.6;
    }
    return null;
  },
};

/** Encoded command line */
const encodedCommandRule: DetectionRule = {
  id: 'endpoint-002',
  name: 'Encoded Command Line',
  description: 'Process started with encoded or obfuscated command line',
  severity: 'high',
  enabled: true,
  eventTypes: ['endpoint.process'],
  mitreTactics: ['execution', 'defense_evasion'],
  mitreTechniques: ['T1059.001', 'T1027'],
  tags: ['endpoint', 'process', 'obfuscation'],
  evaluate: (event: unknown) => {
    const procEvent = event as ProcessEvent;
    const cmdLine = procEvent.commandLine?.toLowerCase() ?? '';
    if (
      cmdLine.includes('-enc') ||
      cmdLine.includes('-encodedcommand') ||
      cmdLine.includes('frombase64')
    ) {
      return 0.85;
    }
    return null;
  },
};

/** Unsigned process execution */
const unsignedProcessRule: DetectionRule = {
  id: 'endpoint-003',
  name: 'Unsigned Process Execution',
  description: 'Execution of unsigned executable',
  severity: 'low',
  enabled: true,
  eventTypes: ['endpoint.process'],
  mitreTactics: ['execution'],
  mitreTechniques: ['T1059'],
  tags: ['endpoint', 'process', 'unsigned'],
  evaluate: (event: unknown) => {
    const procEvent = event as ProcessEvent;
    if (procEvent.isSigned === false) {
      return 0.4;
    }
    return null;
  },
};

/** Sensitive file access */
const sensitiveFileRule: DetectionRule = {
  id: 'endpoint-004',
  name: 'Sensitive File Access',
  description: 'Access to sensitive system or credential file',
  severity: 'high',
  enabled: true,
  eventTypes: ['endpoint.file'],
  mitreTactics: ['credential_access', 'collection'],
  mitreTechniques: ['T1003', 'T1005'],
  tags: ['endpoint', 'file', 'sensitive'],
  evaluate: (event: unknown) => {
    const fileEvent = event as FileEvent;
    if (fileEvent.isSensitiveLocation === true) {
      return 0.8;
    }

    const sensitivePaths = ['sam', 'ntds.dit', 'credentials', 'shadow', 'passwd'];
    const filePath = fileEvent.filePath?.toLowerCase() ?? '';
    if (sensitivePaths.some((p) => filePath.includes(p))) {
      return 0.85;
    }

    return null;
  },
};

/** EDR alert passthrough */
const edrAlertRule: DetectionRule = {
  id: 'endpoint-005',
  name: 'EDR Alert',
  description: 'Alert generated by endpoint detection and response system',
  severity: 'high', // Will be overridden by actual alert severity
  enabled: true,
  eventTypes: ['endpoint.edr_alert'],
  mitreTactics: ['*'],
  mitreTechniques: ['*'],
  tags: ['endpoint', 'edr', 'alert'],
  evaluate: (event: unknown) => {
    const alertEvent = event as EdrAlert;
    // Pass through EDR alerts with their confidence
    return alertEvent.confidence ?? 0.8;
  },
};

/** Registry persistence */
const registryPersistenceRule: DetectionRule = {
  id: 'endpoint-006',
  name: 'Registry Persistence',
  description: 'Modification of registry persistence location',
  severity: 'high',
  enabled: true,
  eventTypes: ['endpoint.registry'],
  mitreTactics: ['persistence'],
  mitreTechniques: ['T1547.001'],
  tags: ['endpoint', 'registry', 'persistence'],
  evaluate: (event: unknown) => {
    const regEvent = event as { isPersistenceLocation?: boolean; operation?: string };
    if (
      regEvent.isPersistenceLocation === true &&
      (regEvent.operation === 'value_set' || regEvent.operation === 'key_created')
    ) {
      return 0.85;
    }
    return null;
  },
};

export const endpointRules: DetectionRule[] = [
  suspiciousProcessRule,
  encodedCommandRule,
  unsignedProcessRule,
  sensitiveFileRule,
  edrAlertRule,
  registryPersistenceRule,
];
