"use strict";
/**
 * Summit Work Graph - Node Types
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkGraphNodeSchema = exports.SprintSchema = exports.PolicySchema = exports.EnvironmentSchema = exports.AgentSchema = exports.CustomerSchema = exports.IncidentSchema = exports.ScanSchema = exports.TestSchema = exports.PRSchema = exports.TicketSchema = exports.EpicSchema = exports.HypothesisSchema = exports.CommitmentSchema = exports.IntentSchema = exports.BaseNodeSchema = void 0;
const zod_1 = require("zod");
exports.BaseNodeSchema = zod_1.z.object({
    id: zod_1.z.string().uuid(),
    type: zod_1.z.string(),
    createdAt: zod_1.z.date(),
    updatedAt: zod_1.z.date(),
    createdBy: zod_1.z.string(),
    metadata: zod_1.z.record(zod_1.z.unknown()).optional(),
});
exports.IntentSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('intent'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    source: zod_1.z.enum(['customer', 'internal', 'market', 'regulation']),
    customer: zod_1.z.string().optional(),
    priority: zod_1.z.enum(['P0', 'P1', 'P2', 'P3']),
    status: zod_1.z.enum(['captured', 'validated', 'planned', 'delivered', 'rejected']),
    evidence: zod_1.z.array(zod_1.z.string()).default([]),
    targetDate: zod_1.z.date().optional(),
    valueScore: zod_1.z.number().min(0).max(100).optional(),
});
exports.CommitmentSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('commitment'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    customer: zod_1.z.string(),
    dueDate: zod_1.z.date(),
    status: zod_1.z.enum(['active', 'at_risk', 'delivered', 'broken']),
    confidence: zod_1.z.number().min(0).max(100),
    contractualSLA: zod_1.z.boolean().default(false),
    escalationPath: zod_1.z.array(zod_1.z.string()).default([]),
    linkedIntents: zod_1.z.array(zod_1.z.string()).default([]),
});
exports.HypothesisSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('hypothesis'),
    statement: zod_1.z.string().min(1),
    status: zod_1.z.enum(['proposed', 'testing', 'validated', 'invalidated']),
    confidence: zod_1.z.number().min(0).max(100),
    evidence: zod_1.z.array(zod_1.z.object({
        type: zod_1.z.enum(['metric', 'user_feedback', 'experiment', 'observation']),
        description: zod_1.z.string(),
        support: zod_1.z.enum(['for', 'against', 'neutral']),
        weight: zod_1.z.number().min(0).max(1),
    })),
    testPlan: zod_1.z.string().optional(),
    outcome: zod_1.z.string().optional(),
});
exports.EpicSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('epic'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    status: zod_1.z.enum(['draft', 'planned', 'in_progress', 'completed', 'cancelled']),
    owner: zod_1.z.string().optional(),
    targetQuarter: zod_1.z.string().optional(),
    progress: zod_1.z.number().min(0).max(100).default(0),
    linearId: zod_1.z.string().optional(),
    jiraKey: zod_1.z.string().optional(),
});
exports.TicketSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('ticket'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    status: zod_1.z.enum(['backlog', 'ready', 'in_progress', 'review', 'done', 'blocked']),
    priority: zod_1.z.enum(['P0', 'P1', 'P2', 'P3']),
    estimate: zod_1.z.number().optional(),
    assignee: zod_1.z.string().optional(),
    assigneeType: zod_1.z.enum(['human', 'agent']).optional(),
    labels: zod_1.z.array(zod_1.z.string()).default([]),
    dueDate: zod_1.z.date().optional(),
    linearId: zod_1.z.string().optional(),
    jiraKey: zod_1.z.string().optional(),
    cycleId: zod_1.z.string().optional(),
    sprintId: zod_1.z.string().optional(),
    agentEligible: zod_1.z.boolean().default(false),
    complexity: zod_1.z.enum(['trivial', 'simple', 'medium', 'complex', 'unknown']).default('unknown'),
    area: zod_1.z.string().optional(),
    blockedReason: zod_1.z.string().optional(),
    completedAt: zod_1.z.date().optional(),
});
exports.PRSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('pr'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    url: zod_1.z.string().url(),
    number: zod_1.z.number(),
    author: zod_1.z.string(),
    authorType: zod_1.z.enum(['human', 'agent']),
    status: zod_1.z.enum(['draft', 'open', 'merged', 'closed']),
    checksStatus: zod_1.z.enum(['pending', 'passing', 'failing']),
    reviewers: zod_1.z.array(zod_1.z.string()).default([]),
    additions: zod_1.z.number().default(0),
    deletions: zod_1.z.number().default(0),
    filesChanged: zod_1.z.number().default(0),
    branch: zod_1.z.string(),
    mergedAt: zod_1.z.date().optional(),
});
exports.TestSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('test'),
    name: zod_1.z.string().min(1),
    suite: zod_1.z.string(),
    status: zod_1.z.enum(['pending', 'running', 'passed', 'failed', 'skipped', 'flaky']),
    lastRun: zod_1.z.date().optional(),
    duration: zod_1.z.number().optional(),
    coverage: zod_1.z.number().min(0).max(100).optional(),
    failureReason: zod_1.z.string().optional(),
    flakyRate: zod_1.z.number().min(0).max(100).optional(),
});
exports.ScanSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('scan'),
    scanType: zod_1.z.enum(['sast', 'dast', 'dependency', 'secret', 'license', 'quality']),
    status: zod_1.z.enum(['pending', 'running', 'completed', 'failed']),
    findings: zod_1.z.array(zod_1.z.object({
        severity: zod_1.z.enum(['critical', 'high', 'medium', 'low', 'info']),
        title: zod_1.z.string(),
        description: zod_1.z.string(),
        location: zod_1.z.string().optional(),
        cwe: zod_1.z.string().optional(),
        remediation: zod_1.z.string().optional(),
    })),
    criticalCount: zod_1.z.number().default(0),
    highCount: zod_1.z.number().default(0),
    mediumCount: zod_1.z.number().default(0),
    lowCount: zod_1.z.number().default(0),
    completedAt: zod_1.z.date().optional(),
});
exports.IncidentSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('incident'),
    title: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    severity: zod_1.z.enum(['SEV1', 'SEV2', 'SEV3', 'SEV4']),
    status: zod_1.z.enum(['detected', 'acknowledged', 'investigating', 'mitigated', 'resolved', 'postmortem']),
    detectedAt: zod_1.z.date(),
    acknowledgedAt: zod_1.z.date().optional(),
    mitigatedAt: zod_1.z.date().optional(),
    resolvedAt: zod_1.z.date().optional(),
    impactedServices: zod_1.z.array(zod_1.z.string()).default([]),
    impactedCustomers: zod_1.z.array(zod_1.z.string()).default([]),
    oncall: zod_1.z.string().optional(),
    rootCause: zod_1.z.string().optional(),
    postmortemUrl: zod_1.z.string().optional(),
    ttd: zod_1.z.number().optional(),
    ttm: zod_1.z.number().optional(),
    ttr: zod_1.z.number().optional(),
});
exports.CustomerSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('customer'),
    name: zod_1.z.string().min(1),
    tier: zod_1.z.enum(['enterprise', 'business', 'startup', 'free']),
    arr: zod_1.z.number().optional(),
    healthScore: zod_1.z.number().min(0).max(100).optional(),
    csm: zod_1.z.string().optional(),
    renewalDate: zod_1.z.date().optional(),
    contracts: zod_1.z.array(zod_1.z.string()).default([]),
});
exports.AgentSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('agent'),
    name: zod_1.z.string().min(1),
    agentType: zod_1.z.enum(['coding', 'testing', 'security', 'docs', 'review', 'triage', 'planning']),
    status: zod_1.z.enum(['available', 'busy', 'offline', 'error']),
    capabilities: zod_1.z.array(zod_1.z.string()).default([]),
    currentTask: zod_1.z.string().optional(),
    completedTasks: zod_1.z.number().default(0),
    successRate: zod_1.z.number().min(0).max(100).default(100),
    averageCompletionTime: zod_1.z.number().optional(),
    reputation: zod_1.z.number().min(0).max(100).default(50),
    lastActive: zod_1.z.date().optional(),
    model: zod_1.z.string().optional(),
    version: zod_1.z.string().optional(),
});
exports.EnvironmentSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('environment'),
    name: zod_1.z.enum(['dev', 'staging', 'production', 'canary']),
    version: zod_1.z.string(),
    deployedAt: zod_1.z.date(),
    health: zod_1.z.enum(['healthy', 'degraded', 'unhealthy', 'unknown']),
    url: zod_1.z.string().optional(),
    region: zod_1.z.string().optional(),
    metrics: zod_1.z.object({
        cpu: zod_1.z.number().optional(),
        memory: zod_1.z.number().optional(),
        latencyP50: zod_1.z.number().optional(),
        latencyP99: zod_1.z.number().optional(),
        errorRate: zod_1.z.number().optional(),
    }).optional(),
});
exports.PolicySchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('policy'),
    name: zod_1.z.string().min(1),
    description: zod_1.z.string(),
    policyType: zod_1.z.enum(['security', 'quality', 'compliance', 'operational', 'governance']),
    status: zod_1.z.enum(['draft', 'active', 'deprecated']),
    scope: zod_1.z.array(zod_1.z.enum(['pr', 'ticket', 'deployment', 'incident', 'all'])),
    conditions: zod_1.z.array(zod_1.z.object({
        field: zod_1.z.string(),
        operator: zod_1.z.enum(['equals', 'not_equals', 'contains', 'greater_than', 'less_than', 'matches']),
        value: zod_1.z.unknown().optional(),
    })),
    actions: zod_1.z.array(zod_1.z.object({
        type: zod_1.z.enum(['block', 'warn', 'notify', 'require_approval', 'auto_fix']),
        message: zod_1.z.string(),
        target: zod_1.z.string().optional(),
    })),
    exceptions: zod_1.z.array(zod_1.z.string()).default([]),
    owner: zod_1.z.string().optional(),
    enforcementLevel: zod_1.z.enum(['advisory', 'soft', 'hard']).default('soft'),
});
exports.SprintSchema = exports.BaseNodeSchema.extend({
    type: zod_1.z.literal('sprint'),
    name: zod_1.z.string().min(1),
    number: zod_1.z.number(),
    status: zod_1.z.enum(['planning', 'active', 'completed', 'cancelled']),
    startDate: zod_1.z.date(),
    endDate: zod_1.z.date(),
    goal: zod_1.z.string().optional(),
    capacity: zod_1.z.number().optional(),
    committed: zod_1.z.number().default(0),
    completed: zod_1.z.number().default(0),
    velocity: zod_1.z.number().optional(),
    team: zod_1.z.string().optional(),
});
exports.WorkGraphNodeSchema = zod_1.z.discriminatedUnion('type', [
    exports.IntentSchema, exports.CommitmentSchema, exports.HypothesisSchema, exports.EpicSchema, exports.TicketSchema, exports.PRSchema,
    exports.TestSchema, exports.ScanSchema, exports.IncidentSchema, exports.CustomerSchema, exports.AgentSchema, exports.EnvironmentSchema,
    exports.PolicySchema, exports.SprintSchema,
]);
