import { ConsentEdgeRecord, ConsentNode, ConsentPolicyVersion } from './types.ts';

export const CONSENT_GRAPH_NODES: ConsentNode[] = [
  { id: 'subject:alice', type: 'SUBJECT', name: 'Alice Carter', metadata: { region: 'US' } },
  { id: 'subject:bob', type: 'SUBJECT', name: 'Bob Singh', metadata: { region: 'EU' } },
  { id: 'purpose:marketing', type: 'PURPOSE', name: 'Marketing Outreach', metadata: { lawfulBasis: 'OPT_IN' } },
  { id: 'purpose:research', type: 'PURPOSE', name: 'Product Research', metadata: { lawfulBasis: 'LEGITIMATE_INTEREST' } },
  { id: 'scope:email', type: 'SCOPE', name: 'Email Campaign Data', metadata: { classification: 'PII' } },
  { id: 'scope:analytics', type: 'SCOPE', name: 'Product Analytics Events', metadata: { classification: 'Behavioral' } },
  { id: 'scope:location', type: 'SCOPE', name: 'Location Telemetry', metadata: { classification: 'Sensitive' } },
  { id: 'delegation:acme', type: 'DELEGATION', name: 'Acme Analytics Partner', metadata: { contract: 'acme-2024' } },
  { id: 'delegation:research-lab', type: 'DELEGATION', name: 'Urban Research Lab', metadata: { contract: 'research-2024' } },
];

export const CONSENT_GRAPH_EDGE_HISTORY: ConsentEdgeRecord[] = [
  {
    recordId: 'rec-001',
    edgeId: 'edge:subject:alice->purpose:marketing',
    type: 'SUBJECT_PURPOSE',
    fromId: 'subject:alice',
    toId: 'purpose:marketing',
    validInterval: { start: '2024-01-01T00:00:00Z' },
    txInterval: { start: '2024-01-01T00:00:00Z' },
    metadata: { lawfulBasis: 'OPT_IN', collectedBy: 'web-form' },
  },
  {
    recordId: 'rec-002',
    edgeId: 'edge:subject:bob->purpose:research',
    type: 'SUBJECT_PURPOSE',
    fromId: 'subject:bob',
    toId: 'purpose:research',
    validInterval: { start: '2024-01-10T00:00:00Z', end: '2024-04-15T00:00:00Z' },
    txInterval: { start: '2024-01-15T00:00:00Z', end: '2024-04-22T00:00:00Z' },
    metadata: { lawfulBasis: 'LEGITIMATE_INTEREST', collectedBy: 'mobile-app' },
  },
  {
    recordId: 'rec-101',
    edgeId: 'edge:purpose:marketing->scope:email',
    type: 'PURPOSE_SCOPE',
    fromId: 'purpose:marketing',
    toId: 'scope:email',
    validInterval: { start: '2024-01-01T00:00:00Z' },
    txInterval: { start: '2024-01-01T00:00:00Z' },
    metadata: { reason: 'Campaign personalization' },
  },
  {
    recordId: 'rec-102',
    edgeId: 'edge:purpose:marketing->scope:location',
    type: 'PURPOSE_SCOPE',
    fromId: 'purpose:marketing',
    toId: 'scope:location',
    validInterval: { start: '2024-01-01T00:00:00Z', end: '2024-03-18T00:00:00Z' },
    txInterval: { start: '2024-01-01T00:00:00Z', end: '2024-03-24T00:00:00Z' },
    metadata: { reason: 'Store proximity segmentation' },
  },
  {
    recordId: 'rec-103',
    edgeId: 'edge:purpose:marketing->scope:analytics',
    type: 'PURPOSE_SCOPE',
    fromId: 'purpose:marketing',
    toId: 'scope:analytics',
    validInterval: { start: '2024-03-18T00:00:00Z' },
    txInterval: { start: '2024-03-24T00:00:00Z' },
    metadata: { reason: 'Cross-channel attribution' },
  },
  {
    recordId: 'rec-104',
    edgeId: 'edge:purpose:research->scope:analytics',
    type: 'PURPOSE_SCOPE',
    fromId: 'purpose:research',
    toId: 'scope:analytics',
    validInterval: { start: '2024-01-10T00:00:00Z' },
    txInterval: { start: '2024-01-15T00:00:00Z' },
    metadata: { reason: 'Usability studies' },
  },
  {
    recordId: 'rec-201',
    edgeId: 'edge:scope:email->delegation:acme',
    type: 'SCOPE_DELEGATION',
    fromId: 'scope:email',
    toId: 'delegation:acme',
    validInterval: { start: '2024-01-01T00:00:00Z' },
    txInterval: { start: '2024-01-01T00:00:00Z' },
    metadata: { contract: 'acme-2024', retentionDays: 30 },
  },
  {
    recordId: 'rec-202',
    edgeId: 'edge:scope:location->delegation:acme',
    type: 'SCOPE_DELEGATION',
    fromId: 'scope:location',
    toId: 'delegation:acme',
    validInterval: { start: '2024-01-01T00:00:00Z', end: '2024-03-18T00:00:00Z' },
    txInterval: { start: '2024-01-01T00:00:00Z', end: '2024-03-24T00:00:00Z' },
    metadata: { contract: 'acme-2024', retentionDays: 7 },
  },
  {
    recordId: 'rec-203',
    edgeId: 'edge:scope:analytics->delegation:research-lab',
    type: 'SCOPE_DELEGATION',
    fromId: 'scope:analytics',
    toId: 'delegation:research-lab',
    validInterval: { start: '2024-01-10T00:00:00Z' },
    txInterval: { start: '2024-01-15T00:00:00Z' },
    metadata: { contract: 'research-2024', retentionDays: 90 },
  },
  {
    recordId: 'rec-301',
    edgeId: 'edge:flow:alice-email',
    type: 'SUBJECT_SCOPE_FLOW',
    fromId: 'subject:alice',
    toId: 'scope:email',
    validInterval: { start: '2024-01-05T00:00:00Z' },
    txInterval: { start: '2024-01-05T00:00:00Z' },
    metadata: {
      flow: {
        id: 'flow:alice-email',
        subjectId: 'subject:alice',
        purposeId: 'purpose:marketing',
        scopeId: 'scope:email',
        description: 'Email campaign personalization for Alice Carter',
        delegationChain: ['delegation:acme'],
      },
    },
  },
  {
    recordId: 'rec-302',
    edgeId: 'edge:flow:alice-location',
    type: 'SUBJECT_SCOPE_FLOW',
    fromId: 'subject:alice',
    toId: 'scope:location',
    validInterval: { start: '2024-01-05T00:00:00Z', end: '2024-03-18T00:00:00Z' },
    txInterval: { start: '2024-01-05T00:00:00Z', end: '2024-03-24T00:00:00Z' },
    metadata: {
      flow: {
        id: 'flow:alice-location',
        subjectId: 'subject:alice',
        purposeId: 'purpose:marketing',
        scopeId: 'scope:location',
        description: 'Location proximity marketing for Alice Carter',
        delegationChain: ['delegation:acme'],
      },
    },
  },
  {
    recordId: 'rec-303',
    edgeId: 'edge:flow:alice-analytics',
    type: 'SUBJECT_SCOPE_FLOW',
    fromId: 'subject:alice',
    toId: 'scope:analytics',
    validInterval: { start: '2024-03-18T00:00:00Z' },
    txInterval: { start: '2024-03-24T00:00:00Z' },
    metadata: {
      flow: {
        id: 'flow:alice-analytics',
        subjectId: 'subject:alice',
        purposeId: 'purpose:marketing',
        scopeId: 'scope:analytics',
        description: 'Attribution analytics for Alice Carter',
        delegationChain: ['delegation:acme'],
      },
    },
  },
  {
    recordId: 'rec-304',
    edgeId: 'edge:flow:bob-analytics',
    type: 'SUBJECT_SCOPE_FLOW',
    fromId: 'subject:bob',
    toId: 'scope:analytics',
    validInterval: { start: '2024-01-12T00:00:00Z', end: '2024-04-15T00:00:00Z' },
    txInterval: { start: '2024-01-15T00:00:00Z', end: '2024-04-22T00:00:00Z' },
    metadata: {
      flow: {
        id: 'flow:bob-analytics',
        subjectId: 'subject:bob',
        purposeId: 'purpose:research',
        scopeId: 'scope:analytics',
        description: 'Product research analytics for Bob Singh',
        delegationChain: ['delegation:research-lab'],
      },
    },
  },
];

export const CONSENT_POLICY_VERSIONS: ConsentPolicyVersion[] = [
  {
    id: 'v1',
    label: 'Baseline launch policies',
    validTime: '2024-02-01T00:00:00Z',
    txTime: '2024-02-01T00:00:00Z',
    summary: 'Initial marketing and research consent graph baseline.',
  },
  {
    id: 'v2',
    label: 'Marketing refresh removing location telemetry',
    validTime: '2024-03-26T00:00:00Z',
    txTime: '2024-03-26T00:00:00Z',
    summary: 'Marketing policies updated to drop location tracking and add analytics flow.',
  },
  {
    id: 'v3',
    label: 'Research opt-out by Bob Singh',
    validTime: '2024-04-26T00:00:00Z',
    txTime: '2024-04-26T00:00:00Z',
    summary: 'Research subject revoked analytics processing; marketing policies unchanged.',
  },
];
