-- Partition outbox_events by range (occurred_at)

BEGIN;

-- 1. Create the new partitioned table
-- Note: We change PK to include partition key (occurred_at)
CREATE TABLE IF NOT EXISTS outbox_events_partitioned (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  aggregate_type TEXT NOT NULL,
  aggregate_id UUID NOT NULL,
  type TEXT NOT NULL,
  payload JSONB NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  PRIMARY KEY (occurred_at, id)
) PARTITION BY RANGE (occurred_at);

-- 2. Create index on processed_at
CREATE INDEX IF NOT EXISTS idx_outbox_partitioned_unprocessed ON outbox_events_partitioned(processed_at) WHERE processed_at IS NULL;

-- 3. Create default partition
CREATE TABLE IF NOT EXISTS outbox_events_default PARTITION OF outbox_events_partitioned DEFAULT;

-- 4. Create partitions for current time periods (adjust months as needed)
-- Creating a few months covering potential current usage
CREATE TABLE IF NOT EXISTS outbox_events_p2024_h2 PARTITION OF outbox_events_partitioned
    FOR VALUES FROM ('2024-06-01') TO ('2025-01-01');

CREATE TABLE IF NOT EXISTS outbox_events_p2025_h1 PARTITION OF outbox_events_partitioned
    FOR VALUES FROM ('2025-01-01') TO ('2025-07-01');

CREATE TABLE IF NOT EXISTS outbox_events_p2025_h2 PARTITION OF outbox_events_partitioned
    FOR VALUES FROM ('2025-07-01') TO ('2026-01-01');

-- 5. Copy data (if old table exists)
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'outbox_events') THEN
        INSERT INTO outbox_events_partitioned (id, aggregate_type, aggregate_id, type, payload, occurred_at, processed_at)
        SELECT id, aggregate_type, aggregate_id, type, payload, occurred_at, processed_at FROM outbox_events;

        -- Sync sequence
        PERFORM setval(pg_get_serial_sequence('outbox_events_partitioned', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM outbox_events));

        -- Rename old table
        ALTER TABLE outbox_events RENAME TO outbox_events_old;
    END IF;
END $$;

-- 6. Rename new table to active name
ALTER TABLE outbox_events_partitioned RENAME TO outbox_events;

COMMIT;
