import { ApprovalRequest, UserContext } from "./types";

export const demoUser: UserContext = {
  id: "user-1",
  name: "Alex Compliance",
  role: "compliance_officer",
  clearance: "l3",
  region: "us",
  tenants: ["tenant-1", "tenant-2"],
};

export const approvalsData: ApprovalRequest[] = [
  {
    id: "req-1",
    title: "Enable switchboard dual routing",
    service: "switchboard",
    requester: "Nora Nguyen",
    riskLevel: "high",
    status: "waiting_dual",
    dualControl: true,
    correlationId: "corr-abc",
    submittedAt: "2025-02-05T10:00:00Z",
    attributes: {
      tenant: "tenant-1",
      region: "us",
      sensitivity: "restricted",
    },
    approvals: [
      {
        id: "act-1",
        actor: "user-2",
        role: "risk_owner",
        decision: "approved",
        rationale: "Meets risk posture with enhanced alerting",
        timestamp: "2025-02-05T10:15:00Z",
        correlationId: "corr-abc",
      },
    ],
    timeline: [
      {
        id: "t1",
        correlationId: "corr-abc",
        type: "request",
        title: "Request submitted",
        description: "Change request raised by Nora",
        actor: "Nora Nguyen",
        timestamp: "2025-02-05T10:00:00Z",
        tags: ["tenant-1", "us"],
      },
      {
        id: "t2",
        correlationId: "corr-abc",
        type: "approval",
        title: "Risk owner approved",
        description: "Risk owner approved with condition: enhanced alerting",
        actor: "user-2",
        timestamp: "2025-02-05T10:15:00Z",
        tags: ["risk"],
      },
      {
        id: "t3",
        correlationId: "corr-abc",
        type: "abac",
        title: "ABAC evaluation",
        description: "ABAC permit for tenant-1 restricted workload",
        actor: "opa.switchboard",
        timestamp: "2025-02-05T10:15:10Z",
        tags: ["policy"],
      },
    ],
  },
  {
    id: "req-2",
    title: "Rotate audit signing key",
    service: "audit-ledger",
    requester: "Priya Patel",
    riskLevel: "medium",
    status: "pending",
    dualControl: false,
    correlationId: "corr-def",
    submittedAt: "2025-02-06T09:30:00Z",
    attributes: {
      tenant: "tenant-2",
      region: "us",
      sensitivity: "internal",
    },
    approvals: [],
    timeline: [
      {
        id: "t4",
        correlationId: "corr-def",
        type: "request",
        title: "Request submitted",
        description: "Audit team requested signing key rotation",
        actor: "Priya Patel",
        timestamp: "2025-02-06T09:30:00Z",
        tags: ["tenant-2"],
      },
    ],
  },
];
