import { WidgetTemplate, DashboardTemplate } from '../types';

// Widget Templates Library
export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  {
    id: 'metric-card',
    name: 'Metric Card',
    description: 'Display a key metric with optional trend',
    type: 'metric',
    category: 'metric',
    icon: '📊',
    defaultConfig: {
      value: 0,
      label: 'Metric',
      format: 'number',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    },
    tags: ['metric', 'kpi', 'stat'],
  },
  {
    id: 'bar-chart',
    name: 'Bar Chart',
    description: 'Compare values across categories',
    type: 'chart',
    category: 'chart',
    icon: '📊',
    defaultConfig: {
      chartType: 'bar',
      xAxis: 'category',
      yAxis: 'value',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 6,
      h: 4,
      minW: 4,
      minH: 3,
    },
    tags: ['chart', 'bar', 'comparison'],
  },
  {
    id: 'line-chart',
    name: 'Line Chart',
    description: 'Show trends over time',
    type: 'chart',
    category: 'chart',
    icon: '📈',
    defaultConfig: {
      chartType: 'line',
      xAxis: 'time',
      yAxis: 'value',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 6,
      h: 4,
      minW: 4,
      minH: 3,
    },
    tags: ['chart', 'line', 'trend', 'time-series'],
  },
  {
    id: 'pie-chart',
    name: 'Pie Chart',
    description: 'Show proportions of a whole',
    type: 'chart',
    category: 'chart',
    icon: '🥧',
    defaultConfig: {
      chartType: 'pie',
      groupBy: 'category',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 4,
      h: 4,
      minW: 3,
      minH: 3,
    },
    tags: ['chart', 'pie', 'proportion'],
  },
  {
    id: 'data-table',
    name: 'Data Table',
    description: 'Display data in tabular format',
    type: 'table',
    category: 'table',
    icon: '📋',
    defaultConfig: {
      columns: [],
      sortable: true,
      filterable: true,
      paginated: true,
      pageSize: 10,
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 8,
      h: 6,
      minW: 4,
      minH: 4,
    },
    tags: ['table', 'data', 'grid'],
  },
  {
    id: 'map-choropleth',
    name: 'Choropleth Map',
    description: 'Display regional data on map',
    type: 'map',
    category: 'map',
    icon: '🗺️',
    defaultConfig: {
      mapType: 'choropleth',
      center: [0, 0],
      zoom: 2,
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 8,
      h: 6,
      minW: 4,
      minH: 4,
    },
    tags: ['map', 'geography', 'choropleth'],
  },
  {
    id: 'network-graph',
    name: 'Network Graph',
    description: 'Visualize node relationships',
    type: 'network',
    category: 'network',
    icon: '🕸️',
    defaultConfig: {
      layout: 'force',
      physics: true,
      clustering: false,
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 8,
      h: 6,
      minW: 6,
      minH: 5,
    },
    tags: ['network', 'graph', 'relationships'],
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Display events over time',
    type: 'timeline',
    category: 'timeline',
    icon: '⏰',
    defaultConfig: {
      startField: 'start',
      labelField: 'label',
      zoom: true,
      pan: true,
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 12,
      h: 4,
      minW: 6,
      minH: 3,
    },
    tags: ['timeline', 'events', 'temporal'],
  },
  {
    id: 'heatmap',
    name: 'Heat Map',
    description: 'Show intensity patterns in a matrix',
    type: 'chart',
    category: 'chart',
    icon: '🔥',
    defaultConfig: {
      chartType: 'heatmap',
      xAxis: 'category',
      yAxis: 'category',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    tags: ['heatmap', 'matrix', 'intensity'],
  },
  {
    id: 'scatter-plot',
    name: 'Scatter Plot',
    description: 'Show relationships between variables',
    type: 'chart',
    category: 'chart',
    icon: '🔵',
    defaultConfig: {
      chartType: 'scatter',
      xAxis: 'x',
      yAxis: 'y',
    },
    defaultLayout: {
      x: 0,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    tags: ['scatter', 'correlation', 'distribution'],
  },
];

// Dashboard Templates
export const DASHBOARD_TEMPLATES: DashboardTemplate[] = [
  {
    id: 'executive-dashboard',
    name: 'Executive Dashboard',
    description: 'High-level KPIs and metrics for executives',
    category: 'business',
    dashboard: {
      name: 'Executive Dashboard',
      description: 'Key metrics at a glance',
      pages: [
        {
          id: 'overview',
          name: 'Overview',
          layout: {
            type: 'grid',
            columns: 12,
            rowHeight: 80,
          },
          widgets: [
            {
              id: 'revenue',
              type: 'metric',
              title: 'Total Revenue',
              config: {
                value: '$2.5M',
                label: 'Total Revenue',
                trend: { value: 12.5, direction: 'up' as const, label: 'vs last month' },
                color: '#10b981',
              },
              layout: { x: 0, y: 0, w: 3, h: 2 },
            },
            {
              id: 'users',
              type: 'metric',
              title: 'Active Users',
              config: {
                value: '48.2K',
                label: 'Active Users',
                trend: { value: 8.3, direction: 'up' as const, label: 'vs last month' },
                color: '#3b82f6',
              },
              layout: { x: 3, y: 0, w: 3, h: 2 },
            },
            {
              id: 'revenue-chart',
              type: 'chart',
              title: 'Revenue Trend',
              config: {
                chartType: 'line',
                xAxis: 'month',
                yAxis: 'revenue',
              },
              layout: { x: 0, y: 2, w: 8, h: 4 },
            },
            {
              id: 'category-breakdown',
              type: 'chart',
              title: 'Revenue by Category',
              config: {
                chartType: 'pie',
                groupBy: 'category',
              },
              layout: { x: 8, y: 2, w: 4, h: 4 },
            },
          ],
          order: 0,
        },
      ],
      version: 1,
    },
    tags: ['executive', 'kpi', 'business'],
  },
  {
    id: 'threat-intel-dashboard',
    name: 'Threat Intelligence Dashboard',
    description: 'Security threat monitoring and analysis',
    category: 'security',
    dashboard: {
      name: 'Threat Intelligence',
      description: 'Real-time threat monitoring',
      pages: [
        {
          id: 'threats',
          name: 'Threats',
          layout: {
            type: 'grid',
            columns: 12,
            rowHeight: 80,
          },
          widgets: [
            {
              id: 'threat-count',
              type: 'metric',
              title: 'Active Threats',
              config: {
                value: 247,
                label: 'Active Threats',
                color: '#ef4444',
              },
              layout: { x: 0, y: 0, w: 3, h: 2 },
            },
            {
              id: 'threat-map',
              type: 'map',
              title: 'Threat Origins',
              config: {
                mapType: 'heatmap',
                center: [0, 20],
                zoom: 2,
              },
              layout: { x: 0, y: 2, w: 8, h: 6 },
            },
            {
              id: 'threat-network',
              type: 'network',
              title: 'Threat Network',
              config: {
                layout: 'force',
                physics: true,
              },
              layout: { x: 8, y: 2, w: 4, h: 6 },
            },
          ],
          order: 0,
        },
      ],
      version: 1,
    },
    tags: ['security', 'threat', 'intelligence'],
  },
  {
    id: 'network-analysis-dashboard',
    name: 'Network Analysis Dashboard',
    description: 'Analyze and visualize network relationships',
    category: 'analytics',
    dashboard: {
      name: 'Network Analysis',
      description: 'Entity relationship analysis',
      pages: [
        {
          id: 'network',
          name: 'Network View',
          layout: {
            type: 'grid',
            columns: 12,
            rowHeight: 80,
          },
          widgets: [
            {
              id: 'network-graph',
              type: 'network',
              title: 'Entity Network',
              config: {
                layout: 'force',
                physics: true,
                clustering: true,
              },
              layout: { x: 0, y: 0, w: 9, h: 8 },
            },
            {
              id: 'node-details',
              type: 'table',
              title: 'Selected Nodes',
              config: {
                columns: [
                  { id: 'name', label: 'Name', field: 'name' },
                  { id: 'type', label: 'Type', field: 'type' },
                  { id: 'degree', label: 'Connections', field: 'degree' },
                ],
              },
              layout: { x: 9, y: 0, w: 3, h: 8 },
            },
          ],
          order: 0,
        },
      ],
      version: 1,
    },
    tags: ['network', 'analysis', 'graph'],
  },
];
