import { Story } from '../narrative/story.js';

export class StoryExportService {
  /**
   * Generates an HTML report for a story.
   * In a real implementation, this might generate a PDF using puppeteer or similar.
   */
  async exportToHtml(story: Story): Promise<string> {
    const eventsHtml = story.events.map(e => `
      <div class="event">
        <span class="time">${new Date(e.timestamp).toISOString()}</span>
        <span class="desc">${this.escapeHtml(e.description)}</span>
        ${e.entityId ? `<span class="entity">Ref: ${e.entityId}</span>` : ''}
      </div>
    `).join('\n');

    const blocksHtml = story.blocks.map(b => `
      <div class="block ${b.type}">
        <div class="content">${this.markdownToHtml(b.content)}</div>
        ${b.citations.length ? `<div class="citations">Citations: ${b.citations.join(', ')}</div>` : ''}
      </div>
    `).join('\n');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${this.escapeHtml(story.title)}</title>
        <style>
          body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
          .timeline { border-left: 2px solid #ccc; padding-left: 20px; margin-bottom: 40px; }
          .event { margin-bottom: 10px; }
          .time { font-weight: bold; margin-right: 10px; }
          .block { margin-bottom: 20px; padding: 10px; background: #f9f9f9; }
          .citations { font-size: 0.8em; color: #666; margin-top: 5px; }
        </style>
      </head>
      <body>
        <h1>${this.escapeHtml(story.title)}</h1>
        <h2>Timeline</h2>
        <div class="timeline">
          ${eventsHtml}
        </div>
        <h2>Narrative</h2>
        <div class="narrative">
          ${blocksHtml}
        </div>
        <footer>
          <p>Generated by IntelGraph Storybuilder</p>
          <p>Provenance ID: ${story.id}</p>
        </footer>
      </body>
      </html>
    `;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  private markdownToHtml(text: string): string {
    // Very basic markdown support
    return this.escapeHtml(text)
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>');
  }
}
