/**
 * System Report Template Definitions
 * Centralized location for all system-provided report templates
 */

import type { ReportTemplate } from '../types/Template.js';

export const TEMPLATE_DEFINITIONS: ReportTemplate[] = [
  {
    id: 'INVESTIGATION_SUMMARY',
    name: 'Investigation Summary Report',
    description: 'A comprehensive overview of investigation findings',
    category: 'INVESTIGATION',
    sections: [
      'executive_summary',
      'investigation_timeline',
      'key_entities',
      'relationship_analysis',
      'evidence_summary',
      'findings_conclusions',
      'recommendations',
    ],
    parameters: [
      { name: 'investigationId', type: 'string', required: true },
      { name: 'includeClassifiedData', type: 'boolean', default: false },
      {
        name: 'summaryLevel',
        type: 'enum',
        options: ['brief', 'detailed', 'comprehensive'],
        default: 'detailed',
      },
      { name: 'timeRange', type: 'daterange', required: false },
    ],
    outputFormats: ['PDF', 'DOCX', 'HTML', 'JSON'],
    estimatedTime: 120000,
    accessLevel: 'ANALYST',
  },
  {
    id: 'ENTITY_PROFILE',
    name: 'Entity Profile Report',
    description: 'Detailed profile of specific entity with all related information',
    category: 'ENTITY',
    sections: [
      'entity_overview',
      'basic_information',
      'connection_analysis',
      'activity_timeline',
      'risk_assessment',
      'media_evidence',
      'related_investigations',
    ],
    parameters: [
      { name: 'entityId', type: 'string', required: true },
      { name: 'includeConnections', type: 'boolean', default: true },
      {
        name: 'connectionDepth',
        type: 'integer',
        default: 2,
        min: 1,
        max: 4,
      },
      { name: 'includeRiskAnalysis', type: 'boolean', default: true },
    ],
    outputFormats: ['PDF', 'DOCX', 'HTML', 'JSON'],
    estimatedTime: 90000,
    accessLevel: 'ANALYST',
  },
  {
    id: 'ENTITY_ANALYSIS',
    name: 'Entity Analysis Report',
    description: 'Deep-dive analysis of a single entity',
    category: 'ENTITY',
    sections: [
      'entity_overview',
      'connection_analysis',
      'risk_assessment',
      'activity_timeline',
    ],
    parameters: [
      { name: 'entityId', type: 'string', required: true },
      { name: 'includeConnections', type: 'boolean', default: true },
    ],
    outputFormats: ['PDF', 'DOCX', 'HTML', 'JSON'],
    estimatedTime: 60000,
    accessLevel: 'ANALYST',
  },
  {
    id: 'NETWORK_ANALYSIS',
    name: 'Network Analysis Report',
    description: 'Social network analysis with community detection and influence mapping',
    category: 'ANALYSIS',
    sections: [
      'network_overview',
      'network_topology',
      'centrality_analysis',
      'community_detection',
      'community_structure',
      'key_players',
      'influence_patterns',
      'communication_flows',
      'anomaly_detection',
      'recommendations',
    ],
    parameters: [
      { name: 'investigationId', type: 'string', required: true },
      {
        name: 'analysisType',
        type: 'enum',
        options: ['full', 'communities', 'influence', 'flows'],
        default: 'full',
      },
      { name: 'minConnectionWeight', type: 'float', default: 0.1 },
      { name: 'includeVisualization', type: 'boolean', default: true },
    ],
    outputFormats: ['PDF', 'HTML', 'JSON', 'GEPHI'],
    estimatedTime: 300000,
    accessLevel: 'SENIOR_ANALYST',
  },
  {
    id: 'COMPLIANCE_AUDIT',
    name: 'Compliance Audit Report',
    description: 'Comprehensive compliance audit with security and regulatory findings',
    category: 'COMPLIANCE',
    sections: [
      'audit_scope',
      'compliance_overview',
      'security_findings',
      'access_patterns',
      'violations_summary',
      'risk_assessment',
      'remediation_plan',
    ],
    parameters: [
      { name: 'auditPeriod', type: 'daterange', required: true },
      {
        name: 'complianceFramework',
        type: 'enum',
        options: ['SOC2', 'FISMA', 'GDPR', 'NIST'],
        required: true,
      },
      { name: 'includeRecommendations', type: 'boolean', default: true },
      {
        name: 'severityLevel',
        type: 'enum',
        options: ['all', 'high', 'critical'],
        default: 'all',
      },
    ],
    outputFormats: ['PDF', 'DOCX', 'JSON'],
    estimatedTime: 180000,
    accessLevel: 'SUPERVISOR',
  },
  {
    id: 'SECURITY_ASSESSMENT',
    name: 'Security Assessment Report',
    description: 'Assessment of security posture and risks',
    category: 'SECURITY',
    sections: [
      'security_findings',
      'access_patterns',
      'risk_assessment',
      'remediation_plan',
    ],
    parameters: [{ name: 'auditPeriod', type: 'daterange', required: true }],
    outputFormats: ['PDF', 'DOCX', 'JSON'],
    estimatedTime: 90000,
    accessLevel: 'SUPERVISOR',
  },
  {
    id: 'ANALYTICS_REPORT',
    name: 'Analytics Results Report',
    description: 'Summary of analytics results and insights',
    category: 'ANALYTICS',
    sections: ['executive_summary', 'key_metrics', 'trend_analysis'],
    parameters: [],
    outputFormats: ['PDF', 'HTML', 'JSON'],
    estimatedTime: 45000,
    accessLevel: 'ANALYST',
  },
  {
    id: 'COMPLIANCE_REPORT',
    name: 'Compliance Report',
    description: 'Compliance overview and findings',
    category: 'COMPLIANCE',
    sections: [
      'compliance_overview',
      'security_findings',
      'violations_summary',
      'remediation_plan',
    ],
    parameters: [],
    outputFormats: ['PDF', 'DOCX', 'JSON'],
    estimatedTime: 90000,
    accessLevel: 'SUPERVISOR',
  },
  {
    id: 'ANALYTICS_DASHBOARD',
    name: 'Analytics Dashboard Report',
    description: 'Executive dashboard with key metrics and insights',
    category: 'DASHBOARD',
    sections: [
      'executive_summary',
      'key_metrics',
      'trend_analysis',
      'performance_indicators',
      'anomaly_highlights',
      'predictive_insights',
      'action_items',
    ],
    parameters: [
      { name: 'timeRange', type: 'daterange', required: true },
      { name: 'includePredictions', type: 'boolean', default: true },
      {
        name: 'detailLevel',
        type: 'enum',
        options: ['summary', 'detailed'],
        default: 'summary',
      },
    ],
    outputFormats: ['PDF', 'HTML', 'PPT', 'JSON'],
    estimatedTime: 60000,
    accessLevel: 'ANALYST',
  },
  {
    id: 'TEMPORAL_ANALYSIS',
    name: 'Temporal Pattern Analysis',
    description: 'Time-based analysis of activities, events, and patterns',
    category: 'ANALYSIS',
    sections: [
      'timeline_overview',
      'activity_patterns',
      'frequency_analysis',
      'anomaly_detection',
      'correlation_analysis',
      'predictive_trends',
    ],
    parameters: [
      { name: 'investigationId', type: 'string', required: true },
      {
        name: 'timeGranularity',
        type: 'enum',
        options: ['hour', 'day', 'week', 'month'],
        default: 'day',
      },
      { name: 'includeForecasting', type: 'boolean', default: true },
      { name: 'anomalyThreshold', type: 'float', default: 0.95 },
    ],
    outputFormats: ['PDF', 'HTML', 'JSON', 'CSV'],
    estimatedTime: 150000,
    accessLevel: 'ANALYST',
  },
];
