import logging
from typing import List, Optional

try:
    from prov.model import PROV_ROLE, PROV_TYPE, ProvDocument
except ImportError:
    ProvDocument = None

from maestro.models import Artifact, ArtifactKind, Run

logger = logging.getLogger(__name__)

class ProvenanceExporter:
    """Exports Maestro Runs and Artifacts to W3C PROV format."""

    def __init__(self):
        if not ProvDocument:
            logger.warning("prov library not found. Provenance export will fail.")

    def export_run(self, run: Run, artifacts: list[Artifact]) -> Optional[ProvDocument]:
        """
        Convert a Run and its Artifacts into a PROV document.
        """
        if not ProvDocument:
            return None

        doc = ProvDocument()
        doc.add_namespace('summit', 'https://github.com/BrianCLong/summit/')
        doc.add_namespace('maestro', 'https://github.com/BrianCLong/summit/maestro/')
        doc.add_namespace('dcterms', 'http://purl.org/dc/terms/')

        # Agent: The user who triggered the run
        # We sanitize the owner string to be a valid identifier part if needed,
        # but here we assume it's safe or allow prov to handle/escape
        agent_id = f'summit:user/{run.owner}'
        agent = doc.agent(agent_id)

        # Activity: The Run itself
        activity_id = f'maestro:run/{run.id}'
        activity = doc.activity(activity_id, startTime=run.started_at, endTime=run.finished_at)

        # Association
        doc.wasAssociatedWith(activity, agent, other_attributes=[(PROV_ROLE, "Owner")])

        # Add metadata as attributes to activity
        if run.metadata:
            for k, v in run.metadata.items():
                # PROV attributes must be qualified names or literals.
                # We put them in summit namespace if possible or just stringify
                doc.activity(activity_id).add_attributes({f'summit:{k}': str(v)})

        # Entities: Artifacts
        for artifact in artifacts:
            entity_id = f'maestro:artifact/{artifact.id}'
            entity = doc.entity(entity_id)

            # attributes
            entity.add_attributes({
                'prov:type': artifact.kind,
                'summit:path': artifact.path_or_uri,
                'dcterms:created': artifact.created_at,
            })

            if artifact.content_hash:
                entity.add_attributes({'summit:content_hash': artifact.content_hash})

            if artifact.metadata_json:
                # Add governance metadata
                for k, v in artifact.metadata_json.dict().items():
                    entity.add_attributes({f'summit:{k}': str(v)})

            # Derivation/Generation
            # Artifact was generated by the Run
            doc.wasGeneratedBy(entity, activity)

        return doc
