export const FLAGS = {
  INFRA_REGISTRY_ENABLED: process.env.INFRA_REGISTRY_ENABLED === 'true',
  INFRA_POLICY_ENFORCE: process.env.INFRA_POLICY_ENFORCE === 'true',
  SCAFFOLDER_ENABLED: process.env.SCAFFOLDER_ENABLED === 'true',
  GRAPHRAG_INFRA_ENABLED: process.env.GRAPHRAG_INFRA_ENABLED === 'true',
  AGENT_INFRA_PLANNER_ENABLED: process.env.AGENT_INFRA_PLANNER_ENABLED === 'true',
};
