#!/usr/bin/env node
/**
 * Summit Autodidactic Feedback Engine (SAFE)
 * 
 * FAANG-Level Innovation for AI-Driven Engineering:
 * When AI agents write code at scale, they often repeat the same mistakes (hallucinating APIs, 
 * breaking architectural boundaries, failing CI in the same way). 
 * 
 * SAFE runs periodically to:
 * 1. Sweep recently failed, closed, or conflicted PRs.
 * 2. Extract the CI logs, diffs, or conflict reasons.
 * 3. Use an LLM to synthesize a generalized, permanent rule (a "Learning").
 * 4. Append this rule to `.learnings/AGENT_DIRECTIVES.md`.
 * 
 * Result: The repository itself teaches the agents how to code for it. 
 * Entropy decreases over time automatically.
 */

import fs from "node:fs/promises";
import { execSync } from "node:child_process";

const token = process.env.GITHUB_TOKEN;
const repoEnv = process.env.REPO;

if (!token || !repoEnv) {
  console.error("Missing GITHUB_TOKEN or REPO");
  process.exit(1);
}

const [owner, repo] = repoEnv.split("/");

async function callAI(prompt, apiKey, provider) {
  if (provider === "anthropic") {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
      body: JSON.stringify({
        model: "claude-3-5-sonnet-20240620",
        max_tokens: 2048,
        messages: [{ role: "user", content: prompt }]
      })
    });
    const data = await res.json();
    return data.content[0].text;
  } else if (provider === "openai") {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [{ role: "system", content: prompt }]
      })
    });
    const data = await res.json();
    return data.choices[0].message.content;
  }
  return null;
}

function exec(cmd, ignoreErrors = false) {
  try {
    return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "ignore"] });
  } catch (err) {
    if (!ignoreErrors) console.error(`Command failed: ${cmd}`);
    return null;
  }
}

async function main() {
  console.log("Starting Summit Autodidactic Feedback Engine (SAFE)...");

  // 1. Fetch recently closed PRs that were NOT merged (likely rejected by humans or failed CI)
  const out = exec(`gh pr list --repo ${repoEnv} --state closed --limit 20 --json number,title,mergedAt,comments`);
  if (!out) return;
  
  const closedPrs = JSON.parse(out).filter(pr => !pr.mergedAt);
  if (closedPrs.length === 0) {
    console.log("No recently failed/rejected PRs to learn from.");
    return;
  }

  console.log(`Found ${closedPrs.length} rejected/closed PRs. Analyzing for lessons...`);

  let aggregatedFailures = "";
  for (const pr of closedPrs.slice(0, 5)) { // Limit to top 5 to respect context windows
    const diff = exec(`gh pr diff ${pr.number} --repo ${repoEnv}`, true);
    if (diff) {
      aggregatedFailures += `\n\n--- REJECTED PR #${pr.number}: ${pr.title} ---\n`;
      aggregatedFailures += `COMMENTS: ${pr.comments?.map(c => c.body).join(" | ")}\n`;
      aggregatedFailures += `DIFF SNIPPET:\n${diff.substring(0, 3000)}\n`;
    }
  }

  if (!aggregatedFailures) return;

  const prompt = `You are the Summit Meta-Cognitive Engine. Your job is to analyze failed Pull Requests generated by AI agents or humans, identify the root cause of the failure (e.g., architectural boundary violation, hallucinated API, missing tests, CI pipeline failure), and synthesize a highly concise, generalized rule to prevent this from happening again.

FAILED PR DATA:
${aggregatedFailures}

Extract ONLY the core technical lessons. Format as a bulleted markdown list. Start each bullet with "CRITICAL RULE:". Do not mention PR numbers, just the generalized architectural or coding rule.
If the failure was trivial (like a typo), ignore it. Focus on systemic, architectural, or API usage failures.`;

  let newLearnings = null;
  if (process.env.ANTHROPIC_API_KEY) {
    newLearnings = await callAI(prompt, process.env.ANTHROPIC_API_KEY, "anthropic");
  } else if (process.env.OPENAI_API_KEY) {
    newLearnings = await callAI(prompt, process.env.OPENAI_API_KEY, "openai");
  } else {
    console.log("No AI key available for SAFE.");
    return;
  }

  if (newLearnings && newLearnings.includes("CRITICAL RULE:")) {
    const filePath = ".learnings/AGENT_DIRECTIVES.md";
    let existing = "";
    try {
      existing = await fs.readFile(filePath, "utf8");
    } catch (e) {
      existing = "# Summit Agent Directives\n\nThese are auto-generated rules synthesized from past failures. ALL AGENTS MUST OBEY THESE STRICTLY.\n\n";
    }

    // Append new learnings if they aren't already exactly in there
    const updated = existing + `\n## Learnt on ${new Date().toISOString().split('T')[0]}\n` + newLearnings + "\n";
    await fs.writeFile(filePath, updated);
    console.log(`\nNew Agent Directives Synthesized and saved to ${filePath}:\n${newLearnings}`);
    
    // Commit the new learnings so they enter the repo context permanently
    exec(`git add ${filePath}`);
    exec(`git commit -m "chore(governance): SAFE synthesized new agent directives"`, true);
    exec(`git push origin main`, true); // Assuming running on main or an admin branch
  } else {
    console.log("No new systemic rules synthesized.");
  }
}

main().catch(console.error);
