CREATE OR REPLACE FUNCTION "ORDERS_REVENUE_V1"()
RETURNS TABLE (
  "ORDER_ID" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "TOTAL_REVENUE" NUMBER,
  "ORDER_COUNT" NUMBER
)
AS
$$
SELECT
  "ORDER_ID",
  "CUSTOMER_ID",
  SUM(amount) AS "TOTAL_REVENUE",
  COUNT(DISTINCT order_id) AS "ORDER_COUNT"
FROM analytics.orders
WHERE
  "ORDER_STATUS" = 'completed'
GROUP BY
  "ORDER_ID",
  "CUSTOMER_ID"
$$
LANGUAGE SQL;
