CREATE OR REPLACE VIEW "ORDERS_REVENUE_V1" AS
SELECT
  "ORDER_ID",
  "CUSTOMER_ID",
  SUM(amount) AS "TOTAL_REVENUE",
  COUNT(DISTINCT order_id) AS "ORDER_COUNT"
FROM analytics.orders
WHERE
  "ORDER_STATUS" = 'completed'
GROUP BY
  "ORDER_ID",
  "CUSTOMER_ID"
;
