"use strict";
/**
 * Alert Schemas
 *
 * Defines the structure of alerts generated by the signal processing pipeline.
 * Alerts are the primary output of the rule engine when conditions are met.
 *
 * @module alert
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateAlertInputSchema = exports.CreateAlertInputSchema = exports.AlertSchema = exports.AlertActionSchema = exports.AlertContextSchema = exports.TriggeringRuleSchema = exports.SignalReferenceSchema = exports.AlertType = exports.AlertStatus = exports.AlertSeverity = void 0;
exports.createAlert = createAlert;
exports.createAlertFromSignal = createAlertFromSignal;
exports.validateAlert = validateAlert;
exports.shouldSuppressAlert = shouldSuppressAlert;
exports.calculateAlertPriority = calculateAlertPriority;
const zod_1 = require("zod");
/**
 * Alert severity levels
 */
exports.AlertSeverity = {
    INFO: 'info',
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    CRITICAL: 'critical',
};
/**
 * Alert status lifecycle
 */
exports.AlertStatus = {
    NEW: 'new',
    ACKNOWLEDGED: 'acknowledged',
    IN_PROGRESS: 'in_progress',
    RESOLVED: 'resolved',
    SUPPRESSED: 'suppressed',
    FALSE_POSITIVE: 'false_positive',
    ESCALATED: 'escalated',
};
/**
 * Alert type categories
 */
exports.AlertType = {
    THRESHOLD: 'threshold',
    PATTERN: 'pattern',
    ANOMALY: 'anomaly',
    CORRELATION: 'correlation',
    TEMPORAL: 'temporal',
    ABSENCE: 'absence',
    RATE: 'rate',
};
/**
 * Reference to a signal that triggered the alert
 */
exports.SignalReferenceSchema = zod_1.z.object({
    /** Signal ID */
    signalId: zod_1.z.string().uuid(),
    /** Signal type */
    signalType: zod_1.z.string(),
    /** Timestamp of the signal */
    timestamp: zod_1.z.number(),
    /** Relevance score (0-1) for this signal in the alert */
    relevance: zod_1.z.number().min(0).max(1).default(1),
    /** Key fields from the signal payload */
    keyFields: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()).optional(),
});
/**
 * Rule that triggered the alert
 */
exports.TriggeringRuleSchema = zod_1.z.object({
    /** Rule ID */
    ruleId: zod_1.z.string(),
    /** Rule name */
    ruleName: zod_1.z.string(),
    /** Rule version */
    ruleVersion: zod_1.z.string(),
    /** Condition that was matched */
    matchedCondition: zod_1.z.string(),
    /** Threshold or pattern that triggered */
    triggerValue: zod_1.z.unknown().optional(),
    /** Actual value that caused the trigger */
    actualValue: zod_1.z.unknown().optional(),
    /** Confidence score for pattern/anomaly matches */
    confidence: zod_1.z.number().min(0).max(1).optional(),
});
/**
 * Alert context with additional metadata
 */
exports.AlertContextSchema = zod_1.z.object({
    /** Investigation ID if part of an active investigation */
    investigationId: zod_1.z.string().optional(),
    /** Case ID if assigned to a case */
    caseId: zod_1.z.string().optional(),
    /** Entity IDs related to this alert */
    relatedEntities: zod_1.z.array(zod_1.z.string()).default([]),
    /** Previous related alerts */
    relatedAlerts: zod_1.z.array(zod_1.z.string()).default([]),
    /** Geographic context */
    location: zod_1.z
        .object({
        latitude: zod_1.z.number(),
        longitude: zod_1.z.number(),
        placeName: zod_1.z.string().optional(),
        country: zod_1.z.string().optional(),
    })
        .optional(),
    /** Time window context */
    timeWindow: zod_1.z
        .object({
        start: zod_1.z.number(),
        end: zod_1.z.number(),
        windowType: zod_1.z.enum(['tumbling', 'sliding', 'session']),
        windowSize: zod_1.z.number(),
    })
        .optional(),
    /** Custom context fields */
    custom: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()).optional(),
});
/**
 * Alert actions and recommendations
 */
exports.AlertActionSchema = zod_1.z.object({
    /** Action type */
    actionType: zod_1.z.enum([
        'investigate',
        'acknowledge',
        'escalate',
        'notify',
        'automate',
        'suppress',
    ]),
    /** Action description */
    description: zod_1.z.string(),
    /** Priority of the action */
    priority: zod_1.z.number().min(1).max(10).default(5),
    /** Automation script/workflow ID */
    automationId: zod_1.z.string().optional(),
    /** Target for notification */
    notificationTarget: zod_1.z.string().optional(),
});
/**
 * Complete Alert schema
 */
exports.AlertSchema = zod_1.z.object({
    /** Unique alert identifier */
    alertId: zod_1.z.string().uuid(),
    /** Alert type */
    alertType: zod_1.z.enum([
        exports.AlertType.THRESHOLD,
        exports.AlertType.PATTERN,
        exports.AlertType.ANOMALY,
        exports.AlertType.CORRELATION,
        exports.AlertType.TEMPORAL,
        exports.AlertType.ABSENCE,
        exports.AlertType.RATE,
    ]),
    /** Alert severity */
    severity: zod_1.z.enum([
        exports.AlertSeverity.INFO,
        exports.AlertSeverity.LOW,
        exports.AlertSeverity.MEDIUM,
        exports.AlertSeverity.HIGH,
        exports.AlertSeverity.CRITICAL,
    ]),
    /** Alert status */
    status: zod_1.z
        .enum([
        exports.AlertStatus.NEW,
        exports.AlertStatus.ACKNOWLEDGED,
        exports.AlertStatus.IN_PROGRESS,
        exports.AlertStatus.RESOLVED,
        exports.AlertStatus.SUPPRESSED,
        exports.AlertStatus.FALSE_POSITIVE,
        exports.AlertStatus.ESCALATED,
    ])
        .default(exports.AlertStatus.NEW),
    /** Tenant ID for multi-tenancy */
    tenantId: zod_1.z.string().min(1),
    /** Alert title */
    title: zod_1.z.string().min(1).max(200),
    /** Detailed description */
    description: zod_1.z.string().max(4000),
    /** Unix timestamp when alert was created */
    createdAt: zod_1.z.number(),
    /** Unix timestamp when alert was last updated */
    updatedAt: zod_1.z.number(),
    /** Unix timestamp when alert expires (optional) */
    expiresAt: zod_1.z.number().optional(),
    /** Rule that triggered this alert */
    triggeringRule: exports.TriggeringRuleSchema,
    /** References to signals that contributed to this alert */
    signalReferences: zod_1.z.array(exports.SignalReferenceSchema).min(1),
    /** Alert context */
    context: exports.AlertContextSchema.default({
        relatedEntities: [],
        relatedAlerts: [],
    }),
    /** Recommended actions */
    recommendedActions: zod_1.z.array(exports.AlertActionSchema).default([]),
    /** Policy labels for access control */
    policyLabels: zod_1.z.array(zod_1.z.string()).default([]),
    /** Classification level */
    classification: zod_1.z.string().optional(),
    /** Tags for categorization */
    tags: zod_1.z.array(zod_1.z.string()).default([]),
    /** Suppression info if suppressed */
    suppression: zod_1.z
        .object({
        suppressedAt: zod_1.z.number(),
        suppressedBy: zod_1.z.string(),
        reason: zod_1.z.string(),
        expiresAt: zod_1.z.number().optional(),
    })
        .optional(),
    /** Acknowledgment info */
    acknowledgment: zod_1.z
        .object({
        acknowledgedAt: zod_1.z.number(),
        acknowledgedBy: zod_1.z.string(),
        notes: zod_1.z.string().optional(),
    })
        .optional(),
    /** Resolution info */
    resolution: zod_1.z
        .object({
        resolvedAt: zod_1.z.number(),
        resolvedBy: zod_1.z.string(),
        resolutionType: zod_1.z.enum([
            'fixed',
            'false_positive',
            'no_action_needed',
            'other',
        ]),
        notes: zod_1.z.string().optional(),
    })
        .optional(),
    /** Schema version */
    schemaVersion: zod_1.z.string().default('1.0.0'),
});
/**
 * Alert creation input (subset of full alert)
 */
exports.CreateAlertInputSchema = zod_1.z.object({
    alertType: exports.AlertSchema.shape.alertType,
    severity: exports.AlertSchema.shape.severity,
    tenantId: zod_1.z.string().min(1),
    title: zod_1.z.string().min(1).max(200),
    description: zod_1.z.string().max(4000),
    triggeringRule: exports.TriggeringRuleSchema,
    signalReferences: zod_1.z.array(exports.SignalReferenceSchema).min(1),
    context: exports.AlertContextSchema.optional(),
    recommendedActions: zod_1.z.array(exports.AlertActionSchema).optional(),
    policyLabels: zod_1.z.array(zod_1.z.string()).optional(),
    classification: zod_1.z.string().optional(),
    tags: zod_1.z.array(zod_1.z.string()).optional(),
});
/**
 * Alert update input
 */
exports.UpdateAlertInputSchema = zod_1.z.object({
    status: exports.AlertSchema.shape.status.optional(),
    severity: exports.AlertSchema.shape.severity.optional(),
    tags: zod_1.z.array(zod_1.z.string()).optional(),
    context: exports.AlertContextSchema.partial().optional(),
    acknowledgment: exports.AlertSchema.shape.acknowledgment.optional(),
    resolution: exports.AlertSchema.shape.resolution.optional(),
    suppression: exports.AlertSchema.shape.suppression.optional(),
});
/**
 * Create a new alert
 */
function createAlert(input) {
    const now = Date.now();
    return {
        alertId: crypto.randomUUID(),
        alertType: input.alertType,
        severity: input.severity,
        status: exports.AlertStatus.NEW,
        tenantId: input.tenantId,
        title: input.title,
        description: input.description,
        createdAt: now,
        updatedAt: now,
        triggeringRule: input.triggeringRule,
        signalReferences: input.signalReferences,
        context: input.context ?? { relatedEntities: [], relatedAlerts: [] },
        recommendedActions: input.recommendedActions ?? [],
        policyLabels: input.policyLabels ?? [],
        classification: input.classification,
        tags: input.tags ?? [],
        schemaVersion: '1.0.0',
    };
}
/**
 * Create alert from signal envelope and rule match
 */
function createAlertFromSignal(envelope, ruleMatch) {
    const now = Date.now();
    return {
        alertId: crypto.randomUUID(),
        alertType: ruleMatch.alertType,
        severity: ruleMatch.severity,
        status: exports.AlertStatus.NEW,
        tenantId: envelope.metadata.tenantId,
        title: ruleMatch.title,
        description: ruleMatch.description,
        createdAt: now,
        updatedAt: now,
        triggeringRule: {
            ruleId: ruleMatch.ruleId,
            ruleName: ruleMatch.ruleName,
            ruleVersion: ruleMatch.ruleVersion,
            matchedCondition: ruleMatch.condition,
            triggerValue: ruleMatch.triggerValue,
            actualValue: ruleMatch.actualValue,
            confidence: ruleMatch.confidence,
        },
        signalReferences: [
            {
                signalId: envelope.metadata.signalId,
                signalType: envelope.metadata.signalType,
                timestamp: envelope.metadata.timestamp,
                relevance: 1,
            },
        ],
        context: {
            relatedEntities: [],
            relatedAlerts: [],
            location: envelope.location
                ? {
                    latitude: envelope.location.latitude,
                    longitude: envelope.location.longitude,
                }
                : undefined,
        },
        recommendedActions: [],
        policyLabels: envelope.metadata.policyLabels,
        classification: envelope.metadata.classification,
        tags: envelope.metadata.tags,
        schemaVersion: '1.0.0',
    };
}
/**
 * Validate an alert
 */
function validateAlert(input) {
    return exports.AlertSchema.safeParse(input);
}
/**
 * Check if alert should be suppressed based on deduplication window
 */
function shouldSuppressAlert(newAlert, existingAlerts, deduplicationWindowMs = 300000) {
    const cutoff = newAlert.createdAt - deduplicationWindowMs;
    return existingAlerts.some((existing) => existing.triggeringRule.ruleId === newAlert.triggeringRule.ruleId &&
        existing.tenantId === newAlert.tenantId &&
        existing.createdAt > cutoff &&
        existing.status !== exports.AlertStatus.RESOLVED &&
        existing.status !== exports.AlertStatus.FALSE_POSITIVE);
}
/**
 * Calculate alert priority score for ordering
 */
function calculateAlertPriority(alert) {
    const severityScores = {
        [exports.AlertSeverity.INFO]: 1,
        [exports.AlertSeverity.LOW]: 2,
        [exports.AlertSeverity.MEDIUM]: 3,
        [exports.AlertSeverity.HIGH]: 4,
        [exports.AlertSeverity.CRITICAL]: 5,
    };
    const typeMultipliers = {
        [exports.AlertType.THRESHOLD]: 1.0,
        [exports.AlertType.PATTERN]: 1.2,
        [exports.AlertType.ANOMALY]: 1.3,
        [exports.AlertType.CORRELATION]: 1.5,
        [exports.AlertType.TEMPORAL]: 1.1,
        [exports.AlertType.ABSENCE]: 1.0,
        [exports.AlertType.RATE]: 1.1,
    };
    const severityScore = severityScores[alert.severity] ?? 3;
    const typeMultiplier = typeMultipliers[alert.alertType] ?? 1.0;
    const signalCount = Math.min(alert.signalReferences.length, 10);
    const confidence = alert.triggeringRule.confidence ?? 1.0;
    return severityScore * typeMultiplier * (1 + signalCount * 0.1) * confidence;
}
