/**
 * Signal Contracts Package
 *
 * Public API for the Signal Bus contract definitions.
 * This package defines the shared schemas, types, and utilities
 * used across the Signal Bus streaming pipeline.
 *
 * @packageDocumentation
 */

// Signal Types
export {
  SignalCategory,
  SignalTypeId,
  SignalTypeRegistry,
  SignalTypeIdSchema,
  getSignalTypeDefinition,
  getSignalTypesByCategory,
  requiresEnrichment,
  getSignalPriority,
  type SignalCategoryType,
  type SignalTypeIdType,
  type SignalTypeDefinition,
} from './signal-types.js';

// Signal Envelope
export {
  SignalQuality,
  SignalSourceSchema,
  GeoLocationSchema,
  DeviceInfoSchema,
  ProvenanceSchema,
  EnrichmentDataSchema,
  SignalMetadataSchema,
  SignalEnvelopeSchema,
  RawSignalInputSchema,
  createSignalEnvelope,
  addProvenanceStep,
  validateSignalEnvelope,
  getPartitionKey,
  getRoutingKey,
  type SignalQualityType,
  type SignalSource,
  type GeoLocation,
  type DeviceInfo,
  type Provenance,
  type EnrichmentData,
  type SignalMetadata,
  type SignalEnvelope,
  type RawSignalInput,
} from './signal-envelope.js';

// Alerts
export {
  AlertSeverity,
  AlertStatus,
  AlertType,
  SignalReferenceSchema,
  TriggeringRuleSchema,
  AlertContextSchema,
  AlertActionSchema,
  AlertSchema,
  CreateAlertInputSchema,
  UpdateAlertInputSchema,
  createAlert,
  createAlertFromSignal,
  validateAlert,
  shouldSuppressAlert,
  calculateAlertPriority,
  type AlertSeverityType,
  type AlertStatusType,
  type AlertTypeType,
  type SignalReference,
  type TriggeringRule,
  type AlertContext,
  type AlertAction,
  type Alert,
  type CreateAlertInput,
  type UpdateAlertInput,
} from './alert.js';

// Rules
export {
  ComparisonOperator,
  LogicalOperator,
  WindowType,
  RuleStatus,
  SimpleConditionSchema,
  CompoundConditionSchema,
  ConditionSchema,
  RuleBaseSchema,
  ThresholdRuleSchema,
  PatternRuleSchema,
  TemporalRuleSchema,
  RateRuleSchema,
  AbsenceRuleSchema,
  AnomalyRuleSchema,
  CorrelationRuleSchema,
  RuleSchema,
  RuleEvaluationResultSchema,
  createThresholdRule,
  createPatternRule,
  createRateRule,
  createAbsenceRule,
  validateRule,
  ruleAppliesToSignalType,
  sortRulesByPriority,
  type ComparisonOperatorType,
  type LogicalOperatorType,
  type WindowTypeType,
  type RuleStatusType,
  type SimpleCondition,
  type CompoundCondition,
  type Condition,
  type RuleBase,
  type ThresholdRule,
  type PatternRule,
  type TemporalRule,
  type RateRule,
  type AbsenceRule,
  type AnomalyRule,
  type CorrelationRule,
  type Rule,
  type RuleEvaluationResult,
} from './rules.js';

// Downstream Integration
export {
  DownstreamEventType,
  DownstreamEventBaseSchema,
  GraphEntitySuggestedSchema,
  GraphRelationshipSuggestedSchema,
  GraphEnrichmentSchema,
  SpacetimeEventSchema,
  SpacetimeTrackSchema,
  CaseTaskSuggestedSchema,
  CaseWatchlistHitSchema,
  CaseAlertNotificationSchema,
  AnalyticsMetricSchema,
  AnalyticsAggregationSchema,
  createGraphEntitySuggestion,
  createSpacetimeEvent,
  createCaseTaskFromAlert,
  createCaseAlertNotification,
  validateDownstreamEvent,
  type DownstreamEventTypeType,
  type DownstreamEventBase,
  type GraphEntitySuggested,
  type GraphRelationshipSuggested,
  type GraphEnrichment,
  type SpacetimeEvent,
  type SpacetimeTrack,
  type CaseTaskSuggested,
  type CaseWatchlistHit,
  type CaseAlertNotification,
  type AnalyticsMetric,
  type AnalyticsAggregation,
  type DownstreamEvent,
} from './downstream.js';

// Topics
export {
  TopicNamespace,
  SignalTopics,
  TopicConfigs,
  ConsumerGroups,
  getCategoryTopic,
  getSignalPartitionKey,
  getAlertPartitionKey,
  getDownstreamTopic,
  isHighPriorityAlert,
  getAllTopicNames,
  getAllTopicConfigs,
  TopicHealthChecks,
  type SignalTopicType,
  type TopicConfig,
  type ConsumerGroupType,
  type TopicHealthCheck,
} from './topics.js';
