"use strict";
/**
 * Signal Type Registry
 *
 * Defines all supported signal types in the IntelGraph platform.
 * Each signal type has a unique identifier, category, and schema version.
 *
 * @module signal-types
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SignalTypeRegistry = exports.SignalTypeIdSchema = exports.SignalTypeId = exports.SignalCategory = void 0;
exports.getSignalTypeDefinition = getSignalTypeDefinition;
exports.getSignalTypesByCategory = getSignalTypesByCategory;
exports.requiresEnrichment = requiresEnrichment;
exports.getSignalPriority = getSignalPriority;
const zod_1 = require("zod");
/**
 * Signal categories for high-level classification
 */
exports.SignalCategory = {
    SENSOR: 'sensor',
    TELEMETRY: 'telemetry',
    COMMS: 'comms',
    LOG: 'log',
    ALERT: 'alert',
    SYSTEM: 'system',
};
/**
 * Signal type identifiers - the canonical registry of all signal types
 */
exports.SignalTypeId = {
    // Sensor signals
    SENSOR_GEOLOCATION: 'sensor.geolocation',
    SENSOR_BIOMETRIC: 'sensor.biometric',
    SENSOR_ENVIRONMENTAL: 'sensor.environmental',
    SENSOR_MOTION: 'sensor.motion',
    SENSOR_PROXIMITY: 'sensor.proximity',
    SENSOR_RFID: 'sensor.rfid',
    SENSOR_ACOUSTIC: 'sensor.acoustic',
    SENSOR_OPTICAL: 'sensor.optical',
    // Telemetry signals
    TELEMETRY_DEVICE_STATUS: 'telemetry.device_status',
    TELEMETRY_NETWORK_ACTIVITY: 'telemetry.network_activity',
    TELEMETRY_RESOURCE_USAGE: 'telemetry.resource_usage',
    TELEMETRY_HEARTBEAT: 'telemetry.heartbeat',
    TELEMETRY_BATTERY: 'telemetry.battery',
    // Communications signals
    COMMS_MESSAGE: 'comms.message',
    COMMS_CALL: 'comms.call',
    COMMS_EMAIL: 'comms.email',
    COMMS_SOCIAL_MEDIA: 'comms.social_media',
    COMMS_RADIO: 'comms.radio',
    // Log signals
    LOG_ACCESS: 'log.access',
    LOG_AUDIT: 'log.audit',
    LOG_SECURITY: 'log.security',
    LOG_APPLICATION: 'log.application',
    LOG_SYSTEM: 'log.system',
    // Alert signals (generated by the platform)
    ALERT_THRESHOLD: 'alert.threshold',
    ALERT_PATTERN: 'alert.pattern',
    ALERT_ANOMALY: 'alert.anomaly',
    ALERT_CORRELATION: 'alert.correlation',
    // System signals
    SYSTEM_CONFIG_CHANGE: 'system.config_change',
    SYSTEM_DEPLOYMENT: 'system.deployment',
    SYSTEM_HEALTH: 'system.health',
};
/**
 * Schema for validating signal type identifiers
 */
exports.SignalTypeIdSchema = zod_1.z.enum([
    exports.SignalTypeId.SENSOR_GEOLOCATION,
    exports.SignalTypeId.SENSOR_BIOMETRIC,
    exports.SignalTypeId.SENSOR_ENVIRONMENTAL,
    exports.SignalTypeId.SENSOR_MOTION,
    exports.SignalTypeId.SENSOR_PROXIMITY,
    exports.SignalTypeId.SENSOR_RFID,
    exports.SignalTypeId.SENSOR_ACOUSTIC,
    exports.SignalTypeId.SENSOR_OPTICAL,
    exports.SignalTypeId.TELEMETRY_DEVICE_STATUS,
    exports.SignalTypeId.TELEMETRY_NETWORK_ACTIVITY,
    exports.SignalTypeId.TELEMETRY_RESOURCE_USAGE,
    exports.SignalTypeId.TELEMETRY_HEARTBEAT,
    exports.SignalTypeId.TELEMETRY_BATTERY,
    exports.SignalTypeId.COMMS_MESSAGE,
    exports.SignalTypeId.COMMS_CALL,
    exports.SignalTypeId.COMMS_EMAIL,
    exports.SignalTypeId.COMMS_SOCIAL_MEDIA,
    exports.SignalTypeId.COMMS_RADIO,
    exports.SignalTypeId.LOG_ACCESS,
    exports.SignalTypeId.LOG_AUDIT,
    exports.SignalTypeId.LOG_SECURITY,
    exports.SignalTypeId.LOG_APPLICATION,
    exports.SignalTypeId.LOG_SYSTEM,
    exports.SignalTypeId.ALERT_THRESHOLD,
    exports.SignalTypeId.ALERT_PATTERN,
    exports.SignalTypeId.ALERT_ANOMALY,
    exports.SignalTypeId.ALERT_CORRELATION,
    exports.SignalTypeId.SYSTEM_CONFIG_CHANGE,
    exports.SignalTypeId.SYSTEM_DEPLOYMENT,
    exports.SignalTypeId.SYSTEM_HEALTH,
]);
/**
 * Registry of all signal type definitions with metadata
 */
exports.SignalTypeRegistry = {
    // Sensor signals
    [exports.SignalTypeId.SENSOR_GEOLOCATION]: {
        id: exports.SignalTypeId.SENSOR_GEOLOCATION,
        category: exports.SignalCategory.SENSOR,
        description: 'GPS, cell tower, WiFi positioning data',
        schemaVersion: '1.0.0',
        retentionDays: 90,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.SENSOR_BIOMETRIC]: {
        id: exports.SignalTypeId.SENSOR_BIOMETRIC,
        category: exports.SignalCategory.SENSOR,
        description: 'Fingerprint, facial recognition, voice print data',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'critical',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.SENSOR_ENVIRONMENTAL]: {
        id: exports.SignalTypeId.SENSOR_ENVIRONMENTAL,
        category: exports.SignalCategory.SENSOR,
        description: 'Temperature, humidity, pressure, air quality',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'low',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.SENSOR_MOTION]: {
        id: exports.SignalTypeId.SENSOR_MOTION,
        category: exports.SignalCategory.SENSOR,
        description: 'Accelerometer, gyroscope, magnetometer data',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'medium',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.SENSOR_PROXIMITY]: {
        id: exports.SignalTypeId.SENSOR_PROXIMITY,
        category: exports.SignalCategory.SENSOR,
        description: 'Bluetooth beacons, NFC, proximity sensors',
        schemaVersion: '1.0.0',
        retentionDays: 60,
        priority: 'medium',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.SENSOR_RFID]: {
        id: exports.SignalTypeId.SENSOR_RFID,
        category: exports.SignalCategory.SENSOR,
        description: 'RFID tag reads, asset tracking',
        schemaVersion: '1.0.0',
        retentionDays: 90,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.SENSOR_ACOUSTIC]: {
        id: exports.SignalTypeId.SENSOR_ACOUSTIC,
        category: exports.SignalCategory.SENSOR,
        description: 'Audio signatures, gunshot detection, speech patterns',
        schemaVersion: '1.0.0',
        retentionDays: 90,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.SENSOR_OPTICAL]: {
        id: exports.SignalTypeId.SENSOR_OPTICAL,
        category: exports.SignalCategory.SENSOR,
        description: 'Camera, LIDAR, infrared sensor data',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'high',
        requiresEnrichment: true,
    },
    // Telemetry signals
    [exports.SignalTypeId.TELEMETRY_DEVICE_STATUS]: {
        id: exports.SignalTypeId.TELEMETRY_DEVICE_STATUS,
        category: exports.SignalCategory.TELEMETRY,
        description: 'Device online/offline, connection state',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'medium',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.TELEMETRY_NETWORK_ACTIVITY]: {
        id: exports.SignalTypeId.TELEMETRY_NETWORK_ACTIVITY,
        category: exports.SignalCategory.TELEMETRY,
        description: 'Network traffic, connection metadata',
        schemaVersion: '1.0.0',
        retentionDays: 90,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.TELEMETRY_RESOURCE_USAGE]: {
        id: exports.SignalTypeId.TELEMETRY_RESOURCE_USAGE,
        category: exports.SignalCategory.TELEMETRY,
        description: 'CPU, memory, disk, network utilization',
        schemaVersion: '1.0.0',
        retentionDays: 14,
        priority: 'low',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.TELEMETRY_HEARTBEAT]: {
        id: exports.SignalTypeId.TELEMETRY_HEARTBEAT,
        category: exports.SignalCategory.TELEMETRY,
        description: 'Periodic liveness signals from devices/agents',
        schemaVersion: '1.0.0',
        retentionDays: 7,
        priority: 'low',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.TELEMETRY_BATTERY]: {
        id: exports.SignalTypeId.TELEMETRY_BATTERY,
        category: exports.SignalCategory.TELEMETRY,
        description: 'Battery level, charging state, power events',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'medium',
        requiresEnrichment: false,
    },
    // Communications signals
    [exports.SignalTypeId.COMMS_MESSAGE]: {
        id: exports.SignalTypeId.COMMS_MESSAGE,
        category: exports.SignalCategory.COMMS,
        description: 'Instant messages, SMS, chat communications',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.COMMS_CALL]: {
        id: exports.SignalTypeId.COMMS_CALL,
        category: exports.SignalCategory.COMMS,
        description: 'Voice/video call metadata and recordings',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.COMMS_EMAIL]: {
        id: exports.SignalTypeId.COMMS_EMAIL,
        category: exports.SignalCategory.COMMS,
        description: 'Email metadata, headers, and content',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.COMMS_SOCIAL_MEDIA]: {
        id: exports.SignalTypeId.COMMS_SOCIAL_MEDIA,
        category: exports.SignalCategory.COMMS,
        description: 'Social media posts, interactions, profiles',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'medium',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.COMMS_RADIO]: {
        id: exports.SignalTypeId.COMMS_RADIO,
        category: exports.SignalCategory.COMMS,
        description: 'Radio communications, walkie-talkie, HAM',
        schemaVersion: '1.0.0',
        retentionDays: 90,
        priority: 'high',
        requiresEnrichment: true,
    },
    // Log signals
    [exports.SignalTypeId.LOG_ACCESS]: {
        id: exports.SignalTypeId.LOG_ACCESS,
        category: exports.SignalCategory.LOG,
        description: 'Physical and logical access logs',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.LOG_AUDIT]: {
        id: exports.SignalTypeId.LOG_AUDIT,
        category: exports.SignalCategory.LOG,
        description: 'Audit trail events, compliance logs',
        schemaVersion: '1.0.0',
        retentionDays: 730,
        priority: 'critical',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.LOG_SECURITY]: {
        id: exports.SignalTypeId.LOG_SECURITY,
        category: exports.SignalCategory.LOG,
        description: 'Security events, intrusion detection, firewall',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'critical',
        requiresEnrichment: true,
    },
    [exports.SignalTypeId.LOG_APPLICATION]: {
        id: exports.SignalTypeId.LOG_APPLICATION,
        category: exports.SignalCategory.LOG,
        description: 'Application-level log events',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'low',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.LOG_SYSTEM]: {
        id: exports.SignalTypeId.LOG_SYSTEM,
        category: exports.SignalCategory.LOG,
        description: 'Operating system and infrastructure logs',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'medium',
        requiresEnrichment: false,
    },
    // Alert signals
    [exports.SignalTypeId.ALERT_THRESHOLD]: {
        id: exports.SignalTypeId.ALERT_THRESHOLD,
        category: exports.SignalCategory.ALERT,
        description: 'Threshold-based alerts (value exceeded limit)',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.ALERT_PATTERN]: {
        id: exports.SignalTypeId.ALERT_PATTERN,
        category: exports.SignalCategory.ALERT,
        description: 'Pattern-match alerts (sequence detected)',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.ALERT_ANOMALY]: {
        id: exports.SignalTypeId.ALERT_ANOMALY,
        category: exports.SignalCategory.ALERT,
        description: 'Anomaly detection alerts (statistical deviation)',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'high',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.ALERT_CORRELATION]: {
        id: exports.SignalTypeId.ALERT_CORRELATION,
        category: exports.SignalCategory.ALERT,
        description: 'Cross-signal correlation alerts',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'critical',
        requiresEnrichment: false,
    },
    // System signals
    [exports.SignalTypeId.SYSTEM_CONFIG_CHANGE]: {
        id: exports.SignalTypeId.SYSTEM_CONFIG_CHANGE,
        category: exports.SignalCategory.SYSTEM,
        description: 'Configuration changes in the platform',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'medium',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.SYSTEM_DEPLOYMENT]: {
        id: exports.SignalTypeId.SYSTEM_DEPLOYMENT,
        category: exports.SignalCategory.SYSTEM,
        description: 'Deployment events, version changes',
        schemaVersion: '1.0.0',
        retentionDays: 365,
        priority: 'medium',
        requiresEnrichment: false,
    },
    [exports.SignalTypeId.SYSTEM_HEALTH]: {
        id: exports.SignalTypeId.SYSTEM_HEALTH,
        category: exports.SignalCategory.SYSTEM,
        description: 'Platform health checks and status',
        schemaVersion: '1.0.0',
        retentionDays: 30,
        priority: 'low',
        requiresEnrichment: false,
    },
};
/**
 * Get signal type definition by ID
 */
function getSignalTypeDefinition(typeId) {
    return exports.SignalTypeRegistry[typeId];
}
/**
 * Get all signal types for a category
 */
function getSignalTypesByCategory(category) {
    return Object.values(exports.SignalTypeRegistry).filter((def) => def.category === category);
}
/**
 * Check if a signal type requires enrichment
 */
function requiresEnrichment(typeId) {
    const def = exports.SignalTypeRegistry[typeId];
    return def?.requiresEnrichment ?? false;
}
/**
 * Get signal priority
 */
function getSignalPriority(typeId) {
    const def = exports.SignalTypeRegistry[typeId];
    return def?.priority ?? 'medium';
}
