/**
 * Signal Type Registry
 *
 * Defines all supported signal types in the IntelGraph platform.
 * Each signal type has a unique identifier, category, and schema version.
 *
 * @module signal-types
 */

import { z } from 'zod';

/**
 * Signal categories for high-level classification
 */
export const SignalCategory = {
  SENSOR: 'sensor',
  TELEMETRY: 'telemetry',
  COMMS: 'comms',
  LOG: 'log',
  ALERT: 'alert',
  SYSTEM: 'system',
} as const;

export type SignalCategoryType = (typeof SignalCategory)[keyof typeof SignalCategory];

/**
 * Signal type identifiers - the canonical registry of all signal types
 */
export const SignalTypeId = {
  // Sensor signals
  SENSOR_GEOLOCATION: 'sensor.geolocation',
  SENSOR_BIOMETRIC: 'sensor.biometric',
  SENSOR_ENVIRONMENTAL: 'sensor.environmental',
  SENSOR_MOTION: 'sensor.motion',
  SENSOR_PROXIMITY: 'sensor.proximity',
  SENSOR_RFID: 'sensor.rfid',
  SENSOR_ACOUSTIC: 'sensor.acoustic',
  SENSOR_OPTICAL: 'sensor.optical',

  // Telemetry signals
  TELEMETRY_DEVICE_STATUS: 'telemetry.device_status',
  TELEMETRY_NETWORK_ACTIVITY: 'telemetry.network_activity',
  TELEMETRY_RESOURCE_USAGE: 'telemetry.resource_usage',
  TELEMETRY_HEARTBEAT: 'telemetry.heartbeat',
  TELEMETRY_BATTERY: 'telemetry.battery',

  // Communications signals
  COMMS_MESSAGE: 'comms.message',
  COMMS_CALL: 'comms.call',
  COMMS_EMAIL: 'comms.email',
  COMMS_SOCIAL_MEDIA: 'comms.social_media',
  COMMS_RADIO: 'comms.radio',

  // Log signals
  LOG_ACCESS: 'log.access',
  LOG_AUDIT: 'log.audit',
  LOG_SECURITY: 'log.security',
  LOG_APPLICATION: 'log.application',
  LOG_SYSTEM: 'log.system',

  // Alert signals (generated by the platform)
  ALERT_THRESHOLD: 'alert.threshold',
  ALERT_PATTERN: 'alert.pattern',
  ALERT_ANOMALY: 'alert.anomaly',
  ALERT_CORRELATION: 'alert.correlation',

  // System signals
  SYSTEM_CONFIG_CHANGE: 'system.config_change',
  SYSTEM_DEPLOYMENT: 'system.deployment',
  SYSTEM_HEALTH: 'system.health',
} as const;

export type SignalTypeIdType = (typeof SignalTypeId)[keyof typeof SignalTypeId];

/**
 * Schema for validating signal type identifiers
 */
export const SignalTypeIdSchema = z.enum([
  SignalTypeId.SENSOR_GEOLOCATION,
  SignalTypeId.SENSOR_BIOMETRIC,
  SignalTypeId.SENSOR_ENVIRONMENTAL,
  SignalTypeId.SENSOR_MOTION,
  SignalTypeId.SENSOR_PROXIMITY,
  SignalTypeId.SENSOR_RFID,
  SignalTypeId.SENSOR_ACOUSTIC,
  SignalTypeId.SENSOR_OPTICAL,
  SignalTypeId.TELEMETRY_DEVICE_STATUS,
  SignalTypeId.TELEMETRY_NETWORK_ACTIVITY,
  SignalTypeId.TELEMETRY_RESOURCE_USAGE,
  SignalTypeId.TELEMETRY_HEARTBEAT,
  SignalTypeId.TELEMETRY_BATTERY,
  SignalTypeId.COMMS_MESSAGE,
  SignalTypeId.COMMS_CALL,
  SignalTypeId.COMMS_EMAIL,
  SignalTypeId.COMMS_SOCIAL_MEDIA,
  SignalTypeId.COMMS_RADIO,
  SignalTypeId.LOG_ACCESS,
  SignalTypeId.LOG_AUDIT,
  SignalTypeId.LOG_SECURITY,
  SignalTypeId.LOG_APPLICATION,
  SignalTypeId.LOG_SYSTEM,
  SignalTypeId.ALERT_THRESHOLD,
  SignalTypeId.ALERT_PATTERN,
  SignalTypeId.ALERT_ANOMALY,
  SignalTypeId.ALERT_CORRELATION,
  SignalTypeId.SYSTEM_CONFIG_CHANGE,
  SignalTypeId.SYSTEM_DEPLOYMENT,
  SignalTypeId.SYSTEM_HEALTH,
]);

/**
 * Signal type metadata definition
 */
export interface SignalTypeDefinition {
  id: SignalTypeIdType;
  category: SignalCategoryType;
  description: string;
  schemaVersion: string;
  retentionDays: number;
  priority: 'low' | 'medium' | 'high' | 'critical';
  requiresEnrichment: boolean;
}

/**
 * Registry of all signal type definitions with metadata
 */
export const SignalTypeRegistry: Record<SignalTypeIdType, SignalTypeDefinition> = {
  // Sensor signals
  [SignalTypeId.SENSOR_GEOLOCATION]: {
    id: SignalTypeId.SENSOR_GEOLOCATION,
    category: SignalCategory.SENSOR,
    description: 'GPS, cell tower, WiFi positioning data',
    schemaVersion: '1.0.0',
    retentionDays: 90,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.SENSOR_BIOMETRIC]: {
    id: SignalTypeId.SENSOR_BIOMETRIC,
    category: SignalCategory.SENSOR,
    description: 'Fingerprint, facial recognition, voice print data',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'critical',
    requiresEnrichment: false,
  },
  [SignalTypeId.SENSOR_ENVIRONMENTAL]: {
    id: SignalTypeId.SENSOR_ENVIRONMENTAL,
    category: SignalCategory.SENSOR,
    description: 'Temperature, humidity, pressure, air quality',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'low',
    requiresEnrichment: false,
  },
  [SignalTypeId.SENSOR_MOTION]: {
    id: SignalTypeId.SENSOR_MOTION,
    category: SignalCategory.SENSOR,
    description: 'Accelerometer, gyroscope, magnetometer data',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'medium',
    requiresEnrichment: false,
  },
  [SignalTypeId.SENSOR_PROXIMITY]: {
    id: SignalTypeId.SENSOR_PROXIMITY,
    category: SignalCategory.SENSOR,
    description: 'Bluetooth beacons, NFC, proximity sensors',
    schemaVersion: '1.0.0',
    retentionDays: 60,
    priority: 'medium',
    requiresEnrichment: true,
  },
  [SignalTypeId.SENSOR_RFID]: {
    id: SignalTypeId.SENSOR_RFID,
    category: SignalCategory.SENSOR,
    description: 'RFID tag reads, asset tracking',
    schemaVersion: '1.0.0',
    retentionDays: 90,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.SENSOR_ACOUSTIC]: {
    id: SignalTypeId.SENSOR_ACOUSTIC,
    category: SignalCategory.SENSOR,
    description: 'Audio signatures, gunshot detection, speech patterns',
    schemaVersion: '1.0.0',
    retentionDays: 90,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.SENSOR_OPTICAL]: {
    id: SignalTypeId.SENSOR_OPTICAL,
    category: SignalCategory.SENSOR,
    description: 'Camera, LIDAR, infrared sensor data',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'high',
    requiresEnrichment: true,
  },

  // Telemetry signals
  [SignalTypeId.TELEMETRY_DEVICE_STATUS]: {
    id: SignalTypeId.TELEMETRY_DEVICE_STATUS,
    category: SignalCategory.TELEMETRY,
    description: 'Device online/offline, connection state',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'medium',
    requiresEnrichment: true,
  },
  [SignalTypeId.TELEMETRY_NETWORK_ACTIVITY]: {
    id: SignalTypeId.TELEMETRY_NETWORK_ACTIVITY,
    category: SignalCategory.TELEMETRY,
    description: 'Network traffic, connection metadata',
    schemaVersion: '1.0.0',
    retentionDays: 90,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.TELEMETRY_RESOURCE_USAGE]: {
    id: SignalTypeId.TELEMETRY_RESOURCE_USAGE,
    category: SignalCategory.TELEMETRY,
    description: 'CPU, memory, disk, network utilization',
    schemaVersion: '1.0.0',
    retentionDays: 14,
    priority: 'low',
    requiresEnrichment: false,
  },
  [SignalTypeId.TELEMETRY_HEARTBEAT]: {
    id: SignalTypeId.TELEMETRY_HEARTBEAT,
    category: SignalCategory.TELEMETRY,
    description: 'Periodic liveness signals from devices/agents',
    schemaVersion: '1.0.0',
    retentionDays: 7,
    priority: 'low',
    requiresEnrichment: false,
  },
  [SignalTypeId.TELEMETRY_BATTERY]: {
    id: SignalTypeId.TELEMETRY_BATTERY,
    category: SignalCategory.TELEMETRY,
    description: 'Battery level, charging state, power events',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'medium',
    requiresEnrichment: false,
  },

  // Communications signals
  [SignalTypeId.COMMS_MESSAGE]: {
    id: SignalTypeId.COMMS_MESSAGE,
    category: SignalCategory.COMMS,
    description: 'Instant messages, SMS, chat communications',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.COMMS_CALL]: {
    id: SignalTypeId.COMMS_CALL,
    category: SignalCategory.COMMS,
    description: 'Voice/video call metadata and recordings',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.COMMS_EMAIL]: {
    id: SignalTypeId.COMMS_EMAIL,
    category: SignalCategory.COMMS,
    description: 'Email metadata, headers, and content',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.COMMS_SOCIAL_MEDIA]: {
    id: SignalTypeId.COMMS_SOCIAL_MEDIA,
    category: SignalCategory.COMMS,
    description: 'Social media posts, interactions, profiles',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'medium',
    requiresEnrichment: true,
  },
  [SignalTypeId.COMMS_RADIO]: {
    id: SignalTypeId.COMMS_RADIO,
    category: SignalCategory.COMMS,
    description: 'Radio communications, walkie-talkie, HAM',
    schemaVersion: '1.0.0',
    retentionDays: 90,
    priority: 'high',
    requiresEnrichment: true,
  },

  // Log signals
  [SignalTypeId.LOG_ACCESS]: {
    id: SignalTypeId.LOG_ACCESS,
    category: SignalCategory.LOG,
    description: 'Physical and logical access logs',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: true,
  },
  [SignalTypeId.LOG_AUDIT]: {
    id: SignalTypeId.LOG_AUDIT,
    category: SignalCategory.LOG,
    description: 'Audit trail events, compliance logs',
    schemaVersion: '1.0.0',
    retentionDays: 730,
    priority: 'critical',
    requiresEnrichment: false,
  },
  [SignalTypeId.LOG_SECURITY]: {
    id: SignalTypeId.LOG_SECURITY,
    category: SignalCategory.LOG,
    description: 'Security events, intrusion detection, firewall',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'critical',
    requiresEnrichment: true,
  },
  [SignalTypeId.LOG_APPLICATION]: {
    id: SignalTypeId.LOG_APPLICATION,
    category: SignalCategory.LOG,
    description: 'Application-level log events',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'low',
    requiresEnrichment: false,
  },
  [SignalTypeId.LOG_SYSTEM]: {
    id: SignalTypeId.LOG_SYSTEM,
    category: SignalCategory.LOG,
    description: 'Operating system and infrastructure logs',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'medium',
    requiresEnrichment: false,
  },

  // Alert signals
  [SignalTypeId.ALERT_THRESHOLD]: {
    id: SignalTypeId.ALERT_THRESHOLD,
    category: SignalCategory.ALERT,
    description: 'Threshold-based alerts (value exceeded limit)',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: false,
  },
  [SignalTypeId.ALERT_PATTERN]: {
    id: SignalTypeId.ALERT_PATTERN,
    category: SignalCategory.ALERT,
    description: 'Pattern-match alerts (sequence detected)',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: false,
  },
  [SignalTypeId.ALERT_ANOMALY]: {
    id: SignalTypeId.ALERT_ANOMALY,
    category: SignalCategory.ALERT,
    description: 'Anomaly detection alerts (statistical deviation)',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'high',
    requiresEnrichment: false,
  },
  [SignalTypeId.ALERT_CORRELATION]: {
    id: SignalTypeId.ALERT_CORRELATION,
    category: SignalCategory.ALERT,
    description: 'Cross-signal correlation alerts',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'critical',
    requiresEnrichment: false,
  },

  // System signals
  [SignalTypeId.SYSTEM_CONFIG_CHANGE]: {
    id: SignalTypeId.SYSTEM_CONFIG_CHANGE,
    category: SignalCategory.SYSTEM,
    description: 'Configuration changes in the platform',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'medium',
    requiresEnrichment: false,
  },
  [SignalTypeId.SYSTEM_DEPLOYMENT]: {
    id: SignalTypeId.SYSTEM_DEPLOYMENT,
    category: SignalCategory.SYSTEM,
    description: 'Deployment events, version changes',
    schemaVersion: '1.0.0',
    retentionDays: 365,
    priority: 'medium',
    requiresEnrichment: false,
  },
  [SignalTypeId.SYSTEM_HEALTH]: {
    id: SignalTypeId.SYSTEM_HEALTH,
    category: SignalCategory.SYSTEM,
    description: 'Platform health checks and status',
    schemaVersion: '1.0.0',
    retentionDays: 30,
    priority: 'low',
    requiresEnrichment: false,
  },
};

/**
 * Get signal type definition by ID
 */
export function getSignalTypeDefinition(
  typeId: SignalTypeIdType,
): SignalTypeDefinition | undefined {
  return SignalTypeRegistry[typeId];
}

/**
 * Get all signal types for a category
 */
export function getSignalTypesByCategory(
  category: SignalCategoryType,
): SignalTypeDefinition[] {
  return Object.values(SignalTypeRegistry).filter(
    (def) => def.category === category,
  );
}

/**
 * Check if a signal type requires enrichment
 */
export function requiresEnrichment(typeId: SignalTypeIdType): boolean {
  const def = SignalTypeRegistry[typeId];
  return def?.requiresEnrichment ?? false;
}

/**
 * Get signal priority
 */
export function getSignalPriority(
  typeId: SignalTypeIdType,
): 'low' | 'medium' | 'high' | 'critical' {
  const def = SignalTypeRegistry[typeId];
  return def?.priority ?? 'medium';
}
