name: benchmark-network

on:
  pull_request:
    paths:
      - 'benchmarks/interactive/runners/network_runner.*'
      - '.github/workflows/benchmark-network.yml'
  push:
    branches: [main]

jobs:
  network-benchmarks:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      run-tests: true
      workspace-filter: ""
