name: Docs Lint

on:
  pull_request:
    paths:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # v4
      - name: Setup Node.js
        uses: actions/setup-node@v4 # v6
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Run Markdown Lint
        run: pnpm dlx markdownlint-cli '**/*.md' --ignore 'node_modules' --disable MD060 MD036 MD032 MD022 MD040 MD030 MD034 MD058 MD013 MD033 MD031 MD029 MD007 MD009 MD014 MD024 MD025 MD026 MD012 MD047 MD037 MD038 MD041 MD051 MD052 MD056 MD001 MD004 MD049 MD055 MD035 MD053 MD010 MD018 MD059 MD046 MD045 MD011 MD050 MD005 MD028 MD023 MD042
