name: Infra Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'src/platform/infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy Infra
        run: echo "Deploying infrastructure..."
permissions:
  contents: read
