export const CPEM_EVIDENCE_IDS = {
  FACILITY_PRIVACY: 'EVD-CPEM-FAC-001',
  MESH_OVERLAY: 'EVD-CPEM-MESH-001',
  PATTERNS: 'EVD-CPEM-PAT-001',
  DETECTORS: 'EVD-CPEM-DET-001',
  SES: 'EVD-CPEM-SES-001',
  API: 'EVD-CPEM-API-001',
};
